'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api-client';
import {useSession} from '../session-provider';
import {ReasonDialog} from '../reason-dialog';
type History={history:{id:string;category:string;text:string;at:string;author:string;supersedesId:string|null}[];flags:{id:string;type:string;value:string;resolvedAt:string|null;reason:string|null}[]};
export function PatientHistory({patientId,onChanged}:{patientId:string;onChanged?:()=>void}){const user=useSession(),[data,setData]=useState<History|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<History['history'][number]|null>(null);const [resolving,setResolving]=useState<string|null>(null);const path='/api/patients/'+patientId+'/history';async function refresh(){try{setData(await api(path));}catch{setError('Unable to load patient history.');}}useEffect(()=>{void refresh();},[path]);async function save(body:unknown){setBusy(true);setError('');try{await api(path,body);setEditing(null);await refresh();onChanged?.();return true;}catch{setError('Unable to save. Refresh and check the entries.');return false;}finally{setBusy(false);}}
return <section className="record-section"><h3>History, allergies and risks</h3>{error&&<p role="alert">{error}</p>}{data?.history.map(h=><article className="ops-record-summary" key={h.id}><strong>{h.category}{data.history.some(v=>v.supersedesId===h.id)?' (amended)':''}</strong><p>{h.text}</p><small>{h.author} · {new Date(h.at).toLocaleString()}</small>{user.permissions.includes('history:write')&&!data.history.some(v=>v.supersedesId===h.id)&&<button className="text-button" onClick={()=>setEditing(h)}>Amend</button>}</article>)}{data?.flags.map(f=><article key={f.id}><p><strong>{f.type}: </strong>{f.value} {f.resolvedAt?'(resolved)':''}</p>{f.reason&&<small>{f.reason}</small>}{!f.resolvedAt&&user.permissions.includes('history:write')&&<button className="text-button" disabled={busy} onClick={()=>setResolving(f.id)}>Resolve flag</button>}</article>)}{user.permissions.includes('history:write')&&<><form key={editing?.id||'new'} className="admin-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);if(await save({action:'history',category:f.get('category'),text:f.get('text'),supersedesId:editing?.id??null}))form.reset();}}><h4>{editing?'Amend history':'Add history'}</h4><label>Category<select name="category" defaultValue={editing?.category||'medical'}>{(editing?[editing.category]:['medical','ocular','family','surgical','drug']).map(c=><option key={c}>{c}</option>)}</select></label><label>Details<textarea name="text" defaultValue={editing?.text||''} required maxLength={3000}/></label><button className="secondary-button" disabled={busy}>Save history</button>{editing&&<button type="button" onClick={()=>setEditing(null)}>Cancel amendment</button>}</form><form className="admin-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);if(await save({action:'flag',type:f.get('type'),value:f.get('value')}))form.reset();}}><label>Flag type<select name="type"><option value="allergy">Allergy</option><option value="risk">Risk</option></select></label><label>Details<input name="value" required maxLength={160}/></label><button className="secondary-button" disabled={busy}>Add flag</button></form></>}{resolving&&<ReasonDialog title="resolveFlagReason" busy={busy} onClose={()=>setResolving(null)} onConfirm={async reason=>{if(await save({action:'resolve',id:resolving,reason}))setResolving(null);}}/>}</section>;
}
