'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api-client';
import { HISTORY_CATEGORIES, HISTORY_LATERALITIES, type PatientHistoryData, type PatientHistoryEntry } from '@/lib/patient-history';
import { useSession } from '../session-provider';
import { ReasonDialog } from '../reason-dialog';

const categoryLabels:Record<(typeof HISTORY_CATEGORIES)[number],string>={medical:'Systemic / medical',ocular:'Ocular disorder',family:'Family history',surgical:'Previous procedure',drug:'Medication history'};

export function StructuredPatientHistory({patientId,onChanged}:{patientId:string;onChanged?:()=>void}){
 const user=useSession(),[data,setData]=useState<PatientHistoryData|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<PatientHistoryEntry|null>(null),[resolving,setResolving]=useState<string|null>(null);
 const path='/api/patients/'+patientId+'/history';
 async function refresh(){try{setData(await api(path));setError('');}catch{setError('Unable to load patient history.');}}
 useEffect(()=>{void refresh();},[path]);
 async function save(body:unknown){setBusy(true);setError('');try{await api(path,body);setEditing(null);await refresh();onChanged?.();return true;}catch{setError('Unable to save. Refresh and check the entries.');return false;}finally{setBusy(false);}}
 const current=data?.history.filter(item=>!data.history.some(value=>value.supersedesId===item.id))??[];
 return <section className="record-section patient-structured-history">
  <div className="registry-heading"><div><h3>Structured clinical history</h3><p>Ocular and systemic conditions, procedures, medicines, and family history remain attributed and amendment-based.</p></div>{data&&<span className="intake-status">{current.filter(item=>item.status==='active').length} active</span>}</div>
  {error&&<p role="alert" className="form-error">{error}</p>}
  <div className="history-entry-grid">{current.map(item=><article className={'history-entry '+item.status} key={item.id}><div><strong>{item.title}</strong><span>{categoryLabels[item.category]}{item.laterality!=='none'?' / '+item.laterality:''}</span></div><p>{item.text}</p><dl><div><dt>Status</dt><dd>{item.status}</dd></div><div><dt>Onset</dt><dd>{item.onsetDate||'Not recorded'}</dd></div>{item.resolvedDate&&<div><dt>Resolved</dt><dd>{item.resolvedDate}</dd></div>}</dl><small>{item.author} / {new Date(item.at).toLocaleString()}</small>{user.permissions.includes('history:write')&&<button type="button" className="text-button" onClick={()=>setEditing(item)}>Amend</button>}</article>)}</div>
  {current.length===0&&<p className="intake-empty">No structured history has been recorded.</p>}
  {user.permissions.includes('history:write')&&<><form key={editing?.id||'new'} className="admin-form history-entry-form" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget,values=new FormData(form);if(await save({action:'history',category:values.get('category'),title:values.get('title'),status:values.get('status'),laterality:values.get('laterality'),onsetDate:values.get('onsetDate')||'',resolvedDate:values.get('status')==='resolved'?values.get('resolvedDate')||'':'',text:values.get('text'),supersedesId:editing?.id??null}))form.reset();}}><h4>{editing?'Amend clinical history':'Add clinical history'}</h4><div className="admin-grid"><label>Category<select name="category" defaultValue={editing?.category||'ocular'}>{HISTORY_CATEGORIES.map(category=><option value={category} key={category}>{categoryLabels[category]}</option>)}</select></label><label>Title<input name="title" required minLength={2} maxLength={160} defaultValue={editing?.title||''}/></label><label>Status<select name="status" defaultValue={editing?.status||'active'}><option value="active">Active</option><option value="resolved">Resolved</option></select></label><label>Eye<select name="laterality" defaultValue={editing?.laterality||'none'}>{HISTORY_LATERALITIES.map(value=><option value={value} key={value}>{value==='none'?'Not eye-specific':value}</option>)}</select></label><label>Onset date<input name="onsetDate" type="date" defaultValue={editing?.onsetDate||''}/></label><label>Resolution date<input name="resolvedDate" type="date" defaultValue={editing?.resolvedDate||''}/></label></div><label>Clinical details<textarea name="text" defaultValue={editing?.text||''} required maxLength={3000}/></label><div className="admin-actions"><button className="secondary-button" disabled={busy}>Save history</button>{editing&&<button type="button" className="text-button" onClick={()=>setEditing(null)}>Cancel amendment</button>}</div></form>
  <form className="admin-form history-flag-form" onSubmit={async event=>{event.preventDefault();const form=event.currentTarget,values=new FormData(form);if(await save({action:'flag',type:values.get('type'),value:values.get('value')}))form.reset();}}><h4>Safety flags</h4><div className="admin-grid"><label>Flag type<select name="type"><option value="allergy">Allergy</option><option value="risk">Risk</option></select></label><label>Details<input name="value" required maxLength={160}/></label></div><button className="secondary-button" disabled={busy}>Add flag</button></form></>}
  {data?.flags.map(flag=><article className="history-flag" key={flag.id}><p><strong>{flag.type}: </strong>{flag.value} {flag.resolvedAt?'(resolved)':''}</p>{flag.reason&&<small>{flag.reason}</small>}{!flag.resolvedAt&&user.permissions.includes('history:write')&&<button type="button" className="text-button" disabled={busy} onClick={()=>setResolving(flag.id)}>Resolve flag</button>}</article>)}
  {resolving&&<ReasonDialog title="resolveFlagReason" busy={busy} onClose={()=>setResolving(null)} onConfirm={async reason=>{if(await save({action:'resolve',id:resolving,reason}))setResolving(null);}}/>}
 </section>;
}
