ALTER TABLE app.prescription_item ADD COLUMN quantity integer CHECK(quantity BETWEEN 1 AND 10000);
CREATE TABLE app.stock_batch (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,facility_id uuid NOT NULL,drug_id uuid NOT NULL,batch_number text NOT NULL,expiry date NOT NULL,unit_cost_paisa bigint NOT NULL CHECK(unit_cost_paisa>=0),quarantined boolean NOT NULL DEFAULT false,
 UNIQUE(tenant_id,id),UNIQUE(tenant_id,facility_id,drug_id,batch_number),FOREIGN KEY(tenant_id,facility_id) REFERENCES app.facility(tenant_id,id),FOREIGN KEY(tenant_id,drug_id) REFERENCES app.formulary(tenant_id,id)
);
CREATE TABLE app.stock_movement (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,batch_id uuid NOT NULL,quantity integer NOT NULL CHECK(quantity<>0),kind text NOT NULL CHECK(kind IN ('receipt','adjustment','dispense','transfer')),reason text NOT NULL,actor_id uuid NOT NULL,at timestamptz NOT NULL DEFAULT now(),request_id uuid NOT NULL,
 UNIQUE(tenant_id,id),UNIQUE(tenant_id,request_id,batch_id),FOREIGN KEY(tenant_id,batch_id) REFERENCES app.stock_batch(tenant_id,id),FOREIGN KEY(tenant_id,actor_id) REFERENCES app.user_account(tenant_id,id)
);
CREATE TABLE app.stock_threshold(tenant_id uuid NOT NULL,facility_id uuid NOT NULL,drug_id uuid NOT NULL,minimum integer NOT NULL CHECK(minimum>=0),PRIMARY KEY(tenant_id,facility_id,drug_id),FOREIGN KEY(tenant_id,facility_id) REFERENCES app.facility(tenant_id,id),FOREIGN KEY(tenant_id,drug_id) REFERENCES app.formulary(tenant_id,id));
CREATE TABLE app.dispense (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,prescription_item_id uuid NOT NULL,movement_id uuid NOT NULL,actor_id uuid NOT NULL,at timestamptz NOT NULL DEFAULT now(),
 FOREIGN KEY(tenant_id,prescription_item_id) REFERENCES app.prescription_item(tenant_id,id),FOREIGN KEY(tenant_id,movement_id) REFERENCES app.stock_movement(tenant_id,id),FOREIGN KEY(tenant_id,actor_id) REFERENCES app.user_account(tenant_id,id),UNIQUE(tenant_id,movement_id)
);
CREATE TABLE app.prescription_closure(tenant_id uuid NOT NULL,prescription_id uuid NOT NULL,actor_id uuid NOT NULL,reason text NOT NULL,at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,prescription_id),FOREIGN KEY(tenant_id,prescription_id) REFERENCES app.prescription(tenant_id,id),FOREIGN KEY(tenant_id,actor_id) REFERENCES app.user_account(tenant_id,id));
CREATE TABLE app.service_catalogue(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,name text NOT NULL,category text NOT NULL CHECK(category IN ('consultation','procedure','investigation','optical','pharmacy')),price_paisa bigint NOT NULL CHECK(price_paisa>=0),active boolean NOT NULL DEFAULT true,version integer NOT NULL DEFAULT 1,UNIQUE(tenant_id,id),UNIQUE(tenant_id,name));
CREATE TABLE app.invoice(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,encounter_id uuid NOT NULL,facility_id uuid NOT NULL,currency text NOT NULL DEFAULT 'PKR' CHECK(currency='PKR'),total_paisa bigint NOT NULL CHECK(total_paisa>=0),discount_paisa bigint NOT NULL DEFAULT 0 CHECK(discount_paisa>=0),discount_reason text NOT NULL DEFAULT '',created_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),request_id uuid NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,request_id),FOREIGN KEY(tenant_id,encounter_id) REFERENCES app.encounter(tenant_id,id),FOREIGN KEY(tenant_id,facility_id) REFERENCES app.facility(tenant_id,id),FOREIGN KEY(tenant_id,created_by) REFERENCES app.user_account(tenant_id,id));
CREATE TABLE app.invoice_line(tenant_id uuid NOT NULL,invoice_id uuid NOT NULL,position integer NOT NULL,service_id uuid NOT NULL,description text NOT NULL,quantity integer NOT NULL CHECK(quantity>0),unit_price_paisa bigint NOT NULL CHECK(unit_price_paisa>=0),PRIMARY KEY(tenant_id,invoice_id,position),FOREIGN KEY(tenant_id,invoice_id) REFERENCES app.invoice(tenant_id,id),FOREIGN KEY(tenant_id,service_id) REFERENCES app.service_catalogue(tenant_id,id));
CREATE TABLE app.cashier_session(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,facility_id uuid NOT NULL,cashier_id uuid NOT NULL,opening_paisa bigint NOT NULL CHECK(opening_paisa>=0),opened_at timestamptz NOT NULL DEFAULT now(),closed_at timestamptz,counted_paisa bigint,expected_paisa bigint,variance_reason text,UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,facility_id) REFERENCES app.facility(tenant_id,id),FOREIGN KEY(tenant_id,cashier_id) REFERENCES app.user_account(tenant_id,id));
CREATE UNIQUE INDEX cashier_open ON app.cashier_session(tenant_id,cashier_id) WHERE closed_at IS NULL;
CREATE TABLE app.receipt_counter(tenant_id uuid NOT NULL,facility_id uuid NOT NULL,date date NOT NULL,sequence integer NOT NULL,PRIMARY KEY(tenant_id,facility_id,date),FOREIGN KEY(tenant_id,facility_id) REFERENCES app.facility(tenant_id,id));
CREATE TABLE app.payment(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,invoice_id uuid NOT NULL,session_id uuid NOT NULL,amount_paisa bigint NOT NULL CHECK(amount_paisa>0),method text NOT NULL CHECK(method IN ('cash','card','bank_transfer','welfare')),reference text NOT NULL,receipt_number text NOT NULL,actor_id uuid NOT NULL,at timestamptz NOT NULL DEFAULT now(),request_id uuid NOT NULL,UNIQUE(tenant_id,id),UNIQUE(tenant_id,request_id),UNIQUE(tenant_id,receipt_number),FOREIGN KEY(tenant_id,invoice_id) REFERENCES app.invoice(tenant_id,id),FOREIGN KEY(tenant_id,session_id) REFERENCES app.cashier_session(tenant_id,id),FOREIGN KEY(tenant_id,actor_id) REFERENCES app.user_account(tenant_id,id));
CREATE TABLE app.refund(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,payment_id uuid NOT NULL,amount_paisa bigint NOT NULL CHECK(amount_paisa>0),reason text NOT NULL,requested_by uuid NOT NULL,requested_at timestamptz NOT NULL DEFAULT now(),approved_by uuid,approved_at timestamptz,session_id uuid,CHECK(approved_by IS NULL OR approved_by<>requested_by),UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,payment_id) REFERENCES app.payment(tenant_id,id),FOREIGN KEY(tenant_id,requested_by) REFERENCES app.user_account(tenant_id,id),FOREIGN KEY(tenant_id,approved_by) REFERENCES app.user_account(tenant_id,id),FOREIGN KEY(tenant_id,session_id) REFERENCES app.cashier_session(tenant_id,id));
CREATE TABLE app.surgery_case(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,encounter_id uuid NOT NULL,facility_id uuid NOT NULL,eye text NOT NULL CHECK(eye IN ('OD','OS')),procedure text NOT NULL,stage text NOT NULL DEFAULT 'estimate',version integer NOT NULL DEFAULT 1,estimate_paisa bigint NOT NULL CHECK(estimate_paisa>=0),scheduled_at timestamptz,created_by uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,encounter_id) REFERENCES app.encounter(tenant_id,id),FOREIGN KEY(tenant_id,facility_id) REFERENCES app.facility(tenant_id,id),FOREIGN KEY(tenant_id,created_by) REFERENCES app.user_account(tenant_id,id),CHECK(stage IN ('estimate','consent','preop','scheduled','operated','discharged','followup','cancelled')));
CREATE TABLE app.surgery_transition(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,case_id uuid NOT NULL,stage text NOT NULL,eye text NOT NULL,notes text NOT NULL,actor_id uuid NOT NULL,at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(tenant_id,case_id) REFERENCES app.surgery_case(tenant_id,id),FOREIGN KEY(tenant_id,actor_id) REFERENCES app.user_account(tenant_id,id));
CREATE TABLE app.consent_document(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,case_id uuid NOT NULL,content bytea NOT NULL,mime text NOT NULL CHECK(mime IN ('application/pdf','image/png','image/jpeg')),filename text NOT NULL,hash text NOT NULL,eye text NOT NULL CHECK(eye IN ('OD','OS')),witness text NOT NULL,actor_id uuid NOT NULL,at timestamptz NOT NULL DEFAULT now(),UNIQUE(tenant_id,id),FOREIGN KEY(tenant_id,case_id) REFERENCES app.surgery_case(tenant_id,id),FOREIGN KEY(tenant_id,actor_id) REFERENCES app.user_account(tenant_id,id),CHECK(octet_length(content) BETWEEN 1 AND 5242880));
DO $policies$ DECLARE item text; BEGIN
 FOREACH item IN ARRAY ARRAY['stock_batch','stock_movement','stock_threshold','dispense','prescription_closure','service_catalogue','invoice','invoice_line','cashier_session','receipt_counter','payment','refund','surgery_case','surgery_transition','consent_document'] LOOP
 EXECUTE format('ALTER TABLE app.%I ENABLE ROW LEVEL SECURITY',item);EXECUTE format('ALTER TABLE app.%I FORCE ROW LEVEL SECURITY',item);EXECUTE format('CREATE POLICY tenant_isolation ON app.%I USING(tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::uuid) WITH CHECK(tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::uuid)',item);EXECUTE format('GRANT SELECT,INSERT ON app.%I TO openeyes_app',item);
 END LOOP;END $policies$;
GRANT UPDATE(quarantined) ON app.stock_batch TO openeyes_app;
GRANT UPDATE(minimum) ON app.stock_threshold TO openeyes_app;
GRANT INSERT ON app.formulary TO openeyes_app;
GRANT UPDATE(active) ON app.formulary TO openeyes_app;
GRANT UPDATE(name,category,price_paisa,active,version) ON app.service_catalogue TO openeyes_app;
GRANT UPDATE(closed_at,counted_paisa,expected_paisa,variance_reason) ON app.cashier_session TO openeyes_app;
GRANT UPDATE(sequence) ON app.receipt_counter TO openeyes_app;
GRANT UPDATE(approved_by,approved_at,session_id) ON app.refund TO openeyes_app;
GRANT UPDATE(stage,version,scheduled_at) ON app.surgery_case TO openeyes_app;
INSERT INTO app.permission(code) VALUES('inventory:write'),('pharmacy:dispense'),('billing:write'),('billing:discount'),('billing:approve_refund'),('surgery:write'),('reports:read') ON CONFLICT DO NOTHING;
INSERT INTO app.role_permission(tenant_id,role_code,permission_code)
 SELECT r.tenant_id,r.code,p.permission FROM app.role r CROSS JOIN (VALUES
 ('inventory_officer','inventory:write'),('pharmacist','pharmacy:dispense'),('cashier','billing:write'),('hospital_admin','billing:discount'),('hospital_admin','billing:approve_refund'),('hospital_admin','inventory:write'),('doctor','surgery:write'),('nurse','surgery:write'),('hospital_admin','surgery:write'),('hospital_admin','reports:read'),('auditor','reports:read'),('cashier','reports:read'),('pharmacist','reports:read'),('inventory_officer','reports:read'),('doctor','reports:read')) AS p(role,permission) WHERE r.code=p.role ON CONFLICT DO NOTHING;
