export const intakeMessages = {
 bookingCancel: "Cancel booking",
 intakeEyebrow: "PATIENT INTAKE", appointmentsTitle: "A clear start to every visit.", appointmentsSubtitle: "Book a clinic slot, confirm arrival, and connect the patient to today's care.",
 queueTitle: "Every patient. One clear next step.", queueSubtitle: "Active encounters across your assigned clinics. Updates every five seconds, including earlier arrivals still in care.",
 workupTitle: "Both eyes. The complete picture.", workupSubtitle: "Record bilateral visual acuity and pressure, then hand the saved workup to the doctor.",
 bookAppointment: "Book appointment", bookingTitle: "Book a clinic appointment", closeBooking: "Close booking", choosePatient: "Choose a patient", selectedPatient: "Selected patient", changePatient: "Change patient", clinicLabel: "Clinic", doctorLabel: "Doctor", appointmentDate: "Appointment date", appointmentTime: "Available slot", chooseSlot: "Choose a slot", noSlots: "No available slots for this doctor and date.", noClinics: "No clinic roster is assigned to your account.", clinicHours: "Demo clinic hours: 09:00–17:00, every day. Slots are 15 minutes. Same-day booking includes earlier slots for the demonstration.", bookingSaved: "Appointment booked.", scheduleLabel: "Clinic schedule", todayLabel: "Today", localTimeLabel: "Asia/Karachi · PKT", allClinics: "All assigned clinics", checkIn: "Check in", checkedIn: "Checked in", booked: "Booked", emptySchedule: "No appointments for this date.", checkInSaved: "Patient checked in and added to the waiting queue.",
 intakeLoading: "Loading clinic data…", liveUpdated: "Last updated", refreshIntake: "Refresh", liveUnavailable: "Live updates paused. Check the connection and retry before acting.",
 stage_waiting: "Waiting", stage_workup: "Workup", stage_dilation: "Dilation", stage_consultation: "Ready for consultation", startWorkup: "Start workup", openWorkup: "Open workup", viewWorkup: "View saved workup", emptyQueue: "No patients at this stage.", elapsedLabel: "min at this stage", arrivalLabel: "Checked in", riskNone: "No recorded risk flags", queueChanged: "Queue stage updated.", workupRecorded: "Workup saved", workupPending: "Workup pending", completeWorkup: "Ready for consultation", startDilation: "Start 20-minute dilation", releaseDilation: "Release to consultation", dilationRemaining: "min of dilation remaining", dilationElapsed: "Dilation timer elapsed", overrideReason: "Early-release reason (at least 8 characters)", dilationHelp: "Dilation is optional. The server starts a 20-minute timer; early release requires an attributed reason. No medication administration is recorded here.",
 encounterLabel: "Encounter", measurementTime: "Measurement time (PKT)", uncorrectedVa: "Uncorrected VA", pinholeVa: "Pinhole VA", correctedVa: "Best-corrected VA", iopLabel: "IOP (mmHg)", iopMethod: "Measurement method", elevatedIop: "Above 21 mmHg · review", notTested: "Not tested", clinicalNotes: "Workup notes", saveWorkup: "Save bilateral workup", savingWorkup: "Saving…", savedBy: "Saved by", revisionLabel: "Revision", closeWorkup: "Close workup", noSavedWorkup: "No workup has been saved for this encounter.", workupReadOnly: "Read-only. Editing is available to the recording nurse or optometrist while the patient is at the workup stage.", workupInstructions: "Enter measurements for OD and OS. CF, HM, PL and NPL remain text values; no acuity conversion is applied.", workupSaveFirst: "Save the bilateral workup before handoff. Handoff locks workup editing.", transitionHistory: "Queue history", unsavedWorkup: "Discard unsaved workup changes?", noWorkupEncounters: "No checked-in encounters in your assigned clinics.", workupEntry: "Bilateral measurements", measurementRequired: "Enter valid measurements for both eyes and check the measurement times.",
 intakeInvalid: "Check the required fields and their values.", slotUnavailable: "This slot is unavailable. Refresh and choose an available clinic slot.", bookingDateInvalid: "Choose today or a date within the next 90 days.", bookingConflict: "The doctor is already booked, or this patient already has an appointment on this date. Refresh the schedule.", appointmentNotFound: "This appointment is unavailable.", alreadyCheckedIn: "This appointment is already checked in. Refresh the schedule.", checkInTodayOnly: "Check-in is available only on the appointment date (PKT).", activeEncounterExists: "This patient already has an active encounter. Open the existing queue entry.", encounterNotFound: "This encounter is unavailable to your account.", encounterLocked: "Workup can be saved only during the workup stage. Refresh to see the current stage.", queueConflict: "The queue changed or this transition is unavailable. Refresh before continuing.", workupRequired: "Save a bilateral workup before advancing this patient.", dilationReasonRequired: "The dilation timer is running. Enter an early-release reason of at least 8 characters.", measurementTimeInvalid: "Measurement times must be between check-in and now (PKT).", workupConflict: "A newer workup revision exists. Close and reopen this encounter before editing.", workupOwnership: "Only the author can revise this workup before handoff.",
 todayAppointments: "Today's appointments", todayCheckedIn: "Today's arrivals", liveWaiting: "Waiting now", liveConsultation: "Ready for the doctor", intakeReady: "Your clinic, connected.", intakeReadyDetail: "Follow booked patients from arrival through saved bilateral workup. Counts reflect your assigned clinics.", openSchedule: "Open schedule", openQueue: "Open live queue", liveCounts: "Live clinic activity", intakeBoundary: "After handoff, the assigned doctor can document, sign, prescribe, and complete the consultation in Doctor Event.",
 audit_appointment_booked: "Appointment booked", audit_appointment_checked_in: "Patient checked in", audit_appointment_list: "Schedule viewed", audit_appointment_seeded: "Demo appointment seeded", audit_queue_viewed: "Queue viewed", audit_queue_transitioned: "Queue stage changed", audit_workup_read: "Workup viewed", audit_workup_saved: "Workup saved",
};
