import 'server-only';
import { hash, verify } from '@node-rs/argon2';
import { z } from 'zod';
import type { PoolClient } from 'pg';
import type { AuthUser, Permission, Session } from '@/lib/access';
import { accessSchema, facilitySchema, passwordSchema, settingsSchema, staffSchema, type AdministrationData } from '@/lib/administration';
import { withTenant } from './db';
import { audit, type AuditContext } from './audit';
import { ApiError } from './http';
import { consumeLimit } from './auth';
export function parseInput<T>(schema:z.ZodType<T>, input:unknown):T {const result=schema.safeParse(input);if(!result.success)throw new ApiError(400,'validationFailed');return result.data;}
export function requireAction(user:AuthUser, permission:Permission){if(!user.permissions.includes(permission))throw new ApiError(403,'accessDenied');}
const hashOptions={algorithm:2 as const,memoryCost:65536,timeCost:3,parallelism:1};
export async function verifyAccountPassword(user:AuthUser,password:string,context:AuditContext) {
 await consumeLimit(`account-reauth:${user.tenantId}:${user.id}`,30,900);
 const row=await withTenant(user.tenantId,user.id,async db=>(await db.query("SELECT password_hash FROM app.user_account WHERE id=$1 AND status='active'",[user.id])).rows[0]);
 if(!row||!await verify(row.password_hash,password).catch(()=>false)){await withTenant(user.tenantId,user.id,db=>audit(db,{tenantId:user.tenantId,actorId:user.id,action:'account.reauth_failed',entityType:'user_account',context}));throw new ApiError(403,'reauthFailed');}return row.password_hash as string;
}
async function checkProof(db:PoolClient,user:AuthUser,proof:string){if(!(await db.query("SELECT 1 FROM app.user_account WHERE id=$1 AND password_hash=$2 AND status='active'",[user.id,proof])).rowCount)throw new ApiError(403,'reauthFailed');}
async function lockAdministration(db:PoolClient,user:AuthUser){await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`administration:${user.tenantId}`]);}
async function log(db:PoolClient,user:AuthUser,context:AuditContext,action:string,id?:string,metadata?:Record<string,unknown>){await audit(db,{tenantId:user.tenantId,actorId:user.id,action,entityType:'administration',entityId:id,metadata,context});}
async function validateFacilities(db:PoolClient,ids:string[]){if((await db.query('SELECT id FROM app.facility WHERE active AND id=ANY($1::uuid[])',[ids])).rowCount!==ids.length)throw new ApiError(400,'facilityRequired');}
export async function administrationData(user:AuthUser,context:AuditContext):Promise<AdministrationData>{requireAction(user,'admin:read');return withTenant(user.tenantId,user.id,async db=>{
 const staff=(await db.query(`SELECT u.id,u.version,u.full_name AS name,u.email,u.designation,u.licence_number AS licence,u.licence_expiry AS "licenceExpiry",u.status,u.must_change_password AS "mustChangePassword",ARRAY(SELECT role_code FROM app.user_role r WHERE r.user_id=u.id ORDER BY role_code) AS roles,ARRAY(SELECT facility_id FROM app.user_facility f WHERE f.user_id=u.id ORDER BY facility_id) AS "facilityIds" FROM app.user_account u ORDER BY u.full_name`)).rows;
 const facilities=(await db.query(`SELECT f.id,f.version,f.name,f.type,f.active,coalesce(s.start_minute,540) AS "startMinute",coalesce(s.end_minute,1020) AS "endMinute",coalesce(s.slot_minutes,15) AS "slotMinutes",coalesce(s.weekdays,ARRAY[0,1,2,3,4,5,6]) AS weekdays,coalesce(s.closed_dates,'{}'::date[])::text[] AS "closedDates",ARRAY(SELECT doctor_id FROM app.clinic_doctor cd WHERE cd.facility_id=f.id AND cd.active ORDER BY doctor_id) AS "doctorIds" FROM app.facility f LEFT JOIN app.clinic_schedule s ON s.facility_id=f.id AND s.tenant_id=f.tenant_id ORDER BY f.name`)).rows;
 const tenant=(await db.query('SELECT name,mrn_prefix,settings,version FROM app.tenant WHERE id=$1',[user.tenantId])).rows[0];
 await log(db,user,context,'administration.read');return {staff,facilities,hospital:{name:tenant.name,mrnPrefix:tenant.mrn_prefix,version:tenant.version,address:'',phone:'',email:'',clinicalIdleMinutes:15,adminIdleMinutes:30,dilationMinutes:20,...tenant.settings}};
 });}
export async function saveStaff(user:AuthUser,input:unknown,context:AuditContext){const data=parseInput(staffSchema,input);requireAction(user,data.id?'staff:write':'account:create');const proof=await verifyAccountPassword(user,data.currentPassword,context);
 const secret=!data.id&&data.temporaryPassword?await hash(data.temporaryPassword,hashOptions):null;if(!data.id&&!secret)throw new ApiError(400,'validationFailed');
 try{return await withTenant(user.tenantId,user.id,async db=>{await lockAdministration(db,user);await checkProof(db,user,proof);await validateFacilities(db,data.facilityIds);
 let id=data.id;
 if(id){const prior=(await db.query('SELECT version FROM app.user_account WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!prior)throw new ApiError(404,'accountNotFound');if(prior.version!==data.version)throw new ApiError(409,'recordChanged');
 const oldRoles=(await db.query('SELECT role_code FROM app.user_role WHERE user_id=$1 ORDER BY role_code',[id])).rows.map(row=>row.role_code);if(JSON.stringify([...data.roles].sort())!==JSON.stringify(oldRoles))throw new ApiError(403,'useAccessManagement');
 if(!user.permissions.includes('account:manage')&&oldRoles.includes('security_admin'))throw new ApiError(403,'accessDenied');
 if(id===user.id){const oldFacilities=(await db.query('SELECT facility_id FROM app.user_facility WHERE user_id=$1 ORDER BY facility_id',[id])).rows.map(row=>row.facility_id);if(JSON.stringify([...data.facilityIds].sort())!==JSON.stringify(oldFacilities))throw new ApiError(403,'selfAccessChange');}
 await db.query('UPDATE app.user_account SET full_name=$2,email=$3,designation=$4,licence_number=$5,licence_expiry=$6,version=version+1 WHERE id=$1',[id,data.name,data.email,data.designation,data.licence,data.licenceExpiry]);
 }else{if(!user.permissions.includes('account:manage')&&data.roles.some(role=>['hospital_admin','security_admin','auditor'].includes(role)))throw new ApiError(403,'accessDenied');
 id=(await db.query('INSERT INTO app.user_account(tenant_id,email,full_name,designation,password_hash,licence_number,licence_expiry,must_change_password) VALUES($1,$2,$3,$4,$5,$6,$7,true) RETURNING id',[user.tenantId,data.email,data.name,data.designation,secret,data.licence,data.licenceExpiry])).rows[0].id;
 for(const role of data.roles)await db.query('INSERT INTO app.user_role(tenant_id,user_id,role_code) VALUES($1,$2,$3)',[user.tenantId,id,role]);}
 await db.query('DELETE FROM app.user_facility WHERE user_id=$1',[id]);for(const facilityId of data.facilityIds)await db.query('INSERT INTO app.user_facility(tenant_id,user_id,facility_id) VALUES($1,$2,$3)',[user.tenantId,id,facilityId]);
 await db.query('DELETE FROM app.session WHERE user_id=$1',[id]);await log(db,user,context,data.id?'staff.updated':'account.created',id,{roles:data.roles,facilityCount:data.facilityIds.length});return {id};
 });}catch(error){if((error as {code?:string}).code==='23505')throw new ApiError(409,'emailExists');throw error;}}
export async function changeAccess(user:AuthUser,input:unknown,context:AuditContext){requireAction(user,'account:manage');const data=parseInput(accessSchema,input);if(data.id===user.id)throw new ApiError(403,'selfAccessChange');const proof=await verifyAccountPassword(user,data.currentPassword,context),secret=data.temporaryPassword?await hash(data.temporaryPassword,hashOptions):null;
 return withTenant(user.tenantId,user.id,async db=>{await lockAdministration(db,user);await checkProof(db,user,proof);const prior=(await db.query('SELECT version FROM app.user_account WHERE id=$1 FOR UPDATE',[data.id])).rows[0];if(!prior)throw new ApiError(404,'accountNotFound');if(prior.version!==data.version)throw new ApiError(409,'recordChanged');
 for(const role of ['security_admin','hospital_admin']){const remaining=(await db.query("SELECT 1 FROM app.user_role r JOIN app.user_account u ON u.id=r.user_id AND u.tenant_id=r.tenant_id WHERE r.role_code=$1 AND u.status='active' AND u.id<>$2 LIMIT 1",[role,data.id])).rowCount;const had=(await db.query('SELECT 1 FROM app.user_role WHERE user_id=$1 AND role_code=$2',[data.id,role])).rowCount;if(had&&!remaining&&(data.status!=='active'||!data.roles.includes(role as 'security_admin'|'hospital_admin')))throw new ApiError(409,'lastAdministrator');}
 await db.query('UPDATE app.user_account SET status=$2,password_hash=coalesce($3,password_hash),must_change_password=CASE WHEN $3::text IS NULL THEN must_change_password ELSE true END,version=version+1 WHERE id=$1',[data.id,data.status,secret]);
 await db.query('DELETE FROM app.user_role WHERE user_id=$1',[data.id]);for(const role of new Set(data.roles))await db.query('INSERT INTO app.user_role(tenant_id,user_id,role_code) VALUES($1,$2,$3)',[user.tenantId,data.id,role]);await db.query('DELETE FROM app.session WHERE user_id=$1',[data.id]);
 await log(db,user,context,'account.access_changed',data.id,{roles:data.roles,status:data.status,passwordReset:!!secret,reason:data.reason});return {ok:true};});}
export async function changeOwnPassword(session:Session,input:unknown,context:AuditContext){const data=parseInput(z.object({currentPassword:z.string().min(1).max(256),password:passwordSchema}).strict(),input);if(data.currentPassword===data.password)throw new ApiError(400,'passwordMustDiffer');const proof=await verifyAccountPassword(session.user,data.currentPassword,context),secret=await hash(data.password,hashOptions);
 return withTenant(session.user.tenantId,session.user.id,async db=>{await db.query('SELECT id FROM app.user_account WHERE id=$1 FOR UPDATE',[session.user.id]);await checkProof(db,session.user,proof);await db.query('UPDATE app.user_account SET password_hash=$2,must_change_password=false,version=version+1 WHERE id=$1',[session.user.id,secret]);await db.query('DELETE FROM app.session WHERE user_id=$1',[session.user.id]);await log(db,session.user,context,'account.password_changed',session.user.id);return {ok:true};});}
export async function saveHospital(user:AuthUser,input:unknown,context:AuditContext){requireAction(user,'settings:write');const data=parseInput(settingsSchema,input);return withTenant(user.tenantId,user.id,async db=>{const {name,mrnPrefix,version,...settings}=data;const result=await db.query('UPDATE app.tenant SET name=$2,mrn_prefix=$3,settings=$4,version=version+1 WHERE id=$1 AND version=$5 RETURNING version',[user.tenantId,name,mrnPrefix,JSON.stringify(settings),version]);if(!result.rowCount)throw new ApiError(409,'recordChanged');await log(db,user,context,'hospital.updated',user.tenantId,{fields:Object.keys(data)});return result.rows[0];});}
export async function saveFacility(user:AuthUser,input:unknown,context:AuditContext){requireAction(user,'settings:write');const data=parseInput(facilitySchema,input);try{return await withTenant(user.tenantId,user.id,async db=>{await lockAdministration(db,user);let id=data.id;if(id){const prior=(await db.query('SELECT * FROM app.facility WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!prior)throw new ApiError(404,'facilityNotFound');if(prior.version!==data.version)throw new ApiError(409,'recordChanged');if(prior.type!==data.type)throw new ApiError(400,'facilityTypeLocked');if(!data.active&&(await db.query("SELECT 1 FROM app.encounter WHERE facility_id=$1 AND closed_at IS NULL UNION ALL SELECT 1 FROM app.appointment WHERE facility_id=$1 AND status='booked' LIMIT 1",[id])).rowCount)throw new ApiError(409,'facilityHasVisits');await db.query('UPDATE app.facility SET name=$2,active=$3,version=version+1 WHERE id=$1',[id,data.name,data.active]);}else{id=(await db.query('INSERT INTO app.facility(tenant_id,name,type,active) VALUES($1,$2,$3,$4) RETURNING id',[user.tenantId,data.name,data.type,data.active])).rows[0].id;}
 if(data.type==='clinic'){
 const valid=(await db.query("SELECT u.id FROM app.user_account u WHERE u.id=ANY($1::uuid[]) AND u.status='active' AND EXISTS(SELECT 1 FROM app.user_role r WHERE r.user_id=u.id AND r.role_code='doctor') AND EXISTS(SELECT 1 FROM app.user_facility f WHERE f.user_id=u.id AND f.facility_id=$2)",[data.doctorIds,id])).rowCount;if(valid!==data.doctorIds.length)throw new ApiError(400,'rosterAssignmentRequired');
 await db.query('INSERT INTO app.clinic_schedule(tenant_id,facility_id,start_minute,end_minute,slot_minutes,weekdays,closed_dates) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(tenant_id,facility_id) DO UPDATE SET start_minute=EXCLUDED.start_minute,end_minute=EXCLUDED.end_minute,slot_minutes=EXCLUDED.slot_minutes,weekdays=EXCLUDED.weekdays,closed_dates=EXCLUDED.closed_dates',[user.tenantId,id,data.startMinute,data.endMinute,data.slotMinutes,[...new Set(data.weekdays)],data.closedDates]);await db.query('UPDATE app.clinic_doctor SET active=false WHERE facility_id=$1',[id]);for(const doctorId of data.doctorIds)await db.query('INSERT INTO app.clinic_doctor(tenant_id,facility_id,doctor_id) VALUES($1,$2,$3) ON CONFLICT(tenant_id,facility_id,doctor_id) DO UPDATE SET active=true',[user.tenantId,id,doctorId]);
 }await log(db,user,context,'facility.updated',id,{active:data.active,type:data.type,rosterCount:data.doctorIds.length});return {id};});}catch(error){if((error as {code?:string}).code==='23505')throw new ApiError(409,'facilityNameExists');throw error;}}
