import 'server-only';
import {z} from 'zod';
import type {PoolClient} from 'pg';
import type {AuthUser,Permission} from '@/lib/access';
import {withTenant} from './db';
import {audit,type AuditContext} from './audit';
import {ApiError} from './http';
import {parseInput,requireAction} from './administration-service';
import {todayKarachi} from '@/lib/patients';
const uuid=z.uuid(),text=(max=500)=>z.string().trim().max(max),reason=text().min(8),money=z.number().int().min(0).max(10000000000),positiveMoney=money.min(1),quantity=z.number().int().min(1).max(10000);
async function lock(db:PoolClient,user:AuthUser){await db.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`operations:${user.tenantId}`]);}
async function facility(db:PoolClient,user:AuthUser,id:string){if(!user.facilityIds.includes(id)||!(await db.query('SELECT 1 FROM app.facility WHERE id=$1 AND active',[id])).rowCount)throw new ApiError(403,'accessDenied');}
async function log(db:PoolClient,user:AuthUser,context:AuditContext,action:string,id?:string,metadata?:Record<string,unknown>){await audit(db,{tenantId:user.tenantId,actorId:user.id,action,entityType:'operations',entityId:id,metadata,context});}
const balance='coalesce((SELECT sum(m.quantity) FROM app.stock_movement m WHERE m.batch_id=b.id),0)::int';
export async function operationsData(user:AuthUser,resource:string,context:AuditContext){const permissions:Record<string,Permission>={inventory:'preview:inventory',billing:'preview:billing',surgery:'preview:surgery',management:'preview:management'};if(!permissions[resource])throw new ApiError(404,'notFound');requireAction(user,permissions[resource]);return withTenant(user.tenantId,user.id,async db=>{const facilities=(await db.query('SELECT id,name,type FROM app.facility WHERE active AND id=ANY($1::uuid[]) ORDER BY name',[user.facilityIds])).rows;let result:Record<string,unknown>={facilities};
 if(resource==='inventory'){
 const drugs=(await db.query('SELECT id,name,strength,therapy_group AS "therapyGroup",active FROM app.formulary ORDER BY name')).rows;
 const batches=(await db.query(`SELECT b.id,b.facility_id AS "facilityId",f.name AS facility,b.drug_id AS "drugId",d.name,d.strength,b.batch_number AS batch,b.expiry,b.unit_cost_paisa::float8 AS "unitCost",b.quarantined,${balance} AS quantity FROM app.stock_batch b JOIN app.formulary d ON d.id=b.drug_id JOIN app.facility f ON f.id=b.facility_id WHERE b.facility_id=ANY($1::uuid[]) ORDER BY b.expiry,b.id`,[user.facilityIds])).rows;
 const thresholds=(await db.query('SELECT facility_id AS "facilityId",drug_id AS "drugId",minimum FROM app.stock_threshold WHERE facility_id=ANY($1::uuid[])',[user.facilityIds])).rows;
 const prescriptions=user.permissions.includes('pharmacy:dispense')?(await db.query(`SELECT r.id,p.mrn,p.given_name||' '||p.family_name AS patient,r.signed_at AS date,EXISTS(SELECT 1 FROM app.prescription_closure c WHERE c.prescription_id=r.id) AS closed,(SELECT coalesce(jsonb_agg(jsonb_build_object('id',i.id,'drugId',i.drug_id,'name',i.name,'strength',i.strength,'eye',i.eye,'quantity',i.quantity,'dispensed',(SELECT coalesce(sum(-m.quantity),0) FROM app.dispense x JOIN app.stock_movement m ON m.id=x.movement_id WHERE x.prescription_item_id=i.id)) ORDER BY i.position),'[]') FROM app.prescription_item i WHERE i.prescription_id=r.id) AS items FROM app.prescription r JOIN app.doctor_event d ON d.id=r.event_id JOIN app.encounter e ON e.id=d.encounter_id JOIN app.patient p ON p.id=e.patient_id WHERE r.status='signed' ORDER BY r.signed_at DESC LIMIT 200`)).rows:[];
 result={...result,drugs,batches,thresholds,prescriptions};
 }else if(resource==='billing'){
 const services=(await db.query('SELECT id,name,category,price_paisa::float8 AS price,active,version FROM app.service_catalogue ORDER BY name')).rows;
 const encounters=(await db.query(`SELECT e.id,p.mrn,p.given_name||' '||p.family_name AS patient,f.name AS clinic,e.facility_id AS "facilityId",e.checked_in_at AS date FROM app.encounter e JOIN app.patient p ON p.id=e.patient_id JOIN app.facility f ON f.id=e.facility_id WHERE e.facility_id=ANY($1::uuid[]) ORDER BY e.checked_in_at DESC LIMIT 200`,[user.facilityIds])).rows;
 const invoices=(await db.query(`SELECT i.id,i.encounter_id AS "encounterId",i.created_at AS date,p.mrn,p.given_name||' '||p.family_name AS patient,i.facility_id AS "facilityId",i.total_paisa::float8 AS total,i.discount_paisa::float8 AS discount,(SELECT coalesce(sum(amount_paisa),0)::float8 FROM app.payment pay WHERE pay.invoice_id=i.id) AS paid,(SELECT coalesce(sum(r.amount_paisa),0)::float8 FROM app.refund r JOIN app.payment pay ON pay.id=r.payment_id WHERE pay.invoice_id=i.id AND r.approved_at IS NOT NULL) AS refunded,(SELECT coalesce(jsonb_agg(jsonb_build_object('description',l.description,'quantity',l.quantity,'price',l.unit_price_paisa) ORDER BY l.position),'[]') FROM app.invoice_line l WHERE l.invoice_id=i.id) AS lines FROM app.invoice i JOIN app.encounter e ON e.id=i.encounter_id JOIN app.patient p ON p.id=e.patient_id WHERE i.facility_id=ANY($1::uuid[]) ORDER BY i.created_at DESC LIMIT 200`,[user.facilityIds])).rows;
 const payments=(await db.query('SELECT p.id,p.invoice_id AS "invoiceId",p.amount_paisa::float8 AS amount,p.method,p.receipt_number AS receipt,p.at FROM app.payment p JOIN app.invoice i ON i.id=p.invoice_id WHERE i.facility_id=ANY($1::uuid[]) ORDER BY p.at DESC LIMIT 500',[user.facilityIds])).rows;
 const sessions=(await db.query(`SELECT s.id,s.cashier_id AS "cashierId",u.full_name AS cashier,s.facility_id AS "facilityId",s.opening_paisa::float8 AS opening,s.opened_at AS "openedAt",s.closed_at AS "closedAt",s.counted_paisa::float8 AS counted,s.expected_paisa::float8 AS expected,s.variance_reason AS reason,(s.opening_paisa+coalesce((SELECT sum(p.amount_paisa) FROM app.payment p WHERE p.session_id=s.id AND p.method='cash'),0)-coalesce((SELECT sum(r.amount_paisa) FROM app.refund r JOIN app.payment p ON p.id=r.payment_id WHERE r.session_id=s.id AND p.method='cash' AND r.approved_at IS NOT NULL),0))::float8 AS "currentExpected" FROM app.cashier_session s JOIN app.user_account u ON u.id=s.cashier_id WHERE s.facility_id=ANY($1::uuid[]) ORDER BY s.opened_at DESC LIMIT 100`,[user.facilityIds])).rows;
 const refunds=(await db.query('SELECT r.id,r.payment_id AS "paymentId",r.amount_paisa::float8 AS amount,r.reason,r.requested_by AS "requestedBy",r.approved_at AS "approvedAt" FROM app.refund r JOIN app.payment p ON p.id=r.payment_id JOIN app.invoice i ON i.id=p.invoice_id WHERE i.facility_id=ANY($1::uuid[]) ORDER BY r.requested_at DESC LIMIT 100',[user.facilityIds])).rows;
 result={...result,services,encounters,invoices,payments,sessions,refunds};
 }else if(resource==='surgery'){
 const encounters=(await db.query(`SELECT e.id,p.mrn,p.given_name||' '||p.family_name AS patient,e.facility_id AS "facilityId" FROM app.encounter e JOIN app.patient p ON p.id=e.patient_id JOIN app.doctor_event d ON d.encounter_id=e.id AND d.status='signed' WHERE e.facility_id=ANY($1::uuid[]) ORDER BY e.checked_in_at DESC LIMIT 200`,[user.facilityIds])).rows;
 const cases=(await db.query(`SELECT c.id,c.version,c.eye,c.procedure,c.stage,c.estimate_paisa::float8 AS estimate,c.scheduled_at AS scheduled,c.facility_id AS "facilityId",p.mrn,p.given_name||' '||p.family_name AS patient,(SELECT coalesce(jsonb_agg(jsonb_build_object('stage',t.stage,'eye',t.eye,'notes',t.notes,'at',t.at,'actor',u.full_name) ORDER BY t.at),'[]') FROM app.surgery_transition t JOIN app.user_account u ON u.id=t.actor_id WHERE t.case_id=c.id) AS history,(SELECT coalesce(jsonb_agg(jsonb_build_object('id',d.id,'filename',d.filename,'eye',d.eye,'witness',d.witness,'at',d.at)),'[]') FROM app.consent_document d WHERE d.case_id=c.id) AS documents FROM app.surgery_case c JOIN app.encounter e ON e.id=c.encounter_id JOIN app.patient p ON p.id=e.patient_id WHERE c.facility_id=ANY($1::uuid[]) ORDER BY c.created_at DESC LIMIT 200`,[user.facilityIds])).rows;
 result={...result,encounters,cases};
 }else result={...result,...await dashboard(db,user)};
 await log(db,user,context,'operations.'+resource+'_read');return result;});}
const inventorySchema=z.discriminatedUnion('action',[
 z.object({action:z.literal('drug'),name:text(150).min(1),strength:text(80).min(1),therapyGroup:text(100).min(1)}).strict(),
 z.object({action:z.literal('receipt'),requestId:uuid,facilityId:uuid,drugId:uuid,batch:text(100).min(1),expiry:z.iso.date(),unitCost:money,quantity,reason}).strict(),
 z.object({action:z.literal('adjust'),requestId:uuid,batchId:uuid,quantity:z.number().int().min(-10000).max(10000).refine(v=>v!==0),reason}).strict(),
 z.object({action:z.literal('quarantine'),batchId:uuid,quarantined:z.boolean(),reason}).strict(),
 z.object({action:z.literal('threshold'),facilityId:uuid,drugId:uuid,minimum:z.number().int().min(0).max(100000)}).strict(),
 z.object({action:z.literal('transfer'),requestId:uuid,batchId:uuid,facilityId:uuid,quantity,reason}).strict()
]);
export async function inventoryAction(user:AuthUser,input:unknown,context:AuditContext){requireAction(user,'inventory:write');const d=parseInput(inventorySchema,input);return withTenant(user.tenantId,user.id,async db=>{await lock(db,user);if('requestId' in d&&(await db.query('SELECT 1 FROM app.stock_movement WHERE request_id=$1',[d.requestId])).rowCount)return {ok:true};
 if(d.action==='drug'){const id=(await db.query('INSERT INTO app.formulary(tenant_id,name,strength,therapy_group) VALUES($1,$2,$3,$4) RETURNING id',[user.tenantId,d.name,d.strength,d.therapyGroup])).rows[0].id;await log(db,user,context,'formulary.created',id);return {id};}
 if(d.action==='threshold'){await facility(db,user,d.facilityId);await db.query('INSERT INTO app.stock_threshold(tenant_id,facility_id,drug_id,minimum) VALUES($1,$2,$3,$4) ON CONFLICT(tenant_id,facility_id,drug_id) DO UPDATE SET minimum=EXCLUDED.minimum',[user.tenantId,d.facilityId,d.drugId,d.minimum]);}
 else if(d.action==='receipt'){await facility(db,user,d.facilityId);if(d.expiry<todayKarachi())throw new ApiError(400,'expiredBatch');if(!(await db.query('SELECT 1 FROM app.formulary WHERE id=$1 AND active',[d.drugId])).rowCount)throw new ApiError(400,'drugUnavailable');let b=(await db.query('SELECT * FROM app.stock_batch WHERE facility_id=$1 AND drug_id=$2 AND batch_number=$3',[d.facilityId,d.drugId,d.batch])).rows[0];if(b&&(b.expiry!==d.expiry||Number(b.unit_cost_paisa)!==d.unitCost))throw new ApiError(409,'batchDetailsConflict');if(!b)b=(await db.query('INSERT INTO app.stock_batch(tenant_id,facility_id,drug_id,batch_number,expiry,unit_cost_paisa) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[user.tenantId,d.facilityId,d.drugId,d.batch,d.expiry,d.unitCost])).rows[0];await db.query("INSERT INTO app.stock_movement(tenant_id,batch_id,quantity,kind,reason,actor_id,request_id) VALUES($1,$2,$3,'receipt',$4,$5,$6)",[user.tenantId,b.id,d.quantity,d.reason,user.id,d.requestId]);}
 else {const b=(await db.query(`SELECT b.*,${balance} AS quantity FROM app.stock_batch b WHERE b.id=$1`,[d.batchId])).rows[0];if(!b)throw new ApiError(404,'batchNotFound');await facility(db,user,b.facility_id);
 if(d.action==='quarantine')await db.query('UPDATE app.stock_batch SET quarantined=$2 WHERE id=$1',[b.id,d.quarantined]);
 else if(d.action==='adjust'){if(b.quantity+d.quantity<0)throw new ApiError(409,'insufficientStock');await db.query("INSERT INTO app.stock_movement(tenant_id,batch_id,quantity,kind,reason,actor_id,request_id) VALUES($1,$2,$3,'adjustment',$4,$5,$6)",[user.tenantId,b.id,d.quantity,d.reason,user.id,d.requestId]);}
 else {await facility(db,user,d.facilityId);if(b.facility_id===d.facilityId||b.quarantined||b.expiry<todayKarachi()||b.quantity<d.quantity)throw new ApiError(409,'insufficientStock');let target=(await db.query('SELECT * FROM app.stock_batch WHERE facility_id=$1 AND drug_id=$2 AND batch_number=$3',[d.facilityId,b.drug_id,b.batch_number])).rows[0];if(target&&(target.expiry!==b.expiry||Number(target.unit_cost_paisa)!==Number(b.unit_cost_paisa)||target.quarantined))throw new ApiError(409,'batchDetailsConflict');if(!target)target=(await db.query('INSERT INTO app.stock_batch(tenant_id,facility_id,drug_id,batch_number,expiry,unit_cost_paisa) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[user.tenantId,d.facilityId,b.drug_id,b.batch_number,b.expiry,b.unit_cost_paisa])).rows[0];for(const [id,qty] of [[b.id,-d.quantity],[target.id,d.quantity]])await db.query("INSERT INTO app.stock_movement(tenant_id,batch_id,quantity,kind,reason,actor_id,request_id) VALUES($1,$2,$3,'transfer',$4,$5,$6)",[user.tenantId,id,qty,d.reason,user.id,d.requestId]);}}
 await log(db,user,context,'inventory.'+d.action,undefined,{action:d.action});return {ok:true};});}
export async function dispensingAction(user:AuthUser,input:unknown,context:AuditContext){requireAction(user,'pharmacy:dispense');const d=parseInput(z.discriminatedUnion('action',[z.object({action:z.literal('dispense'),requestId:uuid,itemId:uuid,facilityId:uuid,quantity,batchId:uuid.optional(),reason:text().default('')}).strict(),z.object({action:z.literal('close'),prescriptionId:uuid,reason}).strict()]),input);return withTenant(user.tenantId,user.id,async db=>{await lock(db,user);
 if(d.action==='close'){const rx=(await db.query("SELECT id FROM app.prescription WHERE id=$1 AND status='signed'",[d.prescriptionId])).rows[0];if(!rx)throw new ApiError(404,'clinicalNotFound');await db.query('INSERT INTO app.prescription_closure(tenant_id,prescription_id,actor_id,reason) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[user.tenantId,rx.id,user.id,d.reason]);await log(db,user,context,'prescription.closed',rx.id,{reason:d.reason});return {ok:true};}
 await facility(db,user,d.facilityId);if((await db.query('SELECT 1 FROM app.stock_movement WHERE request_id=$1',[d.requestId])).rowCount)return {ok:true};
 const item=(await db.query("SELECT i.*,r.author_id FROM app.prescription_item i JOIN app.prescription r ON r.id=i.prescription_id WHERE i.id=$1 AND r.status='signed' AND NOT EXISTS(SELECT 1 FROM app.prescription_closure c WHERE c.prescription_id=r.id)",[d.itemId])).rows[0];if(!item)throw new ApiError(409,'prescriptionClosed');if(item.author_id===user.id)throw new ApiError(403,'separatePrescriberDispenser');if(!item.quantity||!item.drug_id)throw new ApiError(409,'prescriptionQuantityRequired');const issued=Number((await db.query('SELECT coalesce(sum(-m.quantity),0) AS total FROM app.dispense x JOIN app.stock_movement m ON m.id=x.movement_id WHERE x.prescription_item_id=$1',[item.id])).rows[0].total);if(issued+d.quantity>item.quantity)throw new ApiError(409,'quantityExceedsPrescription');
 let batches=(await db.query(`SELECT b.*,${balance} AS quantity FROM app.stock_batch b WHERE b.facility_id=$1 AND b.drug_id=$2 AND NOT b.quarantined AND b.expiry>=$3 ORDER BY b.expiry,b.id`,[d.facilityId,item.drug_id,todayKarachi()])).rows.filter(b=>b.quantity>0);if(d.batchId){if(batches[0]?.id!==d.batchId&&d.reason.length<8)throw new ApiError(400,'fefoReasonRequired');batches=batches.filter(b=>b.id===d.batchId);}if(batches.reduce((n,b)=>n+b.quantity,0)<d.quantity)throw new ApiError(409,'insufficientStock');let remaining=d.quantity;for(const b of batches){if(!remaining)break;const qty=Math.min(remaining,b.quantity);const movement=(await db.query("INSERT INTO app.stock_movement(tenant_id,batch_id,quantity,kind,reason,actor_id,request_id) VALUES($1,$2,$3,'dispense',$4,$5,$6) RETURNING id",[user.tenantId,b.id,-qty,d.reason||'FEFO dispensing',user.id,d.requestId])).rows[0];await db.query('INSERT INTO app.dispense(tenant_id,prescription_item_id,movement_id,actor_id) VALUES($1,$2,$3,$4)',[user.tenantId,item.id,movement.id,user.id]);remaining-=qty;}await log(db,user,context,'prescription.dispensed',item.prescription_id,{itemId:item.id,quantity:d.quantity,facilityId:d.facilityId,reason:d.reason});return {ok:true};});}

const billingSchema=z.discriminatedUnion('action',[
 z.object({action:z.literal('service'),id:uuid.optional(),version:z.number().int().nonnegative().default(0),name:text(150).min(1),category:z.enum(['consultation','procedure','investigation','optical','pharmacy']),price:money,active:z.boolean().default(true)}).strict(),
 z.object({action:z.literal('invoice'),requestId:uuid,encounterId:uuid,lines:z.array(z.object({serviceId:uuid,quantity,expectedPrice:money}).strict()).min(1).max(30),discount:money.default(0),reason:text().default('')}).strict(),
 z.object({action:z.literal('open_session'),facilityId:uuid,opening:money}).strict(),
 z.object({action:z.literal('close_session'),sessionId:uuid,counted:money,reason:text().default('')}).strict(),
 z.object({action:z.literal('payment'),requestId:uuid,invoiceId:uuid,amount:positiveMoney,method:z.enum(['cash','card','bank_transfer','welfare']),reference:text(160).default('')}).strict(),
 z.object({action:z.literal('refund'),paymentId:uuid,amount:positiveMoney,reason}).strict(),
 z.object({action:z.literal('approve_refund'),refundId:uuid}).strict()
]);
export async function billingAction(user:AuthUser,input:unknown,context:AuditContext){const d=parseInput(billingSchema,input);requireAction(user,d.action==='service'?'settings:write':d.action==='approve_refund'?'billing:approve_refund':d.action==='invoice'&&user.permissions.includes('billing:discount')?'billing:discount':'billing:write');return withTenant(user.tenantId,user.id,async db=>{await lock(db,user);
 if(d.action==='service'){if(d.id){if(!(await db.query('UPDATE app.service_catalogue SET name=$2,category=$3,price_paisa=$4,active=$5,version=version+1 WHERE id=$1 AND version=$6',[d.id,d.name,d.category,d.price,d.active,d.version])).rowCount)throw new ApiError(409,'recordChanged');}else await db.query('INSERT INTO app.service_catalogue(tenant_id,name,category,price_paisa,active) VALUES($1,$2,$3,$4,$5)',[user.tenantId,d.name,d.category,d.price,d.active]);}
 else if(d.action==='invoice'){if((await db.query('SELECT id FROM app.invoice WHERE request_id=$1',[d.requestId])).rowCount)return {ok:true};const e=(await db.query('SELECT facility_id FROM app.encounter WHERE id=$1',[d.encounterId])).rows[0];if(!e)throw new ApiError(404,'encounterNotFound');await facility(db,user,e.facility_id);const lines=[];let total=0;for(const line of d.lines){const service=(await db.query('SELECT * FROM app.service_catalogue WHERE id=$1 AND active',[line.serviceId])).rows[0];if(!service||Number(service.price_paisa)!==line.expectedPrice)throw new ApiError(409,'servicePriceChanged');total+=Number(service.price_paisa)*line.quantity;lines.push({...line,service});}if(!Number.isSafeInteger(total)||total>10000000000)throw new ApiError(400,'invalidAmount');if(d.discount){requireAction(user,'billing:discount');if(d.reason.length<8||d.discount>total)throw new ApiError(400,'discountReasonRequired');}const invoice=(await db.query('INSERT INTO app.invoice(tenant_id,encounter_id,facility_id,total_paisa,discount_paisa,discount_reason,created_by,request_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id',[user.tenantId,d.encounterId,e.facility_id,total-d.discount,d.discount,d.reason,user.id,d.requestId])).rows[0];for(const [position,l] of lines.entries())await db.query('INSERT INTO app.invoice_line(tenant_id,invoice_id,position,service_id,description,quantity,unit_price_paisa) VALUES($1,$2,$3,$4,$5,$6,$7)',[user.tenantId,invoice.id,position,l.serviceId,l.service.name,l.quantity,l.service.price_paisa]);await log(db,user,context,'invoice.issued',invoice.id,{total:total-d.discount,discount:d.discount,reason:d.reason});return {id:invoice.id};}
 else if(d.action==='open_session'){await facility(db,user,d.facilityId);if((await db.query('SELECT 1 FROM app.cashier_session WHERE cashier_id=$1 AND closed_at IS NULL',[user.id])).rowCount)throw new ApiError(409,'cashierSessionAlreadyOpen');await db.query('INSERT INTO app.cashier_session(tenant_id,facility_id,cashier_id,opening_paisa) VALUES($1,$2,$3,$4)',[user.tenantId,d.facilityId,user.id,d.opening]);}
 else if(d.action==='close_session'){const session=(await db.query('SELECT * FROM app.cashier_session WHERE id=$1 AND cashier_id=$2 AND closed_at IS NULL FOR UPDATE',[d.sessionId,user.id])).rows[0];if(!session)throw new ApiError(409,'cashierSessionRequired');await facility(db,user,session.facility_id);const expected=Number(session.opening_paisa)+Number((await db.query("SELECT coalesce(sum(amount_paisa),0) AS total FROM app.payment WHERE session_id=$1 AND method='cash'",[session.id])).rows[0].total)-Number((await db.query("SELECT coalesce(sum(r.amount_paisa),0) AS total FROM app.refund r JOIN app.payment p ON p.id=r.payment_id WHERE r.session_id=$1 AND r.approved_at IS NOT NULL AND p.method='cash'",[session.id])).rows[0].total);if(expected!==d.counted&&d.reason.length<8)throw new ApiError(400,'varianceReasonRequired');await db.query('UPDATE app.cashier_session SET closed_at=now(),counted_paisa=$2,expected_paisa=$3,variance_reason=$4 WHERE id=$1',[session.id,d.counted,expected,d.reason]);await log(db,user,context,'cashier.closed',session.id,{expected,counted:d.counted,variance:d.counted-expected,reason:d.reason});return {expected,counted:d.counted,variance:d.counted-expected};}
 else if(d.action==='payment'){const prior=(await db.query('SELECT id,receipt_number AS receipt FROM app.payment WHERE request_id=$1',[d.requestId])).rows[0];if(prior)return prior;const invoice=(await db.query('SELECT * FROM app.invoice WHERE id=$1',[d.invoiceId])).rows[0];if(!invoice)throw new ApiError(404,'invoiceNotFound');await facility(db,user,invoice.facility_id);const session=(await db.query('SELECT id FROM app.cashier_session WHERE cashier_id=$1 AND facility_id=$2 AND closed_at IS NULL FOR UPDATE',[user.id,invoice.facility_id])).rows[0];if(!session)throw new ApiError(409,'cashierSessionRequired');const paid=Number((await db.query('SELECT coalesce(sum(amount_paisa),0) AS total FROM app.payment WHERE invoice_id=$1',[invoice.id])).rows[0].total),refunded=Number((await db.query('SELECT coalesce(sum(r.amount_paisa),0) AS total FROM app.refund r JOIN app.payment p ON p.id=r.payment_id WHERE p.invoice_id=$1 AND r.approved_at IS NOT NULL',[invoice.id])).rows[0].total);if(d.amount>Number(invoice.total_paisa)-paid+refunded)throw new ApiError(409,'overpayment');if(d.method!=='cash'&&!d.reference)throw new ApiError(400,'paymentReferenceRequired');const date=todayKarachi();const seq=(await db.query('INSERT INTO app.receipt_counter(tenant_id,facility_id,date,sequence) VALUES($1,$2,$3,1) ON CONFLICT(tenant_id,facility_id,date) DO UPDATE SET sequence=app.receipt_counter.sequence+1 RETURNING sequence',[user.tenantId,invoice.facility_id,date])).rows[0].sequence;const receipt=invoice.facility_id.replaceAll('-','')+'-'+date.replaceAll('-','')+'-'+String(seq).padStart(5,'0');const result=(await db.query('INSERT INTO app.payment(tenant_id,invoice_id,session_id,amount_paisa,method,reference,receipt_number,actor_id,request_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[user.tenantId,invoice.id,session.id,d.amount,d.method,d.reference,receipt,user.id,d.requestId])).rows[0];await log(db,user,context,'payment.recorded',result.id,{amount:d.amount,method:d.method});return {...result,receipt};}
 else if(d.action==='refund'){const pay=(await db.query('SELECT p.*,i.facility_id FROM app.payment p JOIN app.invoice i ON i.id=p.invoice_id WHERE p.id=$1',[d.paymentId])).rows[0];if(!pay)throw new ApiError(404,'paymentNotFound');await facility(db,user,pay.facility_id);const reserved=Number((await db.query('SELECT coalesce(sum(amount_paisa),0) AS total FROM app.refund WHERE payment_id=$1',[pay.id])).rows[0].total);if(reserved+d.amount>Number(pay.amount_paisa))throw new ApiError(409,'refundExceedsPayment');await db.query('INSERT INTO app.refund(tenant_id,payment_id,amount_paisa,reason,requested_by) VALUES($1,$2,$3,$4,$5)',[user.tenantId,pay.id,d.amount,d.reason,user.id]);}
 else {const r=(await db.query('SELECT r.*,p.method,i.facility_id FROM app.refund r JOIN app.payment p ON p.id=r.payment_id JOIN app.invoice i ON i.id=p.invoice_id WHERE r.id=$1 FOR UPDATE OF r',[d.refundId])).rows[0];if(!r||r.approved_at)throw new ApiError(409,'recordChanged');if(r.requested_by===user.id)throw new ApiError(403,'secondApproverRequired');await facility(db,user,r.facility_id);const session=(await db.query('SELECT id FROM app.cashier_session WHERE cashier_id=$1 AND facility_id=$2 AND closed_at IS NULL FOR UPDATE',[r.requested_by,r.facility_id])).rows[0];if(!session)throw new ApiError(409,'requesterCashierSessionRequired');await db.query('UPDATE app.refund SET approved_by=$2,approved_at=now(),session_id=$3 WHERE id=$1',[r.id,user.id,session.id]);}
 await log(db,user,context,'billing.'+d.action);return {ok:true};});}
export const SURGERY_STAGES=['estimate','consent','preop','scheduled','operated','discharged','followup'] as const;
export async function surgeryAction(user:AuthUser,input:unknown,context:AuditContext){requireAction(user,'surgery:write');const d=parseInput(z.discriminatedUnion('action',[z.object({action:z.literal('create'),encounterId:uuid,facilityId:uuid,eye:z.enum(['OD','OS']),procedure:text(200).min(1),estimate:money}).strict(),z.object({action:z.literal('advance'),id:uuid,version:z.number().int().positive(),stage:z.enum([...SURGERY_STAGES,'cancelled']),eye:z.enum(['OD','OS']),notes:reason,scheduled:z.iso.datetime({offset:true}).optional()}).strict()]),input);return withTenant(user.tenantId,user.id,async db=>{await lock(db,user);if(d.action==='create'){await facility(db,user,d.facilityId);if(!(await db.query("SELECT 1 FROM app.facility WHERE id=$1 AND type='theatre'",[d.facilityId])).rowCount)throw new ApiError(400,'theatreRequired');if(!(await db.query("SELECT 1 FROM app.encounter e JOIN app.doctor_event v ON v.encounter_id=e.id WHERE e.id=$1 AND e.facility_id=ANY($2::uuid[]) AND v.status='signed'",[d.encounterId,user.facilityIds])).rowCount)throw new ApiError(400,'signedEventRequired');const c=(await db.query('INSERT INTO app.surgery_case(tenant_id,encounter_id,facility_id,eye,procedure,estimate_paisa,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[user.tenantId,d.encounterId,d.facilityId,d.eye,d.procedure,d.estimate,user.id])).rows[0];await db.query("INSERT INTO app.surgery_transition(tenant_id,case_id,stage,eye,notes,actor_id) VALUES($1,$2,'estimate',$3,'Case created',$4)",[user.tenantId,c.id,d.eye,user.id]);await log(db,user,context,'surgery.created',c.id);return c;}
 const c=(await db.query('SELECT * FROM app.surgery_case WHERE id=$1 FOR UPDATE',[d.id])).rows[0];if(!c)throw new ApiError(404,'caseNotFound');await facility(db,user,c.facility_id);if(c.version!==d.version)throw new ApiError(409,'recordChanged');if(c.eye!==d.eye)throw new ApiError(409,'lateralityMismatch');if(d.stage==='cancelled'){if(['operated','discharged','followup','cancelled'].includes(c.stage))throw new ApiError(409,'stageConflict');}else if(SURGERY_STAGES[SURGERY_STAGES.indexOf(c.stage)+1]!==d.stage)throw new ApiError(409,'stageConflict');
 if(['consent','scheduled'].includes(d.stage)&&!(await db.query('SELECT 1 FROM app.consent_document WHERE case_id=$1 AND eye=$2',[c.id,c.eye])).rowCount)throw new ApiError(409,'consentDocumentRequired');if(d.stage==='scheduled'&&(!d.scheduled||Date.parse(d.scheduled)<Date.now()))throw new ApiError(400,'futureSurgeryRequired');if(['operated','discharged','followup','preop'].includes(d.stage)&&!user.roles.includes('doctor'))throw new ApiError(403,'doctorRequired');
 await db.query('UPDATE app.surgery_case SET stage=$2,version=version+1,scheduled_at=coalesce($3,scheduled_at) WHERE id=$1',[c.id,d.stage,d.scheduled??null]);await db.query('INSERT INTO app.surgery_transition(tenant_id,case_id,stage,eye,notes,actor_id) VALUES($1,$2,$3,$4,$5,$6)',[user.tenantId,c.id,d.stage,d.eye,d.notes,user.id]);await log(db,user,context,'surgery.'+d.stage,c.id);return {ok:true};});}
async function dashboard(db:PoolClient,user:AuthUser){const date=todayKarachi();const bookings=(await db.query("SELECT count(*)::int AS total,count(*) FILTER(WHERE status='checked_in')::int AS attended,count(*) FILTER(WHERE status='cancelled')::int AS cancelled,count(*) FILTER(WHERE status='no_show')::int AS missed FROM app.appointment WHERE facility_id=ANY($1::uuid[]) AND appointment_date=$2",[user.facilityIds,date])).rows[0];
 const collections=(await db.query("SELECT (p.at AT TIME ZONE 'Asia/Karachi')::date AS date,p.method,sum(p.amount_paisa)::float8 AS amount FROM app.payment p JOIN app.invoice i ON i.id=p.invoice_id WHERE i.facility_id=ANY($1::uuid[]) AND p.at>=now()-interval '30 days' GROUP BY 1,2 ORDER BY 1",[user.facilityIds])).rows;
 const outstanding=Number((await db.query('SELECT coalesce(sum(i.total_paisa-coalesce((SELECT sum(p.amount_paisa) FROM app.payment p WHERE p.invoice_id=i.id),0)+coalesce((SELECT sum(r.amount_paisa) FROM app.refund r JOIN app.payment p ON p.id=r.payment_id WHERE p.invoice_id=i.id AND r.approved_at IS NOT NULL),0)),0)::float8 AS amount FROM app.invoice i WHERE i.facility_id=ANY($1::uuid[])',[user.facilityIds])).rows[0].amount);
 const inventory=(await db.query(`SELECT coalesce(sum((${balance})*b.unit_cost_paisa),0)::float8 AS value,count(*) FILTER(WHERE b.expiry<$2)::int AS expired FROM app.stock_batch b WHERE b.facility_id=ANY($1::uuid[])`,[user.facilityIds,date])).rows[0];
 const surgery=(await db.query('SELECT stage,count(*)::int AS count FROM app.surgery_case WHERE facility_id=ANY($1::uuid[]) GROUP BY stage',[user.facilityIds])).rows;
 const documentation=(await db.query("SELECT count(*)::int AS visits,count(*) FILTER(WHERE d.status='signed')::int AS signed FROM app.encounter e LEFT JOIN app.doctor_event d ON d.encounter_id=e.id WHERE e.facility_id=ANY($1::uuid[]) AND e.checked_in_at>=now()-interval '30 days'",[user.facilityIds])).rows[0];
 const waits=(await db.query(`SELECT stage,round(avg(minutes)::numeric,1)::float8 AS minutes FROM (SELECT q.to_stage AS stage,extract(epoch FROM (lead(q.at) OVER(PARTITION BY q.encounter_id ORDER BY q.encounter_version)-q.at))/60 AS minutes FROM app.queue_transition q JOIN app.encounter e ON e.id=q.encounter_id WHERE e.facility_id=ANY($1::uuid[]) AND e.checked_in_at>=now()-interval '30 days') w WHERE minutes IS NOT NULL GROUP BY stage`,[user.facilityIds])).rows;
 const lowStock=Number((await db.query(`SELECT count(*)::int AS count FROM app.stock_threshold t WHERE t.facility_id=ANY($1::uuid[]) AND t.minimum>coalesce((SELECT sum(m.quantity) FROM app.stock_batch b JOIN app.stock_movement m ON m.batch_id=b.id WHERE b.facility_id=t.facility_id AND b.drug_id=t.drug_id AND NOT b.quarantined AND b.expiry>=$2),0)`,[user.facilityIds,date])).rows[0].count);
 const refunds=Number((await db.query("SELECT coalesce(sum(r.amount_paisa),0)::float8 AS amount FROM app.refund r JOIN app.payment p ON p.id=r.payment_id JOIN app.invoice i ON i.id=p.invoice_id WHERE i.facility_id=ANY($1::uuid[]) AND r.approved_at>=now()-interval '30 days'",[user.facilityIds])).rows[0].amount);
 return {date,bookings,collections,outstanding,inventory,surgery,documentation,waits,lowStock,refunds,asOf:new Date().toISOString()};}
