import 'server-only';
import {z} from 'zod';
import type {AuthUser} from '@/lib/access';
import {withTenant} from './db';
import {audit,type AuditContext} from './audit';
import {parseInput,requireAction} from './administration-service';
import {ApiError} from './http';
export async function patientHistory(user:AuthUser,id:string,context:AuditContext){requireAction(user,'clinical:read');parseInput(z.uuid(),id);return withTenant(user.tenantId,user.id,async db=>{if(!(await db.query('SELECT id FROM app.patient WHERE id=$1',[id])).rowCount)throw new ApiError(404,'patientNotFound');const history=(await db.query('SELECT h.id,h.category,h.text,h.at,h.supersedes_id AS "supersedesId",u.full_name AS author FROM app.patient_history h JOIN app.user_account u ON u.id=h.author_id WHERE h.patient_id=$1 ORDER BY h.at DESC',[id])).rows;const flags=(await db.query('SELECT id,type,value,resolved_at AS "resolvedAt",resolution_reason AS reason FROM app.patient_flag WHERE patient_id=$1 ORDER BY created_at DESC',[id])).rows;await audit(db,{tenantId:user.tenantId,actorId:user.id,action:'patient.history_read',entityType:'patient',entityId:id,context});return {history,flags};});}
export async function updateHistory(user:AuthUser,id:string,input:unknown,context:AuditContext){requireAction(user,'history:write');parseInput(z.uuid(),id);const d=parseInput(z.discriminatedUnion('action',[
 z.object({action:z.literal('history'),category:z.enum(['medical','ocular','family','surgical','drug']),text:z.string().trim().min(1).max(3000),supersedesId:z.uuid().nullable().default(null)}).strict(),
 z.object({action:z.literal('flag'),type:z.enum(['allergy','risk']),value:z.string().trim().min(1).max(160)}).strict(),
 z.object({action:z.literal('resolve'),id:z.uuid(),reason:z.string().trim().min(8).max(500)}).strict()]),input);
 return withTenant(user.tenantId,user.id,async db=>{if(!(await db.query('SELECT id FROM app.patient WHERE id=$1 FOR UPDATE',[id])).rowCount)throw new ApiError(404,'patientNotFound');if(d.action==='history'){if(d.supersedesId){if(!(await db.query('SELECT 1 FROM app.patient_history WHERE id=$1 AND patient_id=$2 AND category=$3',[d.supersedesId,id,d.category])).rowCount)throw new ApiError(404,'historyNotFound');if((await db.query('SELECT 1 FROM app.patient_history WHERE supersedes_id=$1',[d.supersedesId])).rowCount)throw new ApiError(409,'recordChanged');}await db.query('INSERT INTO app.patient_history(tenant_id,patient_id,category,text,author_id,supersedes_id) VALUES($1,$2,$3,$4,$5,$6)',[user.tenantId,id,d.category,d.text,user.id,d.supersedesId]);}else if(d.action==='flag')await db.query('INSERT INTO app.patient_flag(tenant_id,patient_id,type,value,created_by) VALUES($1,$2,$3,$4,$5)',[user.tenantId,id,d.type,d.value,user.id]);else if(!(await db.query('UPDATE app.patient_flag SET resolved_at=now(),resolved_by=$3,resolution_reason=$4 WHERE id=$1 AND patient_id=$2 AND resolved_at IS NULL',[d.id,id,user.id,d.reason])).rowCount)throw new ApiError(409,'recordChanged');await audit(db,{tenantId:user.tenantId,actorId:user.id,action:'patient.'+d.action+'_saved',entityType:'patient',entityId:id,metadata:{action:d.action},context});return {ok:true};});}
