import 'server-only';
import { existsSync,readdirSync } from 'node:fs';
import { resolve,join } from 'node:path';
import { chromium } from 'playwright-core';
import QRCode from 'qrcode';
import type { RxItem } from '@/lib/clinical';
import { ApiError } from './http';
export type PrintablePrescription={id:string;signedAt:string;contentHash:string;snapshot:{hospital:string;patient:{name:string;mrn:string;dob:string;gender:string};prescriber:{name:string;licence:string};items:RxItem[]};addenda:{text:string;author:string;at:string;contentHash:string}[];verificationUrl:string};
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
const date=(value:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Karachi',dateStyle:'medium',timeStyle:'short',hour12:false}).format(new Date(value));
export async function prescriptionHtml(record:PrintablePrescription){const {snapshot}=record;const qr=await QRCode.toDataURL(record.verificationUrl,{errorCorrectionLevel:'M',margin:2,width:180});return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>OpenEyes signed prescription</title><style>
@page{size:A4;margin:18mm}*{box-sizing:border-box}body{font:12px Arial,'Nirmala UI',sans-serif;color:#173d33}header{display:flex;justify-content:space-between;border-bottom:3px solid #173d33;padding-bottom:16px}h1{font-size:27px;margin:0 0 7px}h2{font-size:17px;margin-top:24px}.demo{color:#922d43;font-weight:bold;font-size:11px}.patient{padding:15px;background:#f4f6ef;line-height:1.8;margin:18px 0}.item{border:1px solid #d8dfd1;padding:14px;margin:12px 0;break-inside:avoid;white-space:pre-wrap;overflow-wrap:anywhere}.item h3{margin:0 0 9px;font-size:14px}.eye{color:#922d43;font-weight:bold}dl{display:grid;grid-template-columns:1fr 1fr;gap:7px}dt{color:#75806b;font-size:10px}dd{margin:3px 0 0}.ur{direction:rtl;text-align:right;font-family:'Nirmala UI','Arial',sans-serif;font-size:16px;line-height:2}.signature{border-top:1px solid #cad5c3;padding-top:15px;margin-top:25px;display:flex;gap:18px;break-inside:avoid}.signature img{width:120px;height:120px}.signature p{margin:5px 0;line-height:1.6}.hash{font-size:9px;overflow-wrap:anywhere;color:#6d7b63}.addendum{padding:12px;border-left:3px solid #922d43;background:#faf6f5;margin:12px 0;white-space:pre-wrap;overflow-wrap:anywhere;break-inside:avoid}a{color:#173d33}footer{font-size:10px;color:#6d7b63;border-top:1px solid #dce3d5;padding-top:10px;margin-top:20px}</style></head><body>
<header><div><h1>${escape(snapshot.hospital)}</h1>OpenEyes · Ophthalmology prescription</div><div class="demo">DEMONSTRATION ONLY<br>Powered by Logic box</div></header>
<div class="patient"><strong>${escape(snapshot.patient.name)}</strong><br>MRN ${escape(snapshot.patient.mrn)} · DOB ${escape(snapshot.patient.dob)} · ${escape(snapshot.patient.gender)}<br>Signed ${escape(date(record.signedAt))} PKT</div>
<h2>Signed prescription items</h2>${snapshot.items.map((item,index)=>`<section class="item"><h3>${index+1}. ${escape(item.name)} · ${escape(item.strength)}${item.quantity ? ` - Quantity ${escape(item.quantity)} packs/units` : ""} <span class="eye">${escape(item.eye)}</span></h3><dl><div><dt>Dose</dt><dd>${escape(item.dose)}</dd></div><div><dt>Route</dt><dd>${escape(item.route)}</dd></div><div><dt>Frequency</dt><dd>${escape(item.frequency)}</dd></div><div><dt>Duration</dt><dd>${escape(item.duration)}</dd></div></dl><p>${escape(item.instructions)}</p>${item.instructionsUr?`<p class="ur" lang="ur">${escape(item.instructionsUr)}</p>`:''}${!item.drugId?'<small>Non-formulary item</small>':''}</section>`).join('')}
<section class="signature"><img src="${qr}" alt="Signature verification QR"><div><p><strong>${escape(snapshot.prescriber.name)}</strong><br>Licence: ${escape(snapshot.prescriber.licence)}</p><p>Electronically signed following credential verification.<br>The QR confirms signature status without patient or medication details.</p><a href="${escape(record.verificationUrl)}">Verify signature status</a><p class="hash">Original SHA-256: ${escape(record.contentHash)}</p></div></section>
${record.addenda.length?`<h2>Prescription addenda (${record.addenda.length})</h2><p>The signed items above remain unchanged. Read these dated additions alongside the original.</p>${record.addenda.map(item=>`<section class="addendum"><strong>${escape(item.author)} · ${escape(date(item.at))} PKT</strong><p>${escape(item.text)}</p><small class="hash">Addendum hash: ${escape(item.contentHash)}</small></section>`).join('')}`:''}<footer>Prescription ${escape(record.id)} · This demo does not dispense medication. This PDF includes addenda available when generated.</footer></body></html>`;}
let generating=false;
export async function prescriptionPdf(record:PrintablePrescription){
 if(generating)throw new ApiError(429,'pdfBusy');generating=true;
 try{let executablePath=process.env.PDF_CHROMIUM_EXECUTABLE;
 if(!executablePath&&existsSync(resolve('.playwright'))){const folder=readdirSync(resolve('.playwright')).find(name=>name.startsWith('chromium_headless_shell-'));if(folder){const local=join(resolve('.playwright'),folder,'chrome-headless-shell-win64','chrome-headless-shell.exe');if(existsSync(local))executablePath=local;}}
 const browser=await chromium.launch({headless:true,executablePath,timeout:15000});
 const deadline=setTimeout(()=>void browser.close(),30000);
 try{const context=await browser.newContext({javaScriptEnabled:false,serviceWorkers:'block'});await context.route('**/*',route=>route.abort());const page=await context.newPage();await page.setContent(await prescriptionHtml(record),{waitUntil:'load',timeout:15000});return await page.pdf({format:'A4',printBackground:true,preferCSSPageSize:true});}finally{clearTimeout(deadline);await browser.close();}
 }finally{generating=false;}
}
