import 'server-only';
import {z} from 'zod';
import type {AuthUser,Permission} from '@/lib/access';
import {withTenant} from './db';
import {audit,type AuditContext} from './audit';
import {ApiError} from './http';
import {requireAction} from './administration-service';
export const REPORTS={clinic:{title:'Daily clinic register',permission:'intake:read'},events:{title:'Doctor event list',permission:'clinical:read'},staff:{title:'Staff directory',permission:'admin:read'},cashier:{title:'Cashier reconciliation',permission:'preview:billing'},dispensing:{title:'Dispensing log',permission:'preview:inventory'},expiry:{title:'Stock expiry report',permission:'preview:inventory'}} as const;
export async function report(user:AuthUser,kind:string,date:string,context:AuditContext){requireAction(user,'reports:read');if(!(kind in REPORTS)||!z.iso.date().safeParse(date).success)throw new ApiError(400,'invalidRequest');const config=REPORTS[kind as keyof typeof REPORTS];requireAction(user,config.permission as Permission);return withTenant(user.tenantId,user.id,async db=>{let rows:Record<string,unknown>[]=[];
 if(kind==='clinic')rows=(await db.query(`SELECT a.appointment_date AS date,to_char(a.slot_time,'HH24:MI') AS time,p.mrn,p.given_name||' '||p.family_name AS patient,f.name AS clinic,u.full_name AS doctor,a.status FROM app.appointment a JOIN app.patient p ON p.id=a.patient_id JOIN app.facility f ON f.id=a.facility_id JOIN app.user_account u ON u.id=a.doctor_id WHERE a.facility_id=ANY($1::uuid[]) AND a.appointment_date=$2 ORDER BY a.slot_time`,[user.facilityIds,date])).rows;
 if(kind==='events')rows=(await db.query(`SELECT p.mrn,p.given_name||' '||p.family_name AS patient,f.name AS clinic,u.full_name AS doctor,d.status,d.signed_at AS signed FROM app.doctor_event d JOIN app.encounter e ON e.id=d.encounter_id JOIN app.patient p ON p.id=e.patient_id JOIN app.facility f ON f.id=e.facility_id JOIN app.user_account u ON u.id=d.author_id WHERE e.facility_id=ANY($1::uuid[]) AND (e.checked_in_at AT TIME ZONE 'Asia/Karachi')::date=$2 ORDER BY e.checked_in_at`,[user.facilityIds,date])).rows;
 if(kind==='staff')rows=(await db.query(`SELECT u.full_name AS name,u.designation,u.email,u.licence_number AS licence,u.status,(SELECT string_agg(role_code,', ' ORDER BY role_code) FROM app.user_role r WHERE r.user_id=u.id) AS roles FROM app.user_account u ORDER BY u.full_name`)).rows;
 if(kind==='cashier')rows=(await db.query(`SELECT u.full_name AS cashier,f.name AS facility,s.opened_at,s.closed_at,s.opening_paisa/100.0 AS opening_pkr,s.expected_paisa/100.0 AS expected_pkr,s.counted_paisa/100.0 AS counted_pkr,(s.counted_paisa-s.expected_paisa)/100.0 AS variance_pkr,s.variance_reason FROM app.cashier_session s JOIN app.user_account u ON u.id=s.cashier_id JOIN app.facility f ON f.id=s.facility_id WHERE s.facility_id=ANY($1::uuid[]) AND (s.opened_at AT TIME ZONE 'Asia/Karachi')::date=$2 ORDER BY s.opened_at`,[user.facilityIds,date])).rows;
 if(kind==='dispensing')rows=(await db.query(`SELECT x.at,p.mrn,p.given_name||' '||p.family_name AS patient,i.name AS medicine,i.eye,b.batch_number,b.expiry,-m.quantity AS quantity,u.full_name AS dispenser FROM app.dispense x JOIN app.stock_movement m ON m.id=x.movement_id JOIN app.stock_batch b ON b.id=m.batch_id JOIN app.prescription_item i ON i.id=x.prescription_item_id JOIN app.prescription rx ON rx.id=i.prescription_id JOIN app.doctor_event d ON d.id=rx.event_id JOIN app.encounter e ON e.id=d.encounter_id JOIN app.patient p ON p.id=e.patient_id JOIN app.user_account u ON u.id=x.actor_id WHERE b.facility_id=ANY($1::uuid[]) AND (x.at AT TIME ZONE 'Asia/Karachi')::date=$2 ORDER BY x.at`,[user.facilityIds,date])).rows;
 if(kind==='expiry')rows=(await db.query(`SELECT f.name AS facility,d.name AS medicine,d.strength,b.batch_number,b.expiry,b.quarantined,coalesce(sum(m.quantity),0)::int AS quantity FROM app.stock_batch b JOIN app.facility f ON f.id=b.facility_id JOIN app.formulary d ON d.id=b.drug_id LEFT JOIN app.stock_movement m ON m.batch_id=b.id WHERE b.facility_id=ANY($1::uuid[]) AND b.expiry<=$2::date+90 GROUP BY f.name,d.name,d.strength,b.id HAVING coalesce(sum(m.quantity),0)>0 ORDER BY b.expiry`,[user.facilityIds,date])).rows;
 await audit(db,{tenantId:user.tenantId,actorId:user.id,action:'report.exported',entityType:'report',metadata:{report:kind,date,rowCount:rows.length},context});return {title:config.title,date,rows};});}
export function csvRows(rows:Record<string,unknown>[]){const columns=Object.keys(rows[0]||{});const cell=(value:unknown)=>{let s=value instanceof Date?value.toISOString():String(value??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};return [columns.map(cell).join(','),...rows.map(row=>columns.map(c=>cell(row[c])).join(','))].join('\r\n');}
export async function receipt(user:AuthUser,id:string,context:AuditContext){requireAction(user,'preview:billing');if(!z.uuid().safeParse(id).success)throw new ApiError(404,'notFound');return withTenant(user.tenantId,user.id,async db=>{const row=(await db.query(`SELECT pay.id,pay.receipt_number AS receipt,pay.amount_paisa::float8 AS amount,pay.method,pay.reference,pay.at,p.mrn,p.given_name||' '||p.family_name AS patient,i.id AS invoice,i.total_paisa::float8 AS total,i.discount_paisa::float8 AS discount,u.full_name AS cashier,f.name AS facility,t.name AS hospital,t.settings FROM app.payment pay JOIN app.invoice i ON i.id=pay.invoice_id JOIN app.encounter e ON e.id=i.encounter_id JOIN app.patient p ON p.id=e.patient_id JOIN app.user_account u ON u.id=pay.actor_id JOIN app.facility f ON f.id=i.facility_id JOIN app.tenant t ON t.id=i.tenant_id WHERE pay.id=$1 AND i.facility_id=ANY($2::uuid[])`,[id,user.facilityIds])).rows[0];if(!row)throw new ApiError(404,'notFound');const lines=(await db.query('SELECT description,quantity,unit_price_paisa::float8 AS price FROM app.invoice_line WHERE invoice_id=$1 ORDER BY position',[row.invoice])).rows;await audit(db,{tenantId:user.tenantId,actorId:user.id,action:'receipt.exported',entityType:'payment',entityId:id,context});return {...row,lines};});}
