"use client";
import { useEffect,useRef,useState } from 'react';
import { ArrowRight,Clock3,FileCheck2,X } from 'lucide-react';
import { api } from '@/lib/api-client';
import type { ClinicalList,Timeline } from '@/lib/clinical';
import type { MessageKey } from '@/lib/messages';
import { useLocale } from '../locale-provider';
import { useSession } from '../session-provider';
import { ErrorNotice,intakeError,LiveStatus,RiskFlags,useLiveData } from '../intake/shared';
import { formatDate } from '../patients/patients-workspace';
import { DoctorEditor } from './doctor-editor';
export function ClinicalWorkspace(){const {t}=useLocale(),user=useSession();const live=useLiveData<ClinicalList>('/api/clinical/list');const [selected,setSelected]=useState<string|null>(null);return <div className="clinical-home"><LiveStatus {...live}/><div className="clinical-encounter-grid">{live.data?.encounters.map(item=><article className="panel clinical-encounter" key={item.id}><div><span className="patient-avatar">{item.name[0]}</span><div><h2>{item.name}</h2><small>{item.mrn}</small></div><span className="intake-status">{item.eventStatus?t(item.eventStatus==='signed'?'clinicalSigned':'clinicalDraft'):t(`stage_${item.stage}`)}</span></div><RiskFlags flags={item.flags}/><dl><div><dt>{t('clinicLabel')}</dt><dd>{item.clinic}</dd></div><div><dt>{t(item.doctorId===user.id?'clinicalMine':'clinicalOther')}</dt><dd>{item.doctor}</dd></div></dl><p><Clock3 size={13}/>{formatDate(item.checkedInAt,true)}</p><button type="button" className="primary-button" onClick={()=>setSelected(item.id)}>{t('openClinical')}<ArrowRight size={15}/></button></article>)}</div>{live.data?.encounters.length===0&&<p className="intake-empty">{t('clinicalNoEncounters')}</p>}{selected&&<DoctorEditor id={selected} onClose={()=>{setSelected(null);live.refresh();}}/>}</div>;}
export function HistoryList({patientId,currentId,onOpen,refresh=0}:{patientId:string;currentId?:string;onOpen:(id:string)=>void;refresh?:number}){const {t}=useLocale();const [data,setData]=useState<Timeline|null>(null),[error,setError]=useState<MessageKey|null>(null);useEffect(()=>{const controller=new AbortController();api<Timeline>(`/api/clinical/timeline?patientId=${patientId}`,undefined,{signal:controller.signal}).then(setData).catch(error=>{if(!controller.signal.aborted)setError(intakeError(error));});return()=>controller.abort();},[patientId,refresh]);return <section className="clinical-history"><h3><FileCheck2 size={17}/>{t('clinicalHistory')}</h3><p>{t('patient360Hint')}</p><ErrorNotice error={error}/>{data?.entries.map(item=><button className={item.id===currentId?'selected':''} type="button" key={item.id} onClick={()=>onOpen(item.id)}><strong>{formatDate(item.date)}</strong><span>{item.clinic}</span><small>{item.author}</small><span className={`history-status ${item.status??''}`}>{item.id===currentId?t('currentEncounter'):item.status?t(item.status==='signed'?'clinicalSigned':'clinicalDraft'):t('workup')}</span>{item.synthetic&&<small>{t('importedHistory')}</small>}{item.addendumCount>0&&<small>{item.addendumCount} {t('addendaLabel')}</small>}</button>)}{data?.entries.length===0&&<p>{t('historyEmpty')}</p>}</section>;}
export function PatientTimelineDialog({patientId,onClose}:{patientId:string;onClose:()=>void}){const {t}=useLocale(),ref=useRef<HTMLDialogElement>(null),[selected,setSelected]=useState<string|null>(null);useEffect(()=>{ref.current?.showModal();},[]);return <><dialog ref={ref} className="intake-dialog history-dialog" aria-label={t('patient360')} onCancel={onClose}><div className="patient-record-header"><h2>{t('patient360')}</h2><button type="button" className="icon-button" aria-label={t('closeClinical')} onClick={onClose}><X size={20}/></button></div><div className="intake-dialog-body"><HistoryList patientId={patientId} onOpen={setSelected}/></div></dialog>{selected&&<DoctorEditor id={selected} onClose={()=>setSelected(null)}/>}</>;}
