"use client";
import { useRef, useState } from "react";
import { RotateCcw, Trash2 } from "lucide-react";
import type { ClinicalDrawings } from "@/lib/clinical";

type Eye="OD"|"OS";type Stroke=ClinicalDrawings[Eye]["strokes"][number];
const COLORS=["#7f1d1d","#1d4ed8","#15803d","#111827"] as const;
function Template({kind}:{kind:ClinicalDrawings[Eye]["template"]}){if(kind==='blank')return <path d="M0 250H1000M500 0V500" stroke="#d8ddd5" strokeWidth="2" strokeDasharray="12 12"/>;if(kind==='anterior')return <g fill="none" stroke="#9aa894"><ellipse cx="500" cy="250" rx="360" ry="205" strokeWidth="8"/><circle cx="500" cy="250" r="145" strokeWidth="7"/><circle cx="500" cy="250" r="58" fill="#eef1ea" strokeWidth="6"/><path d="M150 250Q500 75 850 250Q500 425 150 250Z" strokeWidth="3"/></g>;return <g fill="none" stroke="#9aa894"><circle cx="500" cy="250" r="215" strokeWidth="8"/><circle cx="650" cy="235" r="54" fill="#eef1ea" strokeWidth="6"/><circle cx="420" cy="250" r="20" fill="#aeb9a8" strokeWidth="4"/><path d="M650 180C570 210 520 235 440 248M650 290C570 275 520 262 440 252M650 235C720 175 760 140 795 95" strokeWidth="5"/></g>}
function path(points:readonly (readonly [number,number])[]){return points.map((point,index)=>`${index?'L':'M'}${point[0]} ${point[1]}`).join(' ');}
export function ClinicalDrawingSheet({value,onChange,disabled}:{value:ClinicalDrawings;onChange:(value:ClinicalDrawings)=>void;disabled:boolean}){
 const [color,setColor]=useState<(typeof COLORS)[number]>(COLORS[0]),[width,setWidth]=useState(6),[active,setActive]=useState<{eye:Eye;stroke:Stroke}|null>(null);const activeRef=useRef<{eye:Eye;stroke:Stroke}|null>(null),svgRefs=useRef<Record<Eye,SVGSVGElement|null>>({OD:null,OS:null});
 function point(eye:Eye,event:React.PointerEvent<SVGSVGElement>):[number,number]{const box=svgRefs.current[eye]!.getBoundingClientRect();return [Math.round(Math.max(0,Math.min(1000,(event.clientX-box.left)/box.width*1000))),Math.round(Math.max(0,Math.min(1000,(event.clientY-box.top)/box.height*500)))];}
 function start(eye:Eye,event:React.PointerEvent<SVGSVGElement>){if(disabled)return;event.currentTarget.setPointerCapture(event.pointerId);const next={eye,stroke:{id:crypto.randomUUID(),color,width,points:[point(eye,event)]}};activeRef.current=next;setActive(next);}
 function move(eye:Eye,event:React.PointerEvent<SVGSVGElement>){const current=activeRef.current;if(!current||current.eye!==eye||!event.currentTarget.hasPointerCapture(event.pointerId))return;const nextPoint=point(eye,event),last=current.stroke.points.at(-1)!;if(Math.hypot(nextPoint[0]-last[0],nextPoint[1]-last[1])<4)return;const next={...current,stroke:{...current.stroke,points:[...current.stroke.points,nextPoint].slice(0,240)}};activeRef.current=next;setActive(next);}
 function finish(){const current=activeRef.current;if(!current)return;if(current.stroke.points.length>1)onChange({...value,[current.eye]:{...value[current.eye],strokes:[...value[current.eye].strokes,current.stroke].slice(-40)}});activeRef.current=null;setActive(null);}
 return <div className="clinical-drawing-sheet"><div className="drawing-tools"><strong>Clinical drawing sheet</strong><span>Draw with a finger, stylus, or mouse.</span><div>{COLORS.map(item=><button key={item} type="button" className="drawing-color" aria-label={`Ink ${item}`} aria-pressed={color===item} style={{background:item}} onClick={()=>setColor(item)} disabled={disabled}/>)}<label>Width <input type="range" min="2" max="16" value={width} onChange={event=>setWidth(Number(event.target.value))} disabled={disabled}/></label></div></div><div className="drawing-eye-grid">{(['OD','OS'] as const).map(eye=>{const strokes=[...value[eye].strokes,...(active?.eye===eye?[active.stroke]:[])];return <section key={eye} className="drawing-eye"><header><strong>{eye} · {eye==='OD'?'Right eye':'Left eye'}</strong><select value={value[eye].template} disabled={disabled} onChange={event=>onChange({...value,[eye]:{...value[eye],template:event.target.value as ClinicalDrawings[Eye]['template']}})}><option value="fundus">Fundus</option><option value="anterior">Anterior segment</option><option value="blank">Blank sheet</option></select><button type="button" className="icon-button" aria-label={`Undo ${eye}`} disabled={disabled||!value[eye].strokes.length} onClick={()=>onChange({...value,[eye]:{...value[eye],strokes:value[eye].strokes.slice(0,-1)}})}><RotateCcw size={15}/></button><button type="button" className="icon-button" aria-label={`Clear ${eye}`} disabled={disabled||!value[eye].strokes.length} onClick={()=>onChange({...value,[eye]:{...value[eye],strokes:[]}})}><Trash2 size={15}/></button></header><svg ref={node=>{svgRefs.current[eye]=node;}} viewBox="0 0 1000 500" role="img" aria-label={`${eye} clinical drawing`} onPointerDown={event=>start(eye,event)} onPointerMove={event=>move(eye,event)} onPointerUp={finish} onPointerCancel={()=>{activeRef.current=null;setActive(null);}}><rect width="1000" height="500" fill="#fbfcfa"/><Template kind={value[eye].template}/>{strokes.map(stroke=><path key={stroke.id} d={path(stroke.points)} fill="none" stroke={stroke.color} strokeWidth={stroke.width} strokeLinecap="round" strokeLinejoin="round"/>)}</svg></section>;})}</div></div>;
}
