"use client";
import { useEffect,useRef,useState } from 'react';
import { FileCheck2,X } from 'lucide-react';
import { api } from '@/lib/api-client';
import type { RxItem } from '@/lib/clinical';
import type { MessageKey } from '@/lib/messages';
import { useLocale } from '../locale-provider';
import { ErrorNotice,intakeError,LiveStatus,useLiveData } from '../intake/shared';
import { formatDate } from '../patients/patients-workspace';
import { PrescriptionBatchSuggestions } from "../operations/inventory";
import { useSession } from "../session-provider";
type Entry={id:string;name:string;mrn:string;prescriber:string;clinic:string;signedAt:string;addendumCount:number};
type Record=Entry & {contentHash:string;verificationUrl:string;snapshot:{patient:{name:string;mrn:string};prescriber:{name:string;licence:string};items:RxItem[]};addenda:{id:string;text:string;author:string;at:string}[]};
export function PrescriptionInbox(){const {t}=useLocale();const live=useLiveData<{prescriptions:Entry[]}>('/api/clinical/prescriptions');const [id,setId]=useState<string|null>(null);return <section className="panel"><div className="registry-heading"><div><FileCheck2 size={21}/><h2>{t('rxInboxTitle')}</h2></div></div><p className="registry-info">{t('rxInboxBoundary')}</p><LiveStatus {...live}/><div className="intake-table-wrap"><table className="patient-table"><thead><tr><th>{t('patientColumn')}</th><th>{t('signatureAuthor')}</th><th>{t('signatureAt')}</th><th>{t('addendaLabel')}</th><th>{t('recordColumn')}</th></tr></thead><tbody>{live.data?.prescriptions.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small>{item.mrn}</small></td><td>{item.prescriber}<small>{item.clinic}</small></td><td>{formatDate(item.signedAt,true)}</td><td>{item.addendumCount}</td><td><button type="button" className="secondary-button" onClick={()=>setId(item.id)}>{t('rxOpen')}</button></td></tr>)}</tbody></table></div>{live.data?.prescriptions.length===0&&<p className="intake-empty">{t('rxInboxEmpty')}</p>}{id&&<PrescriptionDialog id={id} onClose={()=>setId(null)}/>}</section>;}
function PrescriptionDialog({id,onClose}:{id:string;onClose:()=>void}){const {t}=useLocale(),user=useSession(),ref=useRef<HTMLDialogElement>(null);const [data,setData]=useState<Record|null>(null),[error,setError]=useState<MessageKey|null>(null);useEffect(()=>{ref.current?.showModal();const controller=new AbortController();api<Record>(`/api/clinical/prescription?id=${id}`,undefined,{signal:controller.signal}).then(setData).catch(error=>{if(!controller.signal.aborted)setError(intakeError(error));});return()=>controller.abort();},[id]);return <dialog ref={ref} className="intake-dialog" aria-label={t('rxOpen')} onCancel={onClose}><div className="patient-record-header"><div><p className="eyebrow">{t('clinicalSigned')}</p><h2>{data?.snapshot.patient.name??t('clinicalLoading')}</h2><p>{data?.snapshot.patient.mrn}</p></div><button className="icon-button" type="button" aria-label={t('closeClinical')} onClick={onClose}><X size={20}/></button></div><div className="intake-dialog-body"><ErrorNotice error={error}/>{data&&<><p>{t('rxOriginalNotice')}</p>{data.snapshot.items.map((item,index)=><article className="clinical-addendum" key={item.id}><strong>{index+1}. {item.name} · {item.strength} · {item.eye}</strong><p>{item.dose} · {item.route} · {item.frequency} · {item.duration}</p><p>{item.instructions}</p><p lang="ur" dir="rtl">{item.instructionsUr}</p></article>)}<p>{data.snapshot.prescriber.name} · {data.snapshot.prescriber.licence}<br/>{formatDate(data.signedAt,true)} PKT</p><p className="signature-hash">{data.contentHash}</p>{data.addenda.map(item=><article className="clinical-addendum" key={item.id}><strong>{t('addendaLabel')} · {item.author}</strong><small>{formatDate(item.at,true)}</small><p>{item.text}</p></article>)}{user.permissions.includes("preview:inventory") && <PrescriptionBatchSuggestions drugIds={data.snapshot.items.map(item=>item.drugId)}/>}<div className="clinical-save-actions"><a className="secondary-button" target="_blank" rel="noreferrer" href={data.verificationUrl}>{t('rxVerification')}</a><a className="primary-button" target="_blank" rel="noreferrer" href={`/api/clinical/pdf?id=${data.id}`}>{t('rxPdf')}</a></div></>}</div></dialog>;}
