"use client";
import { Camera, FileImage, Trash2, Upload } from "lucide-react";
import { useRef, useState } from "react";
import type { PrescriptionEvidence } from "@/lib/clinical";

export function PrescriptionEvidencePanel({prescriptionId,evidence,disabled,onChanged}:{prescriptionId:string;evidence:PrescriptionEvidence[];disabled:boolean;onChanged:()=>Promise<void>}){
 const input=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function upload(file:File){setBusy(true);setError('');try{const form=new FormData();form.set('prescriptionId',prescriptionId);form.set('file',file);const response=await fetch('/api/clinical/prescription-evidence',{method:'POST',body:form,credentials:'same-origin'});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error==='evidenceDuplicate'?'This image is already attached.':body.error==='evidenceLimit'?'Up to five evidence files can be attached.':body.error==='fileTooLarge'?'Choose a file smaller than 5 MB.':'The file could not be attached.');await onChanged();}catch(value){setError(value instanceof Error?value.message:'The file could not be attached.');}finally{setBusy(false);if(input.current)input.current.value='';}}
 async function remove(id:string){setBusy(true);setError('');try{const response=await fetch(`/api/clinical/prescription-evidence?id=${id}`,{method:'DELETE',credentials:'same-origin'});if(!response.ok)throw new Error('The evidence could not be removed.');await onChanged();}catch(value){setError(value instanceof Error?value.message:'The evidence could not be removed.');}finally{setBusy(false);}}
 return <div className="prescription-evidence"><div className="clinical-section-heading"><div><h4>Handwritten prescription evidence</h4><p>Attach a photograph or scan of the original signed prescription. The system records its cryptographic hash; it does not compare signatures automatically.</p></div>{!disabled&&<><input ref={input} hidden type="file" accept="image/jpeg,image/png,application/pdf" capture="environment" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file);}}/><button type="button" className="secondary-button" disabled={busy||evidence.length>=5} onClick={()=>input.current?.click()}><Camera size={16}/><Upload size={14}/>Take photo or upload</button></>}</div>{error&&<p className="registration-error" role="alert">{error}</p>}{evidence.length===0?<p className="intake-help">Attach at least one original before signing this prescription.</p>:<div className="evidence-list">{evidence.map(item=><article key={item.id}><FileImage size={18}/><div><a href={`/api/clinical/prescription-evidence?id=${item.id}`} target="_blank" rel="noreferrer">{item.filename}</a><small>{item.actor} · {new Date(item.capturedAt).toLocaleString()} · SHA-256 {item.hash}</small></div>{!disabled&&<button type="button" className="icon-button" aria-label={`Remove ${item.filename}`} disabled={busy} onClick={()=>void remove(item.id)}><Trash2 size={15}/></button>}</article>)}</div>}</div>;
}
