"use client";
import { useEffect,useState } from 'react';
import { Plus,Trash2 } from 'lucide-react';
import { api } from '@/lib/api-client';
import { rxInputSchema,type Drug,type PrescriptionPreset,type RxInput,type RxItem } from '@/lib/clinical';
import type { MessageKey } from '@/lib/messages';
import { useLocale } from '../locale-provider';
import { intakeError } from '../intake/shared';

type Props={
 encounterId:string;rx:RxInput;editable:boolean;busy:boolean;drugs:Drug[];
 onBusy:(busy:boolean)=>void;onError:(error:MessageKey|null)=>void;
 onUpdateItem:(id:string,patch:Partial<RxItem>)=>void;onChange:(value:RxInput)=>void;
};

export function PrescriptionComposer({encounterId,rx,editable,busy,drugs,onBusy,onError,onUpdateItem,onChange}:Props){
 const {t}=useLocale(),[presets,setPresets]=useState<PrescriptionPreset[]>([]),[presetId,setPresetId]=useState('');
 async function refresh(){const result=await api<{presets:PrescriptionPreset[]}>(`/api/clinical/prescription-presets?encounterId=${encounterId}`);setPresets(result.presets);}
 useEffect(()=>{const controller=new AbortController();setPresetId('');api<{presets:PrescriptionPreset[]}>(`/api/clinical/prescription-presets?encounterId=${encounterId}`,undefined,{signal:controller.signal}).then(result=>setPresets(result.presets)).catch(()=>setPresets([]));return()=>controller.abort();},[encounterId]);
 async function savePreset(kind:'favourite'|'specialty_set',items:RxItem[]){const parsed=rxInputSchema.safeParse({encounterId,version:0,items});if(!parsed.success){onError('clinicalInvalid');return;}const name=window.prompt(t(kind==='favourite'?'rxFavouriteName':'rxSetName'),kind==='favourite'?items[0].name:'');if(!name?.trim())return;onBusy(true);onError(null);try{await api('/api/clinical/prescription-presets',{action:'save',kind,name:name.trim(),encounterId,items:parsed.data.items});await refresh();}catch(error){onError(intakeError(error));}finally{onBusy(false);}}
 async function applyPreset(){const preset=presets.find(value=>value.id===presetId);if(!preset)return;if(rx.items.length&&!window.confirm(t('rxPresetReplace')))return;onBusy(true);onError(null);try{await api('/api/clinical/prescription-presets',{action:'use',id:preset.id,encounterId});onChange({...rx,items:preset.items.map(item=>({...item,id:crypto.randomUUID(),taperSchedule:item.taperSchedule??[]}))});}catch(error){onError(intakeError(error));}finally{onBusy(false);}}
 async function deletePreset(){const preset=presets.find(value=>value.id===presetId);if(!preset?.own||!window.confirm(t('rxPresetDeleteConfirm')))return;onBusy(true);onError(null);try{await api('/api/clinical/prescription-presets',{action:'delete',id:preset.id});setPresetId('');await refresh();}catch(error){onError(intakeError(error));}finally{onBusy(false);}}
 const selected=presets.find(value=>value.id===presetId);
 return <>
  {editable&&<div className="rx-preset-tools"><label><span>{t('rxPresets')}</span><select aria-label={t('rxPresets')} value={presetId} onChange={event=>setPresetId(event.target.value)}><option value="">{t('rxPresetChoose')}</option>{presets.some(value=>value.kind==='favourite')&&<optgroup label={t('rxFavourites')}>{presets.filter(value=>value.kind==='favourite').map(value=><option value={value.id} key={value.id}>{value.name}</option>)}</optgroup>}{presets.some(value=>value.kind==='specialty_set')&&<optgroup label={t('rxSpecialtySets')}>{presets.filter(value=>value.kind==='specialty_set').map(value=><option value={value.id} key={value.id}>{value.name} · {value.owner}</option>)}</optgroup>}</select></label><button type="button" className="secondary-button" disabled={!selected||busy} onClick={applyPreset}>{t('rxPresetApply')}</button><button type="button" className="secondary-button" disabled={!rx.items.length||busy} onClick={()=>savePreset('specialty_set',rx.items)}>{t('rxSetSave')}</button><button type="button" className="text-button" disabled={!selected?.own||busy} onClick={deletePreset}>{t('rxPresetDelete')}</button></div>}
  {rx.items.length===0&&<p className="intake-help">{t('rxEmpty')}</p>}
  {rx.items.map((item,index)=><fieldset key={item.id} className="clinical-rx-item" disabled={!editable||busy}><legend>{index+1}. {item.name||t('rxDrug')}</legend><div className="rx-item-grid"><label className="rx-wide"><span>{t('rxDrug')}</span><select aria-label={`${t('rxDrug')} ${index+1}`} value={item.drugId??''} onChange={event=>{const drug=drugs.find(value=>value.id===event.target.value);onUpdateItem(item.id,{drugId:drug?.id??null,name:drug?.name??'',strength:drug?.strength??''});}}><option value="">{t('rxFreeText')}</option>{drugs.map(drug=><option key={drug.id} value={drug.id}>{drug.name} · {drug.strength}</option>)}</select></label>{!item.drugId&&<label><span>{t('rxDrugName')}</span><input aria-label={`${t('rxDrugName')} ${index+1}`} maxLength={150} value={item.name} onChange={event=>onUpdateItem(item.id,{name:event.target.value})}/></label>}<label><span>{t('rxStrength')}</span><input aria-label={`${t('rxStrength')} ${index+1}`} maxLength={80} readOnly={!!item.drugId} value={item.strength} onChange={event=>onUpdateItem(item.id,{strength:event.target.value})}/></label><label><span>{t('rxEye')}</span><select aria-label={`${t('rxEye')} ${index+1}`} value={item.eye} onChange={event=>onUpdateItem(item.id,{eye:event.target.value as RxItem['eye']})}>{['OD','OS','OU'].map(eye=><option key={eye}>{eye}</option>)}</select></label><label>Quantity (packs/units)<input type="number" min={1} max={10000} value={item.quantity??''} onChange={event=>onUpdateItem(item.id,{quantity:event.target.value?Number(event.target.value):null})}/></label>{(['dose','route','frequency','duration'] as const).map(field=><label key={field}><span>{t(({dose:'rxDose',route:'rxRoute',frequency:'rxFrequency',duration:'rxDuration'} as const)[field])}</span><input aria-label={`${field} ${index+1}`} maxLength={field==='route'?80:100} value={item[field]} onChange={event=>onUpdateItem(item.id,{[field]:event.target.value})}/></label>)}<label className="rx-wide"><span>{t('rxInstructions')}</span><textarea aria-label={`${t('rxInstructions')} ${index+1}`} maxLength={500} value={item.instructions} onChange={event=>onUpdateItem(item.id,{instructions:event.target.value})}/></label><label className="rx-wide"><span>{t('rxInstructionsUr')}</span><textarea lang="ur" dir="rtl" aria-label={`${t('rxInstructionsUr')} ${index+1}`} maxLength={500} value={item.instructionsUr} onChange={event=>onUpdateItem(item.id,{instructionsUr:event.target.value})}/></label></div>
   <div className="rx-taper"><div className="clinical-section-heading"><div><strong>{t('rxTaperSchedule')}</strong><p className="intake-help">{t('rxTaperHelp')}</p></div>{editable&&<button type="button" className="text-button" disabled={item.taperSchedule.length>=12} onClick={()=>onUpdateItem(item.id,{taperSchedule:[...item.taperSchedule,{dose:item.dose,frequency:item.frequency,duration:'',instructions:''}]})}><Plus size={13}/>{t('rxTaperAdd')}</button>}</div>{item.taperSchedule.map((step,stepIndex)=><div className="rx-taper-row" key={stepIndex}><strong>{stepIndex+1}</strong><input aria-label={`${t('rxDose')} ${index+1}.${stepIndex+1}`} placeholder={t('rxDose')} maxLength={100} value={step.dose} onChange={event=>onUpdateItem(item.id,{taperSchedule:item.taperSchedule.map((value,i)=>i===stepIndex?{...value,dose:event.target.value}:value)})}/><input aria-label={`${t('rxFrequency')} ${index+1}.${stepIndex+1}`} placeholder={t('rxFrequency')} maxLength={100} value={step.frequency} onChange={event=>onUpdateItem(item.id,{taperSchedule:item.taperSchedule.map((value,i)=>i===stepIndex?{...value,frequency:event.target.value}:value)})}/><input aria-label={`${t('rxDuration')} ${index+1}.${stepIndex+1}`} placeholder={t('rxDuration')} maxLength={100} value={step.duration} onChange={event=>onUpdateItem(item.id,{taperSchedule:item.taperSchedule.map((value,i)=>i===stepIndex?{...value,duration:event.target.value}:value)})}/><input aria-label={`${t('rxInstructions')} ${index+1}.${stepIndex+1}`} placeholder={t('rxInstructions')} maxLength={300} value={step.instructions} onChange={event=>onUpdateItem(item.id,{taperSchedule:item.taperSchedule.map((value,i)=>i===stepIndex?{...value,instructions:event.target.value}:value)})}/>{editable&&<button type="button" className="icon-button" aria-label={`${t('remove')} ${stepIndex+1}`} onClick={()=>onUpdateItem(item.id,{taperSchedule:item.taperSchedule.filter((_,i)=>i!==stepIndex)})}><Trash2 size={13}/></button>}</div>)}</div>
   {editable&&<div className="rx-item-actions"><button type="button" className="text-button" onClick={()=>savePreset('favourite',[item])}>{t('rxFavouriteSave')}</button><button type="button" className="text-button" onClick={()=>onChange({...rx,items:rx.items.filter(value=>value.id!==item.id)})}><Trash2 size={13}/>{t('rxRemove')}</button></div>}</fieldset>)}
  {editable&&<button type="button" className="secondary-button" disabled={rx.items.length>=12||busy} onClick={()=>onChange({...rx,items:[...rx.items,{id:crypto.randomUUID(),drugId:null,name:'',strength:'',eye:'OD',dose:'',route:'',frequency:'',duration:'',instructions:'',instructionsUr:'',taperSchedule:[]}]})}><Plus size={14}/>{t('rxAdd')}</button>}
 </>;
}
