"use client";
import { useEffect,useRef,useState } from 'react';
import { LockKeyhole,X } from 'lucide-react';
import { api } from '@/lib/api-client';
import type { ClinicalDetail,Review,RxItem,DoctorEvent } from '@/lib/clinical';
import type { Workup } from '@/lib/intake';
import { formatDate } from '../patients/patients-workspace';
import type { MessageKey } from '@/lib/messages';
import { useLocale } from '../locale-provider';
import { ErrorNotice,intakeError } from '../intake/shared';
export function SignDialog({kind,id,version,onClose,onSaved}:{kind:'event'|'prescription';id:string;version:number;onClose:()=>void;onSaved:(result:ClinicalDetail)=>void}){
 const {t}=useLocale(),ref=useRef<HTMLDialogElement>(null);const [review,setReview]=useState<Review|null>(null),[password,setPassword]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState<MessageKey|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{ref.current?.showModal();api<Review>('/api/clinical/review',{kind,id,version}).then(setReview).catch(error=>setError(intakeError(error)));},[kind,id,version]);
 async function submit(event:React.FormEvent){event.preventDefault();if(!review)return;setBusy(true);setError(null);try{onSaved(await api<ClinicalDetail>('/api/clinical/sign',{kind,id,version,reviewHash:review.hash,password,warningReason:reason}));setPassword('');}catch(error){setError(intakeError(error));setPassword('');}finally{setBusy(false);}}
 return <dialog className="intake-dialog signing-dialog" ref={ref} aria-labelledby="sign-title" onCancel={event=>{event.preventDefault();if(!busy)onClose();}}><div className="patient-record-header"><div><p className="eyebrow">{t('signingReview')}</p><h2 id="sign-title">{t(kind==='event'?'reviewEvent':'reviewRx')}</h2></div><button type="button" className="icon-button" disabled={busy} aria-label={t('closeReview')} onClick={onClose}><X size={20}/></button></div><div className="intake-dialog-body"><ErrorNotice error={error}/>{review&&<><p>{t('signatureSeparate')}</p><Snapshot snapshot={review.snapshot}/><p className="signature-hash">SHA-256 {review.hash}</p><form onSubmit={submit}>{review.warnings.length>0&&<section className="rx-warning-box"><h3>{t('rxWarnings')}</h3>{review.warnings.map(warning=><p key={warning}>{t(warning as MessageKey)}</p>)}<label><span>{t('signWarningReason')}</span><textarea required minLength={8} maxLength={500} value={reason} onChange={event=>setReason(event.target.value)}/></label></section>}<label><span>{t('reauthPassword')}</span><input required type="password" maxLength={256} autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)}/></label><div className="intake-dialog-actions"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>{t('cancelClinical')}</button><button className="primary-button" disabled={busy}><LockKeyhole size={15}/>{t('signConfirmed')}</button></div></form></>}</div></dialog>;
}
// Render the clinical content being signed; opaque relationship IDs stay in the hashed snapshot.
function Snapshot({snapshot}:{snapshot:Record<string,unknown>}){
 const {t}=useLocale();const data=snapshot as unknown as {kind:string;patient:ClinicalDetail['patient'];prescriber:{name:string;licence:string};complaint?:string;findings?:DoctorEvent['findings'];diagnoses?:DoctorEvent['diagnoses'];plans?:DoctorEvent['plans'];referral?:string;followUp?:string;workup?:Workup;items?:RxItem[]};
 return <div className="signature-snapshot"><h3>{data.patient.name}</h3><p>{data.patient.mrn} · {data.patient.dob} · {data.patient.gender}</p><p>{data.prescriber.name} · {data.prescriber.licence}</p>{data.patient.flags.map((flag,index)=><p key={index}>{t(flag.type==='allergy'?'allergyLabel':'riskLabel')}: {flag.value}</p>)}{data.kind==='event'?<><h4>{t('clinicalComplaint')}</h4><p>{data.complaint}</p><div className="clinical-bilateral" dir="ltr">{(['OD','OS'] as const).map(eye=><section key={eye}><strong>{eye} · {t('clinicalFindings')}</strong><p>{data.findings?.[eye]}</p></section>)}</div><h4>{t('clinicalDiagnosis')}</h4>{data.diagnoses?.map((item,index)=><p key={index}>{item.eye} · {item.label}</p>)}<h4>{t('clinicalPlans')}</h4>{data.plans?.map(item=><p key={item.id}>{item.eye} · {t(item.anatomySite)} · {t(item.intent)}<br/>{item.notes}</p>)}<h4>{t('clinicalReferral')}</h4><p>{data.referral||'—'}</p><h4>{t('clinicalFollowUp')}</h4><p>{data.followUp||'—'}</p>{data.workup&&<><h4>{t('savedWorkup')}</h4>{(['OD','OS'] as const).map(eye=><p key={eye}><strong>{eye}</strong><br/>{t('uncorrectedVa')}: {data.workup![eye].uncorrected} · {t('pinholeVa')}: {data.workup![eye].pinhole} · {t('correctedVa')}: {data.workup![eye].corrected}<br/>{t('iopLabel')}: {data.workup![eye].iop} · {data.workup![eye].method} · {formatDate(data.workup![eye].measuredAt,true)} PKT</p>)}<p>{data.workup.notes}</p><p>{data.workup.author} · {formatDate(data.workup.savedAt,true)} · v{data.workup.version}</p></>}</>:<>{data.items?.map((item,index)=><section className="clinical-addendum" key={item.id}><strong>{index+1}. {item.name} · {item.strength} · {item.eye}</strong><dl><div><dt>{t('rxDose')}</dt><dd>{item.dose}</dd></div><div><dt>{t('rxRoute')}</dt><dd>{item.route}</dd></div><div><dt>{t('rxFrequency')}</dt><dd>{item.frequency}</dd></div><div><dt>{t('rxDuration')}</dt><dd>{item.duration}</dd></div></dl><p>{item.instructions}</p><p dir="rtl" lang="ur">{item.instructionsUr}</p>{!item.drugId&&<small>{t('rxFreeText')}</small>}</section>)}</>}</div>;
}
