import { test,expect,type APIRequestContext } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { writeFileSync } from 'node:fs';
import { contentHash } from '../../src/server/clinical-hash';
import { todayKarachi } from '../../src/lib/patients';
const roles={reception:'aisha.malik',nurse:'nadia.raza',doctor:'sara.khan',other:'hamza.ali',pharmacy:'sana.iqbal'};
async function login(request:APIRequestContext,origin:string,role:keyof typeof roles){const response=await request.post('/api/auth/login',{headers:{Origin:origin},data:{email:`${roles[role]}@demo.openeyes.local`,password:process.env.DEMO_ACCOUNT_PASSWORD}});expect(response.status()).toBe(200);}
async function post(request:APIRequestContext,origin:string,path:string,data:unknown){return request.post(path,{headers:{Origin:origin},data});}
async function prepare(request:APIRequestContext,origin:string){
 await login(request,origin,'reception');const suffix=String(Date.now()).slice(-7);const input={givenName:'Clinical',familyName:`Review${suffix}`,gender:'female',dob:'1965-01-01',dobEstimated:false,phone:`0300${suffix}`,identifierType:'cnic',identifier:`00000${suffix}0`,allergy:'Synthetic allergy requiring reconciliation',city:'Karachi'};
 const review=await(await post(request,origin,'/api/patients/duplicates',input)).json();const response=await post(request,origin,'/api/patients',{...input,duplicateReviewToken:review.reviewToken});expect(response.status()).toBe(201);const patient=(await response.json()).patient;
 const clinic=(await(await request.get('/api/intake/clinics')).json()).clinics.find((item:{name:string})=>item.name==='General Ophthalmology');const doctor=clinic.doctors.find((item:{name:string})=>item.name.includes('Sara'));const date=todayKarachi();const slots=await(await request.get(`/api/intake/slots?facilityId=${clinic.id}&doctorId=${doctor.id}&date=${date}`)).json();
 const booked=await post(request,origin,'/api/intake/appointments',{patientId:patient.id,facilityId:clinic.id,doctorId:doctor.id,date,time:slots.slots.at(-1)});expect(booked.status()).toBe(201);const arrival=await post(request,origin,'/api/intake/checkin',{appointmentId:(await booked.json()).id});expect(arrival.status()).toBe(201);const id=(await arrival.json()).id;
 await post(request,origin,'/api/intake/transition',{encounterId:id,version:1,to:'workup'});await login(request,origin,'nurse');const eye={uncorrected:'6/12',pinhole:'6/9',corrected:'6/6',iop:16,method:'NCT',measuredAt:new Date().toISOString()};expect((await post(request,origin,'/api/intake/workup',{encounterId:id,version:0,OD:eye,OS:eye,notes:'Synthetic workup'})).status()).toBe(201);expect((await post(request,origin,'/api/intake/transition',{encounterId:id,version:2,to:'consultation'})).status()).toBe(200);await login(request,origin,'doctor');return {id,patient};
}
function eventData(id:string,version=0){return {encounterId:id,version,complaint:'Synthetic blurred vision review',findings:{OD:'Synthetic right-eye finding',OS:'Synthetic left-eye finding'},diagnoses:[{eye:'OU',label:'Synthetic cataract example'}],plans:[{id:randomUUID(),eye:'OD',anatomySite:'optic_nerve',intent:'observation',notes:'Synthetic anatomy-linked plan'}],referral:'Demo referral note',followUp:'Demo follow-up note'};}
async function saveEvent(request:APIRequestContext,origin:string,id:string){const result=await post(request,origin,'/api/clinical/event',eventData(id));expect(result.status()).toBe(200);return result.json();}
async function signRecord(request:APIRequestContext,origin:string,kind:string,record:{id:string;version:number}){const response=await post(request,origin,'/api/clinical/review',{kind,id:record.id,version:record.version});expect(response.status()).toBe(200);const review=await response.json();const signed=await post(request,origin,'/api/clinical/sign',{kind,id:record.id,version:record.version,reviewHash:review.hash,password:process.env.DEMO_ACCOUNT_PASSWORD,warningReason:review.warnings.length?'Reviewed synthetic warning flags':''});expect(signed.status()).toBe(200);return signed.json();}
function rxData(id:string,drug:{id:string;name:string;strength:string},version=0){return {encounterId:id,version,items:['OD','OS'].map(eye=>({id:randomUUID(),drugId:drug.id,name:drug.name,strength:drug.strength,eye,dose:'Demo dose',route:'Demo route',frequency:'Demo frequency',duration:'Demo duration',instructions:'Synthetic instructions only',instructionsUr:'صرف نمونہ'}))};}

test('doctor UI saves anatomy-linked findings, signs both records, appends an addendum and produces a PDF',async({page,baseURL})=>{
 test.setTimeout(180000);const {id,patient}=await prepare(page.request,baseURL!);await page.goto('/');const card=page.locator('.clinical-encounter').filter({hasText:patient.mrn});await card.getByRole('button',{name:'Open Doctor Event',exact:true}).click();const editor=page.getByRole('dialog',{name:`Clinical ${patient.familyName}`,exact:true});await expect(editor).toBeVisible();
 await editor.getByLabel('Presenting complaint',{exact:true}).fill('Synthetic blurred vision');await editor.getByLabel('OD findings',{exact:true}).fill('Synthetic right-eye findings');await editor.getByLabel('OS findings',{exact:true}).fill('Synthetic left-eye findings');await editor.getByRole('button',{name:'Add diagnosis',exact:true}).click();await editor.getByLabel('Diagnosis 1',{exact:true}).fill('Synthetic cataract example');
 await editor.getByRole('button',{name:'Open anatomy selection',exact:true}).click();await editor.getByRole('button',{name:'2D diagram',exact:true}).click();await editor.getByTestId('select-OD-optic_nerve').click();await editor.getByRole('button',{name:'Attach selected sites',exact:true}).click();await expect(editor.getByTestId('clinical-plan-OD-optic_nerve')).toBeVisible();await editor.getByRole('button',{name:'Close anatomy selection',exact:true}).click();await editor.getByRole('button',{name:'Save Doctor Event',exact:true}).click();await expect(editor.getByText('Draft saved.',{exact:true})).toBeVisible();
 await editor.locator(':scope > .intake-dialog-body').evaluate(node=>node.scrollTo(0,0));await page.screenshot({path:'test-results/clinical-editor.png',fullPage:true});await editor.getByRole('button',{name:'Review & sign',exact:true}).first().click();const sign=page.getByRole('dialog',{name:'Review Doctor Event',exact:true});await expect(sign.getByText('Synthetic blurred vision',{exact:true})).toBeVisible();await sign.getByLabel('Confirm your password',{exact:true}).fill(process.env.DEMO_ACCOUNT_PASSWORD!);await sign.getByRole('button',{name:'Sign reviewed record',exact:true}).click();await expect(sign).not.toBeVisible();await expect(editor.getByLabel('Presenting complaint',{exact:true})).toBeDisabled();
 const drugs=(await(await page.request.get('/api/clinical/formulary')).json()).drugs;const drug=drugs[0];for(let index=1;index<=2;index++){await editor.getByRole('button',{name:'Add prescription item',exact:true}).click();await editor.getByLabel(`Formulary drug ${index}`,{exact:true}).selectOption(drug.id);await editor.getByLabel(`Eye ${index}`,{exact:true}).selectOption(index===1?'OD':'OS');for(const key of ['dose','route','frequency','duration'])await editor.getByLabel(`${key} ${index}`,{exact:true}).fill(`Demo ${key}`);await editor.getByLabel(`Urdu instructions ${index}`,{exact:true}).fill('صرف نمونہ');}
 await editor.getByRole('button',{name:'Save prescription draft',exact:true}).click();await expect(editor.getByText('Draft saved.',{exact:true})).toBeVisible();await editor.getByRole('button',{name:'Review & sign',exact:true}).click();const rxSign=page.getByRole('dialog',{name:'Review prescription',exact:true});await expect(rxSign.getByText('Prescription review flags',{exact:true})).toBeVisible();await rxSign.getByLabel('Warning review / override reason',{exact:true}).fill('Reviewed synthetic allergy flag for demonstration');await rxSign.getByLabel('Confirm your password',{exact:true}).fill(process.env.DEMO_ACCOUNT_PASSWORD!);await rxSign.getByRole('button',{name:'Sign reviewed record',exact:true}).click();await expect(rxSign).not.toBeVisible();
 await editor.getByRole('button',{name:'Add addendum',exact:true}).first().click();const add=page.getByRole('dialog',{name:'Append an addendum',exact:true});await add.getByLabel('Addendum text',{exact:true}).fill('Dated synthetic clarification; original findings retained.');await add.getByLabel('Confirm your password',{exact:true}).fill(process.env.DEMO_ACCOUNT_PASSWORD!);await add.getByRole('button',{name:'Authenticate & append',exact:true}).click();await expect(add).not.toBeVisible();await expect(editor.getByText('Dated synthetic clarification; original findings retained.',{exact:true})).toBeVisible();
 const detail=await(await page.request.get(`/api/clinical/detail?encounterId=${id}`)).json();expect(detail.event.plans[0].eye).toBe('OD');expect(detail.event.plans[0].anatomySite).toBe('optic_nerve');expect(detail.event.status).toBe('signed');expect(detail.prescription.status).toBe('signed');
 const pdf=await page.request.get(`/api/clinical/pdf?id=${detail.prescription.id}`);expect(pdf.status()).toBe(200);expect(pdf.headers()['content-type']).toContain('application/pdf');const bytes=await pdf.body();expect(bytes.subarray(0,4).toString()).toBe('%PDF');expect(bytes.length).toBeGreaterThan(10000);writeFileSync('test-results/clinical-prescription.pdf',bytes);
 await editor.getByRole('button',{name:'Complete consultation',exact:true}).click();await expect(editor.getByText('Consultation completed',{exact:true})).toBeVisible();await editor.getByRole('button',{name:'Close clinical record',exact:true}).click();await expect(page.locator('.clinical-encounter').filter({hasText:patient.mrn})).not.toBeVisible();
 await page.getByRole('button',{name:'Prescriptions',exact:true}).click();await expect(page.getByRole('row').filter({hasText:patient.mrn})).toBeVisible();await page.screenshot({path:'test-results/clinical-prescription-inbox.png',fullPage:true});
 await page.getByRole('row').filter({hasText:patient.mrn}).getByRole('button',{name:'Open prescription',exact:true}).click(); const signedDialog=page.getByRole('dialog'); await expect(signedDialog.getByRole('heading',{name:'Available batches for signed items'})).toBeVisible(); await expect(signedDialog.locator('.ops-rx-batches')).toBeVisible(); await signedDialog.getByRole('button',{name:'Close clinical record',exact:true}).click();
});

test('signing enforces ownership, real reauthentication, current reviewed content and immutable signed records',async({page,baseURL})=>{
 const {id}=await prepare(page.request,baseURL!);let detail=await saveEvent(page.request,baseURL!,id);const original=detail.event;
 await login(page.request,baseURL!,'other');expect((await post(page.request,baseURL!,'/api/clinical/event',eventData(id,1))).status()).toBe(403);await login(page.request,baseURL!,'doctor');
 const review=await(await post(page.request,baseURL!,'/api/clinical/review',{kind:'event',id:original.id,version:1})).json();const input={kind:'event',id:original.id,version:1,reviewHash:review.hash,password:'wrong password'};expect((await post(page.request,baseURL!,'/api/clinical/sign',input)).status()).toBe(403);
 expect((await post(page.request,baseURL!,'/api/clinical/sign',{...input,password:process.env.DEMO_ACCOUNT_PASSWORD,reviewHash:'0'.repeat(64)})).status()).toBe(409);
 detail=await signRecord(page.request,baseURL!,'event',original);expect(detail.event.contentHash).toBe(contentHash(detail.event.snapshot));expect((await post(page.request,baseURL!,'/api/clinical/event',eventData(id,1))).status()).toBe(409);expect((await post(page.request,baseURL!,'/api/clinical/sign',{...input,password:process.env.DEMO_ACCOUNT_PASSWORD})).status()).toBe(409);
 const before=JSON.stringify(detail.event.snapshot);const add=await post(page.request,baseURL!,'/api/clinical/addendum',{kind:'event',id:original.id,text:'Synthetic clarification appended after signing.',password:process.env.DEMO_ACCOUNT_PASSWORD});expect(add.status()).toBe(201);detail=await add.json();expect(JSON.stringify(detail.event.snapshot)).toBe(before);expect(detail.event.contentHash).toBe(review.hash);expect(detail.addenda).toHaveLength(1);
});

test('draft concurrency and invalid laterality are rejected; unsigned prescriptions never enter pharmacy',async({page,baseURL})=>{
 const {id}=await prepare(page.request,baseURL!);const data=eventData(id);expect((await post(page.request,baseURL!,'/api/clinical/event',{...data,plans:[{...data.plans[0],eye:'LEFT'}]})).status()).toBe(400);
 const responses=await Promise.all([post(page.request,baseURL!,'/api/clinical/event',data),post(page.request,baseURL!,'/api/clinical/event',data)]);expect(responses.map(r=>r.status()).sort()).toEqual([200,409]);
 const drug=(await(await page.request.get('/api/clinical/formulary')).json()).drugs[0];const rx=await post(page.request,baseURL!,'/api/clinical/prescription',rxData(id,drug));expect(rx.status()).toBe(200);const detail=await rx.json();expect((await post(page.request,baseURL!,'/api/clinical/review',{kind:'prescription',id:detail.prescription.id,version:1})).status()).toBe(409);
 await login(page.request,baseURL!,'pharmacy');const list=await(await page.request.get('/api/clinical/prescriptions')).json();expect(list.prescriptions.some((r:{id:string})=>r.id===detail.prescription.id)).toBe(false);expect((await page.request.get(`/api/clinical/pdf?id=${detail.prescription.id}`)).status()).toBe(404);expect((await page.request.get(`/api/clinical/detail?encounterId=${id}`)).status()).toBe(403);
});

test('signed prescription guards protect parent and items; addenda appear without exposing PHI in QR verification',async({page,browser,baseURL})=>{
 const {id}=await prepare(page.request,baseURL!);let detail=await saveEvent(page.request,baseURL!,id);await signRecord(page.request,baseURL!,'event',detail.event);const drug=(await(await page.request.get('/api/clinical/formulary')).json()).drugs[0];detail=await(await post(page.request,baseURL!,'/api/clinical/prescription',rxData(id,drug))).json();detail=await signRecord(page.request,baseURL!,'prescription',detail.prescription);const rx=detail.prescription;
 expect((await post(page.request,baseURL!,'/api/clinical/prescription',rxData(id,drug,1))).status()).toBe(409);
 const db=new pg.Client({connectionString:process.env.DATABASE_URL});await db.connect();try{await db.query('BEGIN');await db.query("SELECT set_config('app.tenant_id',$1,true)",[rx.snapshot.tenantId]);for(const query of ['UPDATE app.prescription SET status=\'draft\' WHERE id=$1','DELETE FROM app.prescription_item WHERE prescription_id=$1']){await db.query('SAVEPOINT blocked');await expect(db.query(query,[rx.id])).rejects.toMatchObject({code:'42501'});await db.query('ROLLBACK TO SAVEPOINT blocked');}}finally{await db.query('ROLLBACK');await db.end();}
 const added=await post(page.request,baseURL!,'/api/clinical/addendum',{kind:'prescription',id:rx.id,text:'Synthetic prescription clarification; original items remain unchanged.',password:process.env.DEMO_ACCOUNT_PASSWORD});expect(added.status()).toBe(201);expect((await added.json()).prescription.contentHash).toBe(rx.contentHash);
 await login(page.request,baseURL!,'pharmacy');const record=await(await page.request.get(`/api/clinical/prescription?id=${rx.id}`)).json();expect(record.addenda).toHaveLength(1);const anonymous=await browser.newContext({baseURL});const check=await anonymous.request.get(record.verificationUrl);expect(check.status()).toBe(200);const html=await check.text();expect(html).toContain(rx.contentHash);expect(html).not.toContain(record.snapshot.patient.name);expect(html).not.toContain(record.snapshot.patient.mrn);expect(html).not.toContain(drug.name);expect((await anonymous.request.get(record.verificationUrl.replace(/token=.*/,'token='+'0'.repeat(64)))).status()).toBe(404);expect((await anonymous.request.get(`/api/clinical/pdf?id=${rx.id}`)).status()).toBe(401);await anonymous.close();
});

test('patient timelines distinguish seeded history from a new patient and respect facility access',async({page,baseURL})=>{
 const {id,patient}=await prepare(page.request,baseURL!);const history=await(await page.request.get(`/api/clinical/timeline?patientId=${patient.id}`)).json();expect(history.entries).toHaveLength(1);expect(history.entries[0].synthetic).toBe(false);
 const db=new pg.Client({connectionString:process.env.DATABASE_ADMIN_URL});await db.connect();try{const original=(await db.query("SELECT id FROM app.patient WHERE right(mrn,6)='000007' AND tenant_id=(SELECT id FROM app.tenant WHERE code='DEMO')")).rows[0];const seeded=await(await page.request.get(`/api/clinical/timeline?patientId=${original.id}`)).json();expect(seeded.entries.filter((row:{synthetic:boolean})=>row.synthetic)).toHaveLength(6);
 const own=(await db.query("SELECT u.id,u.tenant_id,e.facility_id FROM app.user_account u JOIN app.encounter e ON e.doctor_id=u.id WHERE e.id=$1",[id])).rows[0];await db.query('DELETE FROM app.user_facility WHERE user_id=$1 AND facility_id=$2',[own.id,own.facility_id]);try{expect((await page.request.get(`/api/clinical/detail?encounterId=${id}`)).status()).toBe(404);expect((await post(page.request,baseURL!,'/api/clinical/event',eventData(id))).status()).toBe(404);}finally{await db.query('INSERT INTO app.user_facility(tenant_id,user_id,facility_id) VALUES($1,$2,$3)',[own.tenant_id,own.id,own.facility_id]);}
 }finally{await db.end();}
 await login(page.request,baseURL!,'reception');expect((await page.request.get(`/api/clinical/timeline?patientId=${patient.id}`)).status()).toBe(403);expect((await post(page.request,baseURL!,'/api/clinical/event',eventData(id))).status()).toBe(403);
});

test('a changed allergy flag invalidates the reviewed snapshot; warnings cannot be bypassed',async({page,baseURL})=>{
 const {id,patient}=await prepare(page.request,baseURL!);let detail=await saveEvent(page.request,baseURL!,id);const record=detail.event;const review=await(await post(page.request,baseURL!,'/api/clinical/review',{kind:'event',id:record.id,version:1})).json();
 const db=new pg.Client({connectionString:process.env.DATABASE_ADMIN_URL});await db.connect();try{await db.query("INSERT INTO app.patient_flag(tenant_id,patient_id,type,value,created_by) SELECT tenant_id,id,'allergy','Additional synthetic reconciliation flag',created_by FROM app.patient WHERE id=$1",[patient.id]);}finally{await db.end();}
 const stale=await post(page.request,baseURL!,'/api/clinical/sign',{kind:'event',id:record.id,version:1,reviewHash:review.hash,password:process.env.DEMO_ACCOUNT_PASSWORD});expect(stale.status()).toBe(409);expect((await stale.json()).error).toBe('reviewChanged');await signRecord(page.request,baseURL!,'event',record);
 const drug=(await(await page.request.get('/api/clinical/formulary')).json()).drugs[0];detail=await(await post(page.request,baseURL!,'/api/clinical/prescription',rxData(id,drug))).json();const rxReview=await(await post(page.request,baseURL!,'/api/clinical/review',{kind:'prescription',id:detail.prescription.id,version:1})).json();expect(rxReview.warnings).toContain('allergyReview');expect((await post(page.request,baseURL!,'/api/clinical/sign',{kind:'prescription',id:detail.prescription.id,version:1,reviewHash:rxReview.hash,password:process.env.DEMO_ACCOUNT_PASSWORD})).status()).toBe(400);
});

test('an unsigned prescription can be discarded so consultation can complete without medication',async({page,baseURL})=>{
 const {id}=await prepare(page.request,baseURL!);let detail=await saveEvent(page.request,baseURL!,id);detail=await signRecord(page.request,baseURL!,'event',detail.event);const drug=(await(await page.request.get('/api/clinical/formulary')).json()).drugs[0];const rx=await post(page.request,baseURL!,'/api/clinical/prescription',rxData(id,drug));expect(rx.status()).toBe(200);
 const discarded=await post(page.request,baseURL!,'/api/clinical/discard-prescription',{encounterId:id,version:1});expect(discarded.status()).toBe(200);expect((await discarded.json()).prescription).toBeNull();expect((await post(page.request,baseURL!,'/api/clinical/complete',{encounterId:id,version:detail.encounter.version})).status()).toBe(200);
});

test('Patient 360 opens historical signed content and the clinical layout fits a tablet',async({page,baseURL})=>{
 await login(page.request,baseURL!,'doctor');await page.goto('/');await page.getByRole('button',{name:'Patients',exact:true}).click();await page.getByRole('textbox',{name:'Search patients',exact:true}).fill('Nasreen Ahmed');await page.getByRole('button',{name:'Search',exact:true}).click();await page.getByRole('button',{name:'View record Nasreen Ahmed',exact:true}).click();await page.getByRole('button',{name:'Patient 360',exact:true}).click();const history=page.getByRole('dialog',{name:'Patient 360',exact:true});await expect(history.locator('.clinical-history>button')).toHaveCount(7);await history.locator('.clinical-history>button').last().click();const editor=page.locator('.doctor-dialog');await expect(editor.getByLabel('Presenting complaint',{exact:true})).toBeDisabled();await expect(editor.getByText('Synthetic historical example',{exact:false}).first()).toBeVisible();
 await page.setViewportSize({width:820,height:1180});await editor.locator(':scope > .intake-dialog-body').evaluate(node=>node.scrollTo(0,0));await page.screenshot({path:'test-results/clinical-tablet.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect((await editor.boundingBox())!.width).toBeLessThanOrEqual(820);const fields=editor.locator('.clinical-bilateral>label');const od=await fields.nth(0).boundingBox(),os=await fields.nth(1).boundingBox();expect(od!.x).toBeLessThan(os!.x);
});
