import { test, expect, type APIRequestContext } from '@playwright/test';
import { financialSummary, invoiceStatus, invoiceTotal, stockSummary, type OperationsFixture, type SampleInvoice } from '../../src/lib/operations';
import pg from 'pg';
const emails = { doctor: 'hamza.ali', pharmacist: 'sana.iqbal', cashier: 'imran.shah', inventory: 'hina.aslam', admin: 'omar.siddiqui', auditor: 'maryam.saeed', reception: 'aisha.malik' };
async function login(request: APIRequestContext, origin: string, role: keyof typeof emails) { const response = await request.post('/api/auth/login', { headers: { Origin: origin }, data: { email: `${emails[role]}@demo.openeyes.local`, password: process.env.DEMO_ACCOUNT_PASSWORD } }); expect(response.status()).toBe(200); }

test('legacy sample snapshots stay read-only and cannot grant operational writes',async({page,baseURL})=>{await login(page.request,baseURL!,'pharmacist');const before=await(await page.request.get('/api/previews/inventory')).json();expect(before.sample).toBe(true);for(const method of ['POST','PATCH','DELETE'])expect((await page.request.fetch('/api/previews/inventory',{method,headers:{Origin:baseURL!},data:{quantity:0}})).status()).toBe(405);await page.goto('/');await page.getByRole('button',{name:'Pharmacy',exact:true}).click();await expect(page.getByRole('heading',{name:'Batch stock',exact:true})).toBeVisible();await expect(page.getByText('SAMPLE DATA',{exact:true})).toHaveCount(0);});
test('operational screens and real report pages enforce authentication and roles',async({page,baseURL})=>{expect((await page.request.get('/api/operations/billing')).status()).toBe(401);await login(page.request,baseURL!,'reception');for(const resource of ['inventory','billing','surgery','management'])expect((await page.request.get('/api/operations/'+resource)).status()).toBe(403);await login(page.request,baseURL!,'auditor');expect((await page.request.get('/api/operations/management')).status()).toBe(200);expect((await page.request.post('/api/operations/billing',{headers:{Origin:baseURL!},data:{action:'open_session',facilityId:crypto.randomUUID(),opening:0}})).status()).toBe(403);});
test('audit filters distinguish real signatures and preview reads from the seeded break-glass example', async ({ page, baseURL }) => {
  await login(page.request, baseURL!, 'auditor'); await page.request.get('/api/previews/management'); await page.goto('/'); await page.getByRole('button', { name: 'Audit trail', exact: true }).click(); await page.getByLabel('Audit action group').selectOption('examples'); await expect(page.getByText('SEEDED EXAMPLE — no access was granted', { exact: true })).toBeVisible(); await page.getByLabel('Audit action group').selectOption('previews'); await expect(page.getByText('Sample management viewed', { exact: true }).first()).toBeVisible();
  const data = await (await page.request.get('/api/audit?group=clinical')).json(); for (const event of data.events) expect(['clinical.signed','prescription.signed','clinical.addendum']).toContain(event.action);
  expect((await page.request.get('/api/audit?group=invalid')).status()).toBe(400); await page.screenshot({ path: 'test-results/operations-audit.png', fullPage: true });
  const db = new pg.Client({ connectionString: process.env.DATABASE_ADMIN_URL }); await db.connect(); try { const example = (await db.query("SELECT count(*)::int AS total FROM app.audit_log WHERE action='security.break_glass_example' AND tenant_id=(SELECT id FROM app.tenant WHERE code='DEMO')")).rows[0]; expect(example.total).toBe(1); } finally { await db.end(); }
});
