import { test,expect,type APIRequestContext } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { writeFileSync } from 'node:fs';
import { contentHash } from '../../src/server/clinical-hash';
import { todayKarachi } from '../../src/lib/patients';
const roles={reception:'aisha.malik',nurse:'nadia.raza',doctor:'sara.khan',other:'hamza.ali',pharmacy:'sana.iqbal'};
async function login(request:APIRequestContext,origin:string,role:keyof typeof roles){const response=await request.post('/api/auth/login',{headers:{Origin:origin},data:{email:`${roles[role]}@demo.openeyes.local`,password:process.env.DEMO_ACCOUNT_PASSWORD}});expect(response.status()).toBe(200);}
async function post(request:APIRequestContext,origin:string,path:string,data:unknown){return request.post(path,{headers:{Origin:origin},data});}
async function prepare(request:APIRequestContext,origin:string){
 await login(request,origin,'reception');const suffix=String(Date.now()).slice(-7);const input={givenName:'Clinical',familyName:`Review${suffix}`,gender:'female',dob:'1965-01-01',dobEstimated:false,phone:`0300${suffix}`,identifierType:'cnic',identifier:`00000${suffix}0`,allergy:'Synthetic allergy requiring reconciliation',city:'Karachi'};
 const review=await(await post(request,origin,'/api/patients/duplicates',input)).json();const response=await post(request,origin,'/api/patients',{...input,duplicateReviewToken:review.reviewToken});expect(response.status()).toBe(201);const patient=(await response.json()).patient;
 const clinic=(await(await request.get('/api/intake/clinics')).json()).clinics.find((item:{name:string})=>item.name==='General Ophthalmology');const doctor=clinic.doctors.find((item:{name:string})=>item.name.includes('Sara'));const date=todayKarachi();const slots=await(await request.get(`/api/intake/slots?facilityId=${clinic.id}&doctorId=${doctor.id}&date=${date}`)).json();
 const booked=await post(request,origin,'/api/intake/appointments',{patientId:patient.id,facilityId:clinic.id,doctorId:doctor.id,date,time:slots.slots.at(-1)});expect(booked.status()).toBe(201);const arrival=await post(request,origin,'/api/intake/checkin',{appointmentId:(await booked.json()).id});expect(arrival.status()).toBe(201);const id=(await arrival.json()).id;
 await post(request,origin,'/api/intake/transition',{encounterId:id,version:1,to:'workup'});await login(request,origin,'nurse');const eye={uncorrected:'6/12',pinhole:'6/9',corrected:'6/6',iop:16,method:'NCT',measuredAt:new Date().toISOString()};expect((await post(request,origin,'/api/intake/workup',{encounterId:id,version:0,OD:eye,OS:eye,notes:'Synthetic workup'})).status()).toBe(201);expect((await post(request,origin,'/api/intake/transition',{encounterId:id,version:2,to:'consultation'})).status()).toBe(200);await login(request,origin,'doctor');return {id,patient};
}
function eventData(id:string,version=0){return {encounterId:id,version,complaint:'Synthetic blurred vision review',findings:{OD:'Synthetic right-eye finding',OS:'Synthetic left-eye finding'},diagnoses:[{eye:'OU',label:'Synthetic cataract example'}],plans:[{id:randomUUID(),eye:'OD',anatomySite:'optic_nerve',intent:'observation',notes:'Synthetic anatomy-linked plan'}],referral:'Demo referral note',followUp:'Demo follow-up note'};}
async function saveEvent(request:APIRequestContext,origin:string,id:string){const result=await post(request,origin,'/api/clinical/event',eventData(id));expect(result.status()).toBe(200);return result.json();}
async function signRecord(request:APIRequestContext,origin:string,kind:string,record:{id:string;version:number}){const response=await post(request,origin,'/api/clinical/review',{kind,id:record.id,version:record.version});expect(response.status()).toBe(200);const review=await response.json();const signed=await post(request,origin,'/api/clinical/sign',{kind,id:record.id,version:record.version,reviewHash:review.hash,password:process.env.DEMO_ACCOUNT_PASSWORD,warningReason:review.warnings.length?'Reviewed synthetic warning flags':''});expect(signed.status()).toBe(200);return signed.json();}
function rxData(id:string,drug:{id:string;name:string;strength:string},version=0){return {encounterId:id,version,items:['OD','OS'].map(eye=>({id:randomUUID(),drugId:drug.id,name:drug.name,strength:drug.strength,eye,dose:'Demo dose',route:'Demo route',frequency:'Demo frequency',duration:'Demo duration',instructions:'Synthetic instructions only',instructionsUr:'صرف نمونہ'}))};}


async function loginAs(request:APIRequestContext,origin:string,name:string,password=process.env.DEMO_ACCOUNT_PASSWORD!){const r=await post(request,origin,'/api/auth/login',{email:name.includes('@')?name:name+'@demo.openeyes.local',password});expect(r.status(),await r.text()).toBe(200);return (await r.json()).user;}
async function ok(request:APIRequestContext,origin:string,path:string,data:unknown){const r=await post(request,origin,path,data);expect(r.status(),await r.text()).toBeLessThan(300);return r.json();}
test('administration creates accounts, forces password change, protects roles and revokes sessions',async({page,browser,baseURL})=>{
 const user=await loginAs(page.request,baseURL!,'omar.siddiqui');const data=await(await page.request.get('/api/administration/overview')).json();const email=`usable-${Date.now()}@test.invalid`,password='Temporary-test-pass-981',newPassword='Personal-test-pass-982';
 const staff={version:0,name:'Usable test staff',email,designation:'Reception test',licence:'',licenceExpiry:null,facilityIds:user.facilityIds,roles:['receptionist'],temporaryPassword:password,currentPassword:process.env.DEMO_ACCOUNT_PASSWORD};
 expect((await post(page.request,baseURL!,'/api/administration/staff',{...staff,roles:['security_admin']})).status()).toBe(403);
 const created=await ok(page.request,baseURL!,'/api/administration/staff',staff);const target=await browser.newContext();await loginAs(target.request,baseURL!,email,password);expect((await target.request.get('/api/intake/clinics')).status()).toBe(403);
 await ok(target.request,baseURL!,'/api/auth/password',{currentPassword:password,password:newPassword});expect((await target.request.get('/api/auth/session')).status()).toBe(401);await loginAs(target.request,baseURL!,email,newPassword);expect((await target.request.get('/api/intake/clinics')).status()).toBe(200);
 await loginAs(page.request,baseURL!,'faisal.noor');let current=(await(await page.request.get('/api/administration/overview')).json()).staff.find((s:{id:string})=>s.id===created.id);await ok(page.request,baseURL!,'/api/administration/access',{id:created.id,version:current.version,status:'disabled',roles:['receptionist'],reason:'Test account disabled by security',currentPassword:process.env.DEMO_ACCOUNT_PASSWORD});expect((await target.request.get('/api/auth/session')).status()).toBe(401);
 const security=(await(await page.request.get('/api/auth/session')).json()).user;expect((await post(page.request,baseURL!,'/api/administration/access',{id:security.id,version:1,status:'disabled',roles:['security_admin'],reason:'Attempt self disable',currentPassword:process.env.DEMO_ACCOUNT_PASSWORD})).status()).toBe(403);
 const admin=data.staff.find((s:{roles:string[]})=>s.roles.includes('hospital_admin'));expect((await post(page.request,baseURL!,'/api/administration/access',{id:admin.id,version:admin.version,status:'disabled',roles:admin.roles,reason:'Attempt last administrator removal',currentPassword:process.env.DEMO_ACCOUNT_PASSWORD})).status()).toBe(409);await target.close();
 await loginAs(page.request,baseURL!,'omar.siddiqui');await page.goto('/');await page.getByRole('button',{name:'Administration',exact:true}).click();await expect(page.getByRole('heading',{name:'Staff and user accounts'})).toBeVisible();await expect(page.getByRole('button',{name:'Build roadmap',exact:true})).toHaveCount(0);await expect(page.getByText('Powered by Logic box',{exact:true}).first()).toBeVisible();await page.screenshot({path:'test-results/usable-administration.png',fullPage:true});
});
test('patient corrections and clinical history retain versions and immutable workup details',async({page,baseURL})=>{
 const {id,patient}=await prepare(page.request,baseURL!);await loginAs(page.request,baseURL!,'aisha.malik');const p=(await(await page.request.get('/api/patients/'+patient.id)).json()).patient;const edit={version:p.version,givenName:p.givenName,familyName:p.familyName,gender:p.gender,dob:p.dob,dobEstimated:p.dobEstimated,phone:p.phone,city:'Updated city',address:p.address,preferredLanguage:p.preferredLanguage,nextOfKinName:p.nextOfKinName,nextOfKinPhone:p.nextOfKinPhone,reason:'Corrected address from patient'};await ok(page.request,baseURL!,'/api/patients/'+p.id,edit);expect((await post(page.request,baseURL!,'/api/patients/'+p.id,edit)).status()).toBe(409);const updated=(await(await page.request.get('/api/patients/'+p.id)).json()).patient;expect(updated.mrn).toBe(p.mrn);expect(updated.identifierMasked).toBe(p.identifierMasked);expect(updated.city).toBe('Updated city');
 await loginAs(page.request,baseURL!,'nadia.raza');await ok(page.request,baseURL!,`/api/patients/${p.id}/history`,{action:'history',category:'ocular',text:'Synthetic ocular history entry'});let history=await(await page.request.get(`/api/patients/${p.id}/history`)).json();const original=history.history[0];await ok(page.request,baseURL!,`/api/patients/${p.id}/history`,{action:'history',category:'ocular',text:'Clarified synthetic ocular history',supersedesId:original.id});await ok(page.request,baseURL!,`/api/patients/${p.id}/history`,{action:'flag',type:'risk',value:'Synthetic risk to resolve'});history=await(await page.request.get(`/api/patients/${p.id}/history`)).json();await ok(page.request,baseURL!,`/api/patients/${p.id}/history`,{action:'resolve',id:history.flags[0].id,reason:'Risk confirmed no longer active'});history=await(await page.request.get(`/api/patients/${p.id}/history`)).json();expect(history.history).toHaveLength(2);expect(history.flags[0].resolvedAt).toBeTruthy();
 const detail=await(await page.request.get('/api/intake/workup?encounterId='+id)).json();expect(detail.workup.OD.iop).toBe(16);
});
test('appointments cancel and reschedule atomically without losing the old booking',async({page,baseURL})=>{
 await loginAs(page.request,baseURL!,'aisha.malik');let appts=(await(await page.request.get('/api/intake/appointments?date='+todayKarachi())).json()).appointments;const a=appts.find((a:{status:string})=>a.status==='booked');expect(a).toBeTruthy();const reason='Patient requested a changed appointment';const slots=(await(await page.request.get(`/api/intake/slots?facilityId=${a.facilityId}&doctorId=${a.doctorId}&date=${a.date}`)).json()).slots;
 const replacement=await ok(page.request,baseURL!,'/api/intake/appointment-action',{id:a.id,version:a.version,action:'rescheduled',reason,booking:{facilityId:a.facilityId,doctorId:a.doctorId,date:a.date,time:slots.at(-1)}});appts=(await(await page.request.get('/api/intake/appointments?date='+todayKarachi())).json()).appointments;expect(appts.find((x:{id:string})=>x.id===a.id).status).toBe('rescheduled');const next=appts.find((x:{id:string})=>x.id===replacement.id);await ok(page.request,baseURL!,'/api/intake/appointment-action',{id:next.id,version:next.version,action:'cancelled',reason});expect((await post(page.request,baseURL!,'/api/intake/checkin',{appointmentId:next.id})).status()).toBe(409);
});
test('clinic configuration drives slot availability without removing historical roster references',async({page,baseURL})=>{
 await loginAs(page.request,baseURL!,'omar.siddiqui');let d=await(await page.request.get('/api/administration/overview')).json();const f=d.facilities.find((f:{name:string})=>f.name==='General Ophthalmology');const tomorrow=new Date(Date.parse(todayKarachi())+86400000).toISOString().slice(0,10);await ok(page.request,baseURL!,'/api/administration/facility',{...f,closedDates:[tomorrow]});const slots=await(await page.request.get(`/api/intake/slots?facilityId=${f.id}&doctorId=${f.doctorIds[0]}&date=${tomorrow}`)).json();expect(slots.slots).toHaveLength(0);await ok(page.request,baseURL!,'/api/administration/facility',{...f,version:f.version+1});
});
test('cataract surgery requires consent, verified pre-op, operation note and follow-up records',async({page,baseURL})=>{
 const db=new pg.Client({connectionString:process.env.DATABASE_ADMIN_URL});
 await db.connect();
 try {
  await db.query("INSERT INTO app.user_facility(tenant_id,user_id,facility_id) SELECT u.tenant_id,u.id,f.id FROM app.user_account u JOIN app.facility f ON f.tenant_id=u.tenant_id WHERE u.email='sara.khan@demo.openeyes.local' AND f.type='theatre' ON CONFLICT DO NOTHING");
 } finally { await db.end(); }
 await loginAs(page.request,baseURL!,'sara.khan');
 const data=await(await page.request.get('/api/operations/surgery')).json();
 const theatre=data.facilities.find((facility:{type:string})=>facility.type==='theatre');
 const procedure=data.procedures.find((item:{code:string})=>item.code==='cataract-phaco-iol');
 const surgeon=data.surgeons.find((item:{name:string})=>item.name==='Dr. Sara Khan');
 expect(theatre).toBeTruthy();
 expect(procedure).toBeTruthy();
 expect(surgeon).toBeTruthy();
 const created=await ok(page.request,baseURL!,'/api/operations/surgery',{action:'create',encounterId:data.encounters[0].id,facilityId:theatre.id,surgeonId:surgeon.id,eye:'OD',procedureCode:procedure.code});
 const stage={action:'advance',id:created.id,version:1,stage:'consent',eye:'OD',notes:'Consent verified for cataract pathway'};
 expect((await post(page.request,baseURL!,'/api/operations/surgery',stage)).status()).toBe(409);
 const file={name:'synthetic-consent.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6GtMAAAAASUVORK5CYII=','base64')};
 const uploaded=await page.request.post('/api/operations/consent',{headers:{Origin:baseURL!},multipart:{caseId:created.id,eye:'OD',signatoryType:'patient',signatoryName:'Synthetic patient',relationship:'',witnessName:'Synthetic witness',witnessRole:'Clinical witness',accepted:'true',file}});
 const consent=await uploaded.json();expect(uploaded.status(),JSON.stringify(consent)).toBe(200);
 expect((await post(page.request,baseURL!,'/api/operations/surgery',stage)).status()).toBe(409);
 await loginAs(page.request,baseURL!,'nadia.raza');
 expect((await post(page.request,baseURL!,'/api/operations/consent',{action:'confirm',consentVersionId:consent.id})).status()).toBe(403);
 await loginAs(page.request,baseURL!,'sara.khan');
 await ok(page.request,baseURL!,'/api/operations/consent',{action:'confirm',consentVersionId:consent.id});
 await ok(page.request,baseURL!,'/api/operations/consent',{action:'withdraw',consentVersionId:consent.id,reason:'Patient requested a revised consent record'});
 expect((await post(page.request,baseURL!,'/api/operations/surgery',stage)).status()).toBe(409);
 const replacementResponse=await page.request.post('/api/operations/consent',{headers:{Origin:baseURL!},multipart:{caseId:created.id,eye:'OD',signatoryType:'patient',signatoryName:'Synthetic patient',relationship:'',witnessName:'Synthetic witness',witnessRole:'Clinical witness',accepted:'true',file}});
 const replacement=await replacementResponse.json();expect(replacementResponse.status(),JSON.stringify(replacement)).toBe(200);
 await ok(page.request,baseURL!,'/api/operations/consent',{action:'confirm',consentVersionId:replacement.id});
 await ok(page.request,baseURL!,'/api/operations/surgery',stage);
 await ok(page.request,baseURL!,'/api/operations/surgery',{action:'save_preop',id:created.id,version:0,eye:'OD',axialLength:23.45,keratometryK1:43.1,keratometryK2:44.2,targetRefraction:-0.25,iolModel:'Synthetic IOL',iolPower:21.5,anaesthesia:'topical',biometryVerified:true,medicalClearance:true,pupilDilation:true,notes:'Synthetic pre-operative assessment'});
 await ok(page.request,baseURL!,'/api/operations/surgery',{...stage,version:2,stage:'preop',notes:'Pre-operative assessment verified'});
 const scheduled=new Date(Date.now()+86400000).toISOString();
 expect((await post(page.request,baseURL!,'/api/operations/surgery',{...stage,version:3,stage:'scheduled',eye:'OS',scheduled})).status()).toBe(409);
 await ok(page.request,baseURL!,'/api/operations/surgery',{...stage,version:3,stage:'scheduled',scheduled,notes:'Scheduled after verified assessment'});
 expect((await post(page.request,baseURL!,'/api/operations/surgery',{...stage,version:4,stage:'operated',notes:'Attempt without operation note'})).status()).toBe(409);
 await ok(page.request,baseURL!,'/api/operations/surgery',{action:'save_operation',id:created.id,version:0,eye:'OD',procedurePerformed:'Phacoemulsification and IOL',anaesthesia:'topical',incision:'2.4 mm clear corneal',capsulorhexis:'Continuous curvilinear',phacoTechnique:'Divide and conquer',iolModel:'Synthetic IOL',iolPower:21.5,complications:'None',postoperativeInstructions:'Topical medication and protective shield'});
 await ok(page.request,baseURL!,'/api/operations/surgery',{...stage,version:4,stage:'operated',notes:'Procedure completed without complication'});
 await ok(page.request,baseURL!,'/api/operations/surgery',{action:'save_followup',id:created.id,version:0,visitType:'day_1',eye:'OD',uncorrectedAcuity:'6/12',correctedAcuity:'6/6',iop:15,wound:'Secure',cornea:'Clear',anteriorChamber:'Deep and quiet',iolPosition:'Centered',medications:'Continue prescribed drops',plan:'Review in one week'});
 await ok(page.request,baseURL!,'/api/operations/surgery',{action:'save_followup',id:created.id,version:1,visitType:'day_1',eye:'OD',uncorrectedAcuity:'6/9',correctedAcuity:'6/6',iop:14,wound:'Secure',cornea:'Clear',anteriorChamber:'Deep and quiet',iolPosition:'Centered',medications:'Continue prescribed drops',plan:'Corrected review in one week'});
 const refreshed=await(await page.request.get('/api/operations/surgery')).json();
 const saved=refreshed.cases.find((item:{id:string})=>item.id===created.id);
 expect(saved.preop.biometryVerified).toBe(true);
 expect(saved.surgeon).toBe('Dr. Sara Khan');
 expect(saved.readiness.status).toBe('completed');
 expect(saved.consents[0].version).toBe(2);
 expect(saved.consents[0].status).toBe('confirmed');
 expect(saved.consents[0].confirmedBy).toBe('Dr. Sara Khan');
 expect(saved.consents[1].status).toBe('withdrawn');
 expect(saved.consents[1].withdrawalReason).toBe('Patient requested a revised consent record');
 expect(saved.operationNote.iolModel).toBe('Synthetic IOL');
 expect(saved.followups).toHaveLength(1);
 expect(saved.followups[0].version).toBe(2);
 expect(saved.followups[0].plan).toBe('Corrected review in one week');
 await page.goto('/');
 await page.getByRole('button',{name:'Surgery lifecycle',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Theatre worklist',exact:true})).toBeVisible();
 await expect(page.getByRole('heading',{name:'Surgery cases',exact:true})).toBeVisible();
 await page.screenshot({path:'test-results/usable-surgery.png',fullPage:true});
});
test('live dashboards derive clinical records and reports enforce roles',async({page,baseURL})=>{
 await loginAs(page.request,baseURL!,'omar.siddiqui');const data=await(await page.request.get('/api/operations/management')).json();expect(data.bookings.total).toBeGreaterThanOrEqual(0);expect(Array.isArray(data.surgery)).toBe(true);expect(Array.isArray(data.waits)).toBe(true);expect(data.documentation.visits).toBeGreaterThanOrEqual(data.documentation.signed);for(const type of ['clinic','staff','events']){const response=await page.request.get('/api/reports/'+type+'?date='+todayKarachi()+'&format=csv');expect(response.status(),await response.text()).toBe(200);expect(response.headers()['content-type']).toContain('text/csv');}for(const retired of ['cashier','dispensing','expiry'])expect((await page.request.get('/api/reports/'+retired+'?date='+todayKarachi()+'&format=csv')).status()).toBe(400);await page.goto('/');await page.getByRole('button',{name:'Management',exact:true}).click();await expect(page.getByRole('heading',{name:'Signed clinical documentation'})).toBeVisible();await page.setViewportSize({width:820,height:1180});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('consultation completion closes the queue directly and walk-in workup remains functional',async({page,baseURL})=>{
 const {id}=await prepare(page.request,baseURL!);let detail=await saveEvent(page.request,baseURL!,id);detail=await signRecord(page.request,baseURL!,'event',detail.event);const completed=await ok(page.request,baseURL!,'/api/clinical/complete',{encounterId:id,version:detail.encounter.version});expect(completed.encounter.stage).toBe('completed');expect(completed.encounter.closedAt).toBeTruthy();await loginAs(page.request,baseURL!,'aisha.malik');expect((await(await page.request.get('/api/intake/queue')).json()).encounters.some((entry:{id:string})=>entry.id===id)).toBe(false);
 const clinics=(await(await page.request.get('/api/intake/clinics')).json()).clinics;const clinic=clinics[0];const suffix=String(Date.now()).slice(-7),input={givenName:'Walkin',familyName:'Validation'+suffix,gender:'male',dob:'1990-01-01',phone:'0300'+suffix,identifierType:'cnic',identifier:'00000'+suffix+'0'};const review=await(await post(page.request,baseURL!,'/api/patients/duplicates',input)).json();const registered=await ok(page.request,baseURL!,'/api/patients',{...input,duplicateReviewToken:review.reviewToken});const walk={patientId:registered.patient.id,facilityId:clinic.id,doctorId:clinic.doctors[0].id};const arrival=await ok(page.request,baseURL!,'/api/intake/walkin',walk);expect(arrival.id).toBeTruthy();expect((await post(page.request,baseURL!,'/api/intake/walkin',walk)).status()).toBe(409);await ok(page.request,baseURL!,'/api/intake/transition',{encounterId:arrival.id,version:1,to:'workup'});await loginAs(page.request,baseURL!,'nadia.raza');const eye={uncorrected:'6/12',pinhole:'6/9',corrected:'6/6',iop:16,method:'NCT',measuredAt:new Date().toISOString(),refraction:{sphere:-1.25,cylinder:-0.5,axis:90,add:1.5,pd:32},logmar:{uncorrected:0.3,pinhole:0.18,corrected:0}};const saved=await ok(page.request,baseURL!,'/api/intake/workup',{encounterId:arrival.id,version:0,OD:eye,OS:eye,notes:'Synthetic refraction and logMAR verification'});expect(saved.workup.OD.refraction.axis).toBe(90);expect(saved.workup.OS.logmar.uncorrected).toBe(0.3);
});
test('identity corrections stay encrypted, reject duplicates and preserve the MRN',async({page,baseURL})=>{await loginAs(page.request,baseURL!,'aisha.malik');const people=(await(await post(page.request,baseURL!,'/api/patients/search',{query:'',page:1})).json()).patients;const p=(await(await page.request.get('/api/patients/'+people[0].id)).json()).patient;const body={version:p.version,givenName:p.givenName,familyName:p.familyName,gender:p.gender,dob:p.dob,dobEstimated:p.dobEstimated,phone:p.phone,city:p.city,address:p.address,preferredLanguage:p.preferredLanguage,nextOfKinName:p.nextOfKinName,nextOfKinPhone:p.nextOfKinPhone,reason:'Identity checked against replacement document',identifierType:'passport',identifier:'TEST'+Date.now().toString().slice(-9)};await ok(page.request,baseURL!,'/api/patients/'+p.id,body);const updated=(await(await page.request.get('/api/patients/'+p.id)).json()).patient;expect(updated.mrn).toBe(p.mrn);expect(updated.identifierMasked.endsWith(body.identifier.slice(-4))).toBe(true);expect(JSON.stringify(updated)).not.toContain(body.identifier);const summary=await page.request.get('/patients/'+p.id+'/summary');expect(summary.status()).toBe(200);expect(await summary.text()).not.toContain(body.identifier);});
