import { test,expect,type APIRequestContext } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { writeFileSync } from 'node:fs';
import { contentHash } from '../../src/server/clinical-hash';
import { todayKarachi } from '../../src/lib/patients';
const roles={reception:'aisha.malik',nurse:'nadia.raza',doctor:'sara.khan',other:'hamza.ali',pharmacy:'sana.iqbal'};
async function login(request:APIRequestContext,origin:string,role:keyof typeof roles){const response=await request.post('/api/auth/login',{headers:{Origin:origin},data:{email:`${roles[role]}@demo.openeyes.local`,password:process.env.DEMO_ACCOUNT_PASSWORD}});expect(response.status()).toBe(200);}
async function post(request:APIRequestContext,origin:string,path:string,data:unknown){return request.post(path,{headers:{Origin:origin},data});}
async function prepare(request:APIRequestContext,origin:string){
 await login(request,origin,'reception');const suffix=String(Date.now()).slice(-7);const input={givenName:'Clinical',familyName:`Review${suffix}`,gender:'female',dob:'1965-01-01',dobEstimated:false,phone:`0300${suffix}`,identifierType:'cnic',identifier:`00000${suffix}0`,allergy:'Synthetic allergy requiring reconciliation',city:'Karachi'};
 const review=await(await post(request,origin,'/api/patients/duplicates',input)).json();const response=await post(request,origin,'/api/patients',{...input,duplicateReviewToken:review.reviewToken});expect(response.status()).toBe(201);const patient=(await response.json()).patient;
 const clinic=(await(await request.get('/api/intake/clinics')).json()).clinics.find((item:{name:string})=>item.name==='General Ophthalmology');const doctor=clinic.doctors.find((item:{name:string})=>item.name.includes('Sara'));const date=todayKarachi();const slots=await(await request.get(`/api/intake/slots?facilityId=${clinic.id}&doctorId=${doctor.id}&date=${date}`)).json();
 const booked=await post(request,origin,'/api/intake/appointments',{patientId:patient.id,facilityId:clinic.id,doctorId:doctor.id,date,time:slots.slots.at(-1)});expect(booked.status()).toBe(201);const arrival=await post(request,origin,'/api/intake/checkin',{appointmentId:(await booked.json()).id});expect(arrival.status()).toBe(201);const id=(await arrival.json()).id;
 await post(request,origin,'/api/intake/transition',{encounterId:id,version:1,to:'workup'});await login(request,origin,'nurse');const eye={uncorrected:'6/12',pinhole:'6/9',corrected:'6/6',iop:16,method:'NCT',measuredAt:new Date().toISOString()};expect((await post(request,origin,'/api/intake/workup',{encounterId:id,version:0,OD:eye,OS:eye,notes:'Synthetic workup'})).status()).toBe(201);expect((await post(request,origin,'/api/intake/transition',{encounterId:id,version:2,to:'consultation'})).status()).toBe(200);await login(request,origin,'doctor');return {id,patient};
}
function eventData(id:string,version=0){return {encounterId:id,version,complaint:'Synthetic blurred vision review',findings:{OD:'Synthetic right-eye finding',OS:'Synthetic left-eye finding'},diagnoses:[{eye:'OU',label:'Synthetic cataract example'}],plans:[{id:randomUUID(),eye:'OD',anatomySite:'optic_nerve',intent:'observation',notes:'Synthetic anatomy-linked plan'}],referral:'Demo referral note',followUp:'Demo follow-up note'};}
async function saveEvent(request:APIRequestContext,origin:string,id:string){const result=await post(request,origin,'/api/clinical/event',eventData(id));expect(result.status()).toBe(200);return result.json();}
async function signRecord(request:APIRequestContext,origin:string,kind:string,record:{id:string;version:number}){const response=await post(request,origin,'/api/clinical/review',{kind,id:record.id,version:record.version});expect(response.status()).toBe(200);const review=await response.json();const signed=await post(request,origin,'/api/clinical/sign',{kind,id:record.id,version:record.version,reviewHash:review.hash,password:process.env.DEMO_ACCOUNT_PASSWORD,warningReason:review.warnings.length?'Reviewed synthetic warning flags':''});expect(signed.status()).toBe(200);return signed.json();}
function rxData(id:string,drug:{id:string;name:string;strength:string},version=0){return {encounterId:id,version,items:['OD','OS'].map(eye=>({id:randomUUID(),drugId:drug.id,name:drug.name,strength:drug.strength,eye,dose:'Demo dose',route:'Demo route',frequency:'Demo frequency',duration:'Demo duration',instructions:'Synthetic instructions only',instructionsUr:'صرف نمونہ'}))};}


async function loginAs(request:APIRequestContext,origin:string,name:string,password=process.env.DEMO_ACCOUNT_PASSWORD!){const r=await post(request,origin,'/api/auth/login',{email:name.includes('@')?name:name+'@demo.openeyes.local',password});expect(r.status(),await r.text()).toBe(200);return (await r.json()).user;}
async function ok(request:APIRequestContext,origin:string,path:string,data:unknown){const r=await post(request,origin,path,data);expect(r.status(),await r.text()).toBeLessThan(300);return r.json();}
test('administration creates accounts, forces password change, protects roles and revokes sessions',async({page,browser,baseURL})=>{
 const user=await loginAs(page.request,baseURL!,'omar.siddiqui');const data=await(await page.request.get('/api/administration/overview')).json();const email=`usable-${Date.now()}@test.invalid`,password='Temporary-test-pass-981',newPassword='Personal-test-pass-982';
 const staff={version:0,name:'Usable test staff',email,designation:'Reception test',licence:'',licenceExpiry:null,facilityIds:user.facilityIds,roles:['receptionist'],temporaryPassword:password,currentPassword:process.env.DEMO_ACCOUNT_PASSWORD};
 expect((await post(page.request,baseURL!,'/api/administration/staff',{...staff,roles:['security_admin']})).status()).toBe(403);
 const created=await ok(page.request,baseURL!,'/api/administration/staff',staff);const target=await browser.newContext();await loginAs(target.request,baseURL!,email,password);expect((await target.request.get('/api/intake/clinics')).status()).toBe(403);
 await ok(target.request,baseURL!,'/api/auth/password',{currentPassword:password,password:newPassword});expect((await target.request.get('/api/auth/session')).status()).toBe(401);await loginAs(target.request,baseURL!,email,newPassword);expect((await target.request.get('/api/intake/clinics')).status()).toBe(200);
 await loginAs(page.request,baseURL!,'faisal.noor');let current=(await(await page.request.get('/api/administration/overview')).json()).staff.find((s:{id:string})=>s.id===created.id);await ok(page.request,baseURL!,'/api/administration/access',{id:created.id,version:current.version,status:'disabled',roles:['receptionist'],reason:'Test account disabled by security',currentPassword:process.env.DEMO_ACCOUNT_PASSWORD});expect((await target.request.get('/api/auth/session')).status()).toBe(401);
 const security=(await(await page.request.get('/api/auth/session')).json()).user;expect((await post(page.request,baseURL!,'/api/administration/access',{id:security.id,version:1,status:'disabled',roles:['security_admin'],reason:'Attempt self disable',currentPassword:process.env.DEMO_ACCOUNT_PASSWORD})).status()).toBe(403);
 const admin=data.staff.find((s:{roles:string[]})=>s.roles.includes('hospital_admin'));expect((await post(page.request,baseURL!,'/api/administration/access',{id:admin.id,version:admin.version,status:'disabled',roles:admin.roles,reason:'Attempt last administrator removal',currentPassword:process.env.DEMO_ACCOUNT_PASSWORD})).status()).toBe(409);await target.close();
 await loginAs(page.request,baseURL!,'omar.siddiqui');await page.goto('/');await page.getByRole('button',{name:'Administration',exact:true}).click();await expect(page.getByRole('heading',{name:'Staff and user accounts'})).toBeVisible();await expect(page.getByRole('button',{name:'Build roadmap',exact:true})).toHaveCount(0);await expect(page.getByText('Powered by Logic box',{exact:true}).first()).toBeVisible();await page.screenshot({path:'test-results/usable-administration.png',fullPage:true});
});
test('patient corrections and clinical history retain versions and immutable workup details',async({page,baseURL})=>{
 const {id,patient}=await prepare(page.request,baseURL!);await loginAs(page.request,baseURL!,'aisha.malik');const p=(await(await page.request.get('/api/patients/'+patient.id)).json()).patient;const edit={version:p.version,givenName:p.givenName,familyName:p.familyName,gender:p.gender,dob:p.dob,dobEstimated:p.dobEstimated,phone:p.phone,city:'Updated city',address:p.address,preferredLanguage:p.preferredLanguage,nextOfKinName:p.nextOfKinName,nextOfKinPhone:p.nextOfKinPhone,reason:'Corrected address from patient'};await ok(page.request,baseURL!,'/api/patients/'+p.id,edit);expect((await post(page.request,baseURL!,'/api/patients/'+p.id,edit)).status()).toBe(409);const updated=(await(await page.request.get('/api/patients/'+p.id)).json()).patient;expect(updated.mrn).toBe(p.mrn);expect(updated.identifierMasked).toBe(p.identifierMasked);expect(updated.city).toBe('Updated city');
 await loginAs(page.request,baseURL!,'nadia.raza');await ok(page.request,baseURL!,`/api/patients/${p.id}/history`,{action:'history',category:'ocular',text:'Synthetic ocular history entry'});let history=await(await page.request.get(`/api/patients/${p.id}/history`)).json();const original=history.history[0];await ok(page.request,baseURL!,`/api/patients/${p.id}/history`,{action:'history',category:'ocular',text:'Clarified synthetic ocular history',supersedesId:original.id});await ok(page.request,baseURL!,`/api/patients/${p.id}/history`,{action:'flag',type:'risk',value:'Synthetic risk to resolve'});history=await(await page.request.get(`/api/patients/${p.id}/history`)).json();await ok(page.request,baseURL!,`/api/patients/${p.id}/history`,{action:'resolve',id:history.flags[0].id,reason:'Risk confirmed no longer active'});history=await(await page.request.get(`/api/patients/${p.id}/history`)).json();expect(history.history).toHaveLength(2);expect(history.flags[0].resolvedAt).toBeTruthy();
 const detail=await(await page.request.get('/api/intake/workup?encounterId='+id)).json();expect(detail.workup.OD.iop).toBe(16);
});
test('appointments cancel and reschedule atomically without losing the old booking',async({page,baseURL})=>{
 await loginAs(page.request,baseURL!,'aisha.malik');let appts=(await(await page.request.get('/api/intake/appointments?date='+todayKarachi())).json()).appointments;const a=appts.find((a:{status:string})=>a.status==='booked');expect(a).toBeTruthy();const reason='Patient requested a changed appointment';const slots=(await(await page.request.get(`/api/intake/slots?facilityId=${a.facilityId}&doctorId=${a.doctorId}&date=${a.date}`)).json()).slots;
 const replacement=await ok(page.request,baseURL!,'/api/intake/appointment-action',{id:a.id,version:a.version,action:'rescheduled',reason,booking:{facilityId:a.facilityId,doctorId:a.doctorId,date:a.date,time:slots.at(-1)}});appts=(await(await page.request.get('/api/intake/appointments?date='+todayKarachi())).json()).appointments;expect(appts.find((x:{id:string})=>x.id===a.id).status).toBe('rescheduled');const next=appts.find((x:{id:string})=>x.id===replacement.id);await ok(page.request,baseURL!,'/api/intake/appointment-action',{id:next.id,version:next.version,action:'cancelled',reason});expect((await post(page.request,baseURL!,'/api/intake/checkin',{appointmentId:next.id})).status()).toBe(409);
});
test('actual FEFO dispensing is partial, idempotent, bounded and changes stock',async({page,baseURL})=>{
 test.setTimeout(120000);const {id}=await prepare(page.request,baseURL!);let detail=await saveEvent(page.request,baseURL!,id);detail=await signRecord(page.request,baseURL!,'event',detail.event);const drug=(await(await page.request.get('/api/clinical/formulary')).json()).drugs[0];const data=rxData(id,drug);data.items=data.items.slice(0,1);const rx=await ok(page.request,baseURL!,'/api/clinical/prescription',{...data,items:data.items.map(i=>({...i,quantity:3}))});detail=await signRecord(page.request,baseURL!,'prescription',rx.prescription);const itemId=detail.prescription.items[0].id;
 await loginAs(page.request,baseURL!,'omar.siddiqui');const administration=await(await page.request.get('/api/administration/overview')).json();const pharmacy=administration.facilities.find((f:{type:string})=>f.type==='pharmacy');// Facility assignments are configured by another administrator, never self-expanded.
 await loginAs(page.request,baseURL!,'faisal.noor');const staffData=await(await page.request.get('/api/administration/overview')).json();const officer=staffData.staff.find((s:{email:string})=>s.email==='hina.aslam@demo.openeyes.local');await ok(page.request,baseURL!,'/api/administration/staff',{id:officer.id,version:officer.version,name:officer.name,email:officer.email,designation:officer.designation,licence:officer.licence,licenceExpiry:officer.licenceExpiry,roles:officer.roles,facilityIds:[pharmacy.id],currentPassword:process.env.DEMO_ACCOUNT_PASSWORD});await loginAs(page.request,baseURL!,'hina.aslam');
 for(const [days,qty] of [[30,1],[60,4]])await ok(page.request,baseURL!,'/api/operations/inventory',{action:'receipt',requestId:randomUUID(),facilityId:pharmacy.id,drugId:drug.id,batch:'E2E-'+id.slice(0,8)+'-'+days,expiry:new Date(Date.now()+days*86400000).toISOString().slice(0,10),unitCost:10000,quantity:qty,reason:'Synthetic stock received for validation'});
 await loginAs(page.request,baseURL!,'sana.iqbal');const requestId=randomUUID(),body={action:'dispense',requestId,itemId,facilityId:pharmacy.id,quantity:2};await ok(page.request,baseURL!,'/api/operations/dispensing',body);await ok(page.request,baseURL!,'/api/operations/dispensing',body);let inventory=await(await page.request.get('/api/operations/inventory')).json();let supply=inventory.prescriptions.find((r:{id:string})=>r.id===detail.prescription.id);expect(supply.items[0].dispensed).toBe(2);expect((await post(page.request,baseURL!,'/api/operations/dispensing',{...body,requestId:randomUUID(),quantity:2})).status()).toBe(409);await ok(page.request,baseURL!,'/api/operations/dispensing',{...body,requestId:randomUUID(),quantity:1});await page.goto('/');await page.getByRole('button',{name:'Pharmacy',exact:true}).click();await expect(page.getByRole('heading',{name:'Batch stock',exact:true})).toBeVisible();await page.screenshot({path:'test-results/usable-pharmacy.png',fullPage:true});
});
test('billing uses partial payments, gapless receipt retries, second-user refunds and explained cash variance',async({page,baseURL})=>{
 await loginAs(page.request,baseURL!,'omar.siddiqui');await ok(page.request,baseURL!,'/api/operations/billing',{action:'service',name:'E2E consultation '+Date.now(),category:'consultation',price:10000});let d=await(await page.request.get('/api/operations/billing')).json();const service=d.services.find((s:{name:string})=>s.name.startsWith('E2E'));const encounter=d.encounters.find((e:{facilityId:string})=>e.facilityId===d.facilities.find((f:{name:string})=>f.name==='General Ophthalmology').id);const invoice=await ok(page.request,baseURL!,'/api/operations/billing',{action:'invoice',requestId:randomUUID(),encounterId:encounter.id,lines:[{serviceId:service.id,quantity:1,expectedPrice:service.price}],discount:0,reason:''});await loginAs(page.request,baseURL!,'imran.shah');await ok(page.request,baseURL!,'/api/operations/billing',{action:'open_session',facilityId:encounter.facilityId,opening:1000});const paymentBody={action:'payment',requestId:randomUUID(),invoiceId:invoice.id,amount:4000,method:'cash',reference:''};const payment=await ok(page.request,baseURL!,'/api/operations/billing',paymentBody);const retried=await ok(page.request,baseURL!,'/api/operations/billing',paymentBody);expect(retried.receipt).toBe(payment.receipt);expect((await post(page.request,baseURL!,'/api/operations/billing',{...paymentBody,requestId:randomUUID(),amount:7000})).status()).toBe(409);await ok(page.request,baseURL!,'/api/operations/billing',{action:'refund',paymentId:payment.id,amount:1000,reason:'Synthetic refund request for validation'});d=await(await page.request.get('/api/operations/billing')).json();const refund=d.refunds.find((r:{paymentId:string})=>r.paymentId===payment.id);expect((await post(page.request,baseURL!,'/api/operations/billing',{action:'approve_refund',refundId:refund.id})).status()).toBe(403);await loginAs(page.request,baseURL!,'omar.siddiqui');await ok(page.request,baseURL!,'/api/operations/billing',{action:'approve_refund',refundId:refund.id});await loginAs(page.request,baseURL!,'imran.shah');d=await(await page.request.get('/api/operations/billing')).json();const session=d.sessions.find((s:{closedAt:string|null})=>!s.closedAt);expect(session.currentExpected).toBe(4000);expect((await post(page.request,baseURL!,'/api/operations/billing',{action:'close_session',sessionId:session.id,counted:3900,reason:''})).status()).toBe(400);await ok(page.request,baseURL!,'/api/operations/billing',{action:'close_session',sessionId:session.id,counted:3900,reason:'Counted shortage recorded for test'});await page.goto('/receipts/'+payment.id);await expect(page.getByRole('heading',{name:'Payment receipt',exact:true})).toBeVisible();await page.pdf({path:'test-results/usable-receipt.pdf',format:'A4'});
});

test('clinic configuration drives slot availability without removing historical roster references',async({page,baseURL})=>{
 await loginAs(page.request,baseURL!,'omar.siddiqui');let d=await(await page.request.get('/api/administration/overview')).json();const f=d.facilities.find((f:{name:string})=>f.name==='General Ophthalmology');const tomorrow=new Date(Date.parse(todayKarachi())+86400000).toISOString().slice(0,10);await ok(page.request,baseURL!,'/api/administration/facility',{...f,closedDates:[tomorrow]});const slots=await(await page.request.get(`/api/intake/slots?facilityId=${f.id}&doctorId=${f.doctorIds[0]}&date=${tomorrow}`)).json();expect(slots.slots).toHaveLength(0);await ok(page.request,baseURL!,'/api/administration/facility',{...f,version:f.version+1});
});
test('surgery requires actual consent storage and matching eye before sequential progression',async({page,baseURL})=>{
 await loginAs(page.request,baseURL!,'sara.khan');const d=await(await page.request.get('/api/operations/surgery')).json();const theatre=d.facilities.find((f:{type:string})=>f.type==='theatre');expect(theatre).toBeTruthy();const c=await ok(page.request,baseURL!,'/api/operations/surgery',{action:'create',encounterId:d.encounters[0].id,facilityId:theatre.id,eye:'OD',procedure:'Synthetic cataract case',estimate:500000});const stage={action:'advance',id:c.id,version:1,stage:'consent',eye:'OD',notes:'Consent verified for synthetic case'};expect((await post(page.request,baseURL!,'/api/operations/surgery',stage)).status()).toBe(409);expect((await post(page.request,baseURL!,'/api/operations/surgery',{...stage,stage:'scheduled'})).status()).toBe(409);
 const file={name:'synthetic-consent.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6GtMAAAAASUVORK5CYII=','base64')};const uploaded=await page.request.post('/api/operations/consent',{headers:{Origin:baseURL!},multipart:{caseId:c.id,eye:'OD',witness:'Synthetic witness',file}});expect(uploaded.status(),await uploaded.text()).toBe(200);await ok(page.request,baseURL!,'/api/operations/surgery',stage);await ok(page.request,baseURL!,'/api/operations/surgery',{...stage,version:2,stage:'preop',notes:'Pre-operative clearance recorded'});const scheduled=new Date(Date.now()+86400000).toISOString();expect((await post(page.request,baseURL!,'/api/operations/surgery',{...stage,version:3,stage:'scheduled',eye:'OS',scheduled})).status()).toBe(409);await ok(page.request,baseURL!,'/api/operations/surgery',{...stage,version:3,stage:'scheduled',scheduled});await page.goto('/');await page.getByRole('button',{name:'Surgery lifecycle',exact:true}).click();await expect(page.getByRole('heading',{name:'Surgery cases',exact:true})).toBeVisible();await page.screenshot({path:'test-results/usable-surgery.png',fullPage:true});
});
test('live dashboards derive saved transactions and reports enforce roles',async({page,baseURL})=>{
 await loginAs(page.request,baseURL!,'omar.siddiqui');const d=await(await page.request.get('/api/operations/management')).json();expect(d.collections.some((x:{amount:number})=>x.amount>0)).toBe(true);for(const type of ['clinic','staff','cashier','dispensing','expiry']){const r=await page.request.get('/api/reports/'+type+'?date='+todayKarachi()+'&format=csv');expect(r.status(),await r.text()).toBe(200);expect(r.headers()['content-type']).toContain('text/csv');}await page.goto('/');await page.getByRole('button',{name:'Management',exact:true}).click();await expect(page.getByRole('heading',{name:'Collections in the last 30 days'})).toBeVisible();await page.screenshot({path:'test-results/usable-management.png',fullPage:true});await page.setViewportSize({width:820,height:1180});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'test-results/usable-management-tablet.png',fullPage:true});await loginAs(page.request,baseURL!,'aisha.malik');expect((await page.request.get('/api/reports/cashier')).status()).toBe(403);expect((await post(page.request,baseURL!,'/api/operations/inventory',{action:'drug',name:'Denied',strength:'1',therapyGroup:'test'})).status()).toBe(403);
});

test('walk-in arrival is atomic and the final queue closes only after pharmacy and billing settlement',async({page,baseURL})=>{
 const {id,patient}=await prepare(page.request,baseURL!);let detail=await saveEvent(page.request,baseURL!,id);detail=await signRecord(page.request,baseURL!,'event',detail.event);await ok(page.request,baseURL!,'/api/clinical/complete',{encounterId:id,version:detail.encounter.version});await loginAs(page.request,baseURL!,'aisha.malik');const queue=await(await page.request.get('/api/intake/queue')).json();const entry=queue.encounters.find((e:{id:string})=>e.id===id);expect(entry.stage).toBe('pharmacy_billing');await loginAs(page.request,baseURL!,'omar.siddiqui');const billing=await(await page.request.get('/api/operations/billing')).json();const service=billing.services.find((s:{active:boolean})=>s.active);const invoice=await ok(page.request,baseURL!,'/api/operations/billing',{action:'invoice',requestId:randomUUID(),encounterId:id,lines:[{serviceId:service.id,quantity:1,expectedPrice:service.price}],discount:0,reason:''});await loginAs(page.request,baseURL!,'aisha.malik');expect((await post(page.request,baseURL!,'/api/intake/queue-action',{id,version:entry.version,action:'completed',reason:'Attempt completion before settlement'})).status()).toBe(409);await loginAs(page.request,baseURL!,'imran.shah');await ok(page.request,baseURL!,'/api/operations/billing',{action:'open_session',facilityId:entry.facilityId,opening:0});await ok(page.request,baseURL!,'/api/operations/billing',{action:'payment',requestId:randomUUID(),invoiceId:invoice.id,amount:service.price,method:'welfare',reference:'Synthetic welfare authorisation'});const sessions=(await(await page.request.get('/api/operations/billing')).json()).sessions;await ok(page.request,baseURL!,'/api/operations/billing',{action:'close_session',sessionId:sessions.find((s:{closedAt:string|null})=>!s.closedAt).id,counted:0,reason:''});await loginAs(page.request,baseURL!,'aisha.malik');await ok(page.request,baseURL!,'/api/intake/queue-action',{id,version:entry.version,action:'completed',reason:'All recorded charges settled; no medication required'});expect((await(await page.request.get('/api/intake/queue')).json()).encounters.some((e:{id:string})=>e.id===id)).toBe(false);
 const clinics=(await(await page.request.get('/api/intake/clinics')).json()).clinics;const clinic=clinics[0];const suffix=String(Date.now()).slice(-7),input={givenName:'Walkin',familyName:'Validation'+suffix,gender:'male',dob:'1990-01-01',phone:'0300'+suffix,identifierType:'cnic',identifier:'00000'+suffix+'0'};const review=await(await post(page.request,baseURL!,'/api/patients/duplicates',input)).json();const registered=await ok(page.request,baseURL!,'/api/patients',{...input,duplicateReviewToken:review.reviewToken});const walk={patientId:registered.patient.id,facilityId:clinic.id,doctorId:clinic.doctors[0].id};const arrival=await ok(page.request,baseURL!,'/api/intake/walkin',walk);expect(arrival.id).toBeTruthy();expect((await post(page.request,baseURL!,'/api/intake/walkin',walk)).status()).toBe(409);await ok(page.request,baseURL!,'/api/intake/transition',{encounterId:arrival.id,version:1,to:'workup'});await loginAs(page.request,baseURL!,'nadia.raza');const eye={uncorrected:'6/12',pinhole:'6/9',corrected:'6/6',iop:16,method:'NCT',measuredAt:new Date().toISOString(),refraction:{sphere:-1.25,cylinder:-0.5,axis:90,add:1.5,pd:32},logmar:{uncorrected:0.3,pinhole:0.18,corrected:0}};const saved=await ok(page.request,baseURL!,'/api/intake/workup',{encounterId:arrival.id,version:0,OD:eye,OS:eye,notes:'Synthetic refraction and logMAR verification'});expect(saved.workup.OD.refraction.axis).toBe(90);expect(saved.workup.OS.logmar.uncorrected).toBe(0.3);expect((await post(page.request,baseURL!,'/api/intake/workup',{encounterId:arrival.id,version:1,OD:{...eye,refraction:{...eye.refraction,cylinder:1}},OS:eye,notes:''})).status()).toBe(400);
});
test('identity corrections stay encrypted, reject duplicates and preserve the MRN',async({page,baseURL})=>{await loginAs(page.request,baseURL!,'aisha.malik');const people=(await(await post(page.request,baseURL!,'/api/patients/search',{query:'',page:1})).json()).patients;const p=(await(await page.request.get('/api/patients/'+people[0].id)).json()).patient;const body={version:p.version,givenName:p.givenName,familyName:p.familyName,gender:p.gender,dob:p.dob,dobEstimated:p.dobEstimated,phone:p.phone,city:p.city,address:p.address,preferredLanguage:p.preferredLanguage,nextOfKinName:p.nextOfKinName,nextOfKinPhone:p.nextOfKinPhone,reason:'Identity checked against replacement document',identifierType:'passport',identifier:'TEST'+Date.now().toString().slice(-9)};await ok(page.request,baseURL!,'/api/patients/'+p.id,body);const updated=(await(await page.request.get('/api/patients/'+p.id)).json()).patient;expect(updated.mrn).toBe(p.mrn);expect(updated.identifierMasked.endsWith(body.identifier.slice(-4))).toBe(true);expect(JSON.stringify(updated)).not.toContain(body.identifier);const summary=await page.request.get('/patients/'+p.id+'/summary');expect(summary.status()).toBe(200);expect(await summary.text()).not.toContain(body.identifier);});
