import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { canonicalJson,contentHash } from '../src/server/clinical-hash';
import { EMPTY_DRAWINGS,eventInputSchema,rxInputSchema,prescriptionWarnings,type RxItem } from '../src/lib/clinical';
import { ROLE_PERMISSIONS } from '../src/lib/access';
test('content hashes are independent of object insertion order but preserve laterality and row order',()=>{assert.equal(contentHash({a:1,b:{x:'OD',y:2}}),contentHash({b:{y:2,x:'OD'},a:1}));assert.notEqual(contentHash({eye:'OD'}),contentHash({eye:'OS'}));assert.notEqual(contentHash(['OD','OS']),contentHash(['OS','OD']));assert.equal(canonicalJson({when:new Date('2026-09-14T00:00:00Z')}),'{"when":"2026-09-14T00:00:00.000Z"}');});
test('event validation rejects missing laterality, duplicate anatomy pairs and injected signing fields',()=>{const plan={id:randomUUID(),eye:'OD',anatomySite:'optic_nerve',intent:'observation',notes:''};const input={encounterId:randomUUID(),version:0,complaint:'Demo',findings:{OD:'Right',OS:'Left'},diagnoses:[{eye:'OU',label:'Demo diagnosis'}],plans:[plan],referral:'',followUp:'',drawings:structuredClone(EMPTY_DRAWINGS)};assert.equal(eventInputSchema.safeParse(input).success,true);assert.equal(eventInputSchema.safeParse({...input,status:'signed'}).success,false);assert.equal(eventInputSchema.safeParse({...input,plans:[plan,{...plan,id:randomUUID()}]}).success,false);assert.equal(eventInputSchema.safeParse({...input,diagnoses:[{label:'Missing eye'}]}).success,false);});
const item:RxItem={id:randomUUID(),drugId:randomUUID(),name:'Example',strength:'Demo',eye:'OD',dose:'Demo dose',route:'Demo route',frequency:'Demo frequency',duration:'Demo duration',instructions:'',instructionsUr:'صرف نمونہ'};
test('prescription entry requires explicit medication directions and preserves Urdu text',()=>{const data={encounterId:randomUUID(),version:0,items:[item]};assert.equal(rxInputSchema.parse(data).items[0].instructionsUr,item.instructionsUr);assert.equal(rxInputSchema.safeParse({...data,items:[{...item,dose:''}]}).success,false);assert.equal(rxInputSchema.safeParse({...data,signedBy:randomUUID()}).success,false);});
test('warning review differentiates separate eyes from overlapping duplicate therapy',()=>{assert.deepEqual(prescriptionWarnings([item,{...item,id:randomUUID(),eye:'OS'}],[]),[]);assert.deepEqual(prescriptionWarnings([item,{...item,id:randomUUID(),eye:'OU'}],[]),['duplicateTherapyReview']);assert.deepEqual(prescriptionWarnings([{...item,drugId:null}],[{type:'allergy',value:'Needs reconciliation'}]),['allergyReview','nonFormularyReview']);});
test('prescribing and signing are restricted to doctors and retired pharmacy access is empty',()=>{for(const role of ['receptionist','nurse','hospital_admin','pharmacist'] as const)assert.equal(ROLE_PERMISSIONS[role].includes('clinical:sign'),false);assert.ok(ROLE_PERMISSIONS.doctor.includes('clinical:sign'));assert.deepEqual(ROLE_PERMISSIONS.pharmacist,[]);});

test('clinical drawings validate bounded stylus paths and reject injected SVG content',()=>{const valid=structuredClone(EMPTY_DRAWINGS);valid.OD.strokes.push({id:randomUUID(),color:'#7f1d1d',width:6,points:[[10,20],[30,40]]});const base={encounterId:randomUUID(),version:0,complaint:'Demo',findings:{OD:'Right',OS:'Left'},diagnoses:[{eye:'OU',label:'Demo'}],plans:[],referral:'',followUp:'',drawings:valid};assert.equal(eventInputSchema.safeParse(base).success,true);assert.equal(eventInputSchema.safeParse({...base,drawings:{...valid,OD:{...valid.OD,strokes:[{...valid.OD.strokes[0],color:'url(javascript:bad)'}]}}}).success,false);assert.equal(eventInputSchema.safeParse({...base,drawings:{...valid,OS:{...valid.OS,template:'uploaded-html'}}}).success,false);});
