import pg from 'pg';
import {randomUUID} from 'node:crypto';
import {assertDemoDatabase} from './env';
async function main(){const db=new pg.Client({connectionString:assertDemoDatabase().toString()});await db.connect();try{await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock(724912010)');const tenant=(await db.query("SELECT id FROM app.tenant WHERE code='DEMO' AND is_demo")).rows[0];if(!tenant)throw new Error('A synthetic demo tenant is required');const tid=tenant.id;if((await db.query("SELECT 1 FROM app.audit_log WHERE tenant_id=$1 AND action='operations.synthetic_opening_seed'",[tid])).rowCount){await db.query('COMMIT');console.log('Existing live operations opening data preserved.');return;}
 await db.query("INSERT INTO app.user_facility(tenant_id,user_id,facility_id) SELECT $1,u.id,f.id FROM app.user_account u JOIN app.user_role r ON r.user_id=u.id AND r.tenant_id=u.tenant_id JOIN app.facility f ON f.tenant_id=u.tenant_id WHERE u.tenant_id=$1 AND (r.role_code IN ('hospital_admin','auditor','inventory_officer') OR (r.role_code IN ('doctor','nurse') AND f.type='theatre') OR (r.role_code='cashier' AND f.type='clinic')) ON CONFLICT DO NOTHING",[tid]);
 const actor=(await db.query("SELECT id FROM app.user_account WHERE tenant_id=$1 AND email='hina.aslam@demo.openeyes.local'",[tid])).rows[0].id,pharmacy=(await db.query("SELECT id FROM app.facility WHERE tenant_id=$1 AND type='pharmacy'",[tid])).rows[0].id,drugs=(await db.query('SELECT id FROM app.formulary WHERE tenant_id=$1 ORDER BY name',[tid])).rows;
 for(const [index,drug] of drugs.entries()){const expiry=new Date(Date.now()+180*86400000).toISOString().slice(0,10);const batch=(await db.query("INSERT INTO app.stock_batch(tenant_id,facility_id,drug_id,batch_number,expiry,unit_cost_paisa) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING RETURNING id",[tid,pharmacy,drug.id,'SYNTHETIC-OPENING-'+(index+1),expiry,25000+index*5000])).rows[0];if(batch)await db.query("INSERT INTO app.stock_movement(tenant_id,batch_id,quantity,kind,reason,actor_id,request_id) VALUES($1,$2,30,'receipt','Synthetic opening stock for testing',$3,$4)",[tid,batch.id,actor,randomUUID()]);await db.query('INSERT INTO app.stock_threshold(tenant_id,facility_id,drug_id,minimum) VALUES($1,$2,$3,10) ON CONFLICT DO NOTHING',[tid,pharmacy,drug.id]);}
 for(const [name,category,price] of [['Consultation','consultation',150000],['OCT investigation','investigation',400000],['Cataract procedure','procedure',4500000],['Optical service','optical',250000],['Pharmacy supply','pharmacy',50000]])await db.query('INSERT INTO app.service_catalogue(tenant_id,name,category,price_paisa) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[tid,name,category,price]);
 await db.query("INSERT INTO app.audit_log(tenant_id,actor_id,action,entity_type,metadata) VALUES($1,$2,'operations.synthetic_opening_seed','operations',$3)",[tid,actor,JSON.stringify({synthetic:true,stockItems:drugs.length})]);await db.query('COMMIT');console.log('Added synthetic opening stock, service prices, and operational facility assignments. Existing patient and financial records preserved.');}catch(e){await db.query('ROLLBACK');throw e;}finally{await db.end();}}
main().catch(e=>{console.error('Live operations seed failed:',e.code||e.message);process.exitCode=1;});
