"use client";
import {useState} from 'react';
import {useSession} from '../session-provider';
import {ActionForm,LiveHeading,Table,useOperations,pkr,choice,reasonField,moneyField,number,amount,type Facility} from './live-shared';
import {invoiceTotal,type SampleInvoice} from '@/lib/operations';
import type {MessageKey} from '@/lib/messages';
import {useLocale} from '../locale-provider';
import {money} from './shared';
type Service={id:string;name:string;category:string;price:number;active:boolean;version:number};
type Billing={facilities:Facility[];services:Service[];encounters:{id:string;patient:string;mrn:string;clinic:string;date:string;facilityId:string}[];invoices:{id:string;patient:string;mrn:string;date:string;total:number;discount:number;paid:number;refunded:number;facilityId:string;lines:{description:string;quantity:number;price:number}[]}[];payments:{id:string;invoiceId:string;amount:number;method:string;receipt:string;at:string}[];sessions:{id:string;cashierId:string;cashier:string;facilityId:string;opening:number;openedAt:string;closedAt:string|null;counted:number|null;expected:number|null;currentExpected:number;reason:string|null}[];refunds:{id:string;paymentId:string;amount:number;reason:string;requestedBy:string;approvedAt:string|null}[]};
export function BillingWorkspace(){const {t}=useLocale();const user=useSession(),live=useOperations<Billing>('billing'),[lines,setLines]=useState<{serviceId:string;quantity:number}[]>([{serviceId:'',quantity:1}]),[editing,setEditing]=useState<Service|null>(null);if(!live.data)return <LiveHeading {...live}/>;const d=live.data,write=user.permissions.includes('billing:write'),discount=user.permissions.includes('billing:discount'),settings=user.permissions.includes('settings:write'),facilities=d.facilities.map(f=>({value:f.id,label:f.name})),session=d.sessions.find(s=>s.cashierId===user.id&&!s.closedAt);const serviceFields=[{name:'name',label:'billServiceName' as const,value:editing?.name},choice('category','billCategory',['consultation','procedure','investigation','optical','pharmacy'].map(value=>({value,label:t(`serviceCat_${value}` as MessageKey)}))),{...moneyField('price','billPrice'),value:editing?editing.price/100:undefined},choice('active','billStatus',[{value:'true',label:t('billActive')},{value:'false',label:t('billInactive')}])];
 return <div className="ops-workspace"><LiveHeading {...live}/><div className="ops-metrics"><article className="panel"><span>{t('billOutstanding')}</span><strong>{pkr(d.invoices.reduce((n,i)=>n+i.total-i.paid+i.refunded,0))}</strong></article><article className="panel"><span>{t('billYourSession')}</span><strong>{t(session?'billSessionOpen':'billSessionClosed')}</strong><small>{session?`Expected cash ${pkr(session.currentExpected)}`:t('billOpenSessionHint')}</small></article></div>
 {write&&!session&&<ActionForm title="billOpenSession" resource="billing" fields={[choice('facilityId','billFacility',facilities),moneyField('opening','billOpeningFloat')]} onSaved={live.refresh} body={f=>({action:'open_session',facilityId:f.get('facilityId'),opening:amount(f,'opening')})}/>}{write&&session&&<ActionForm title="billCloseSession" resource="billing" fields={[moneyField('counted','billCountedCash'),{...reasonField,label:'billVarianceExplain' as const,optional:true}]} onSaved={live.refresh} body={f=>({action:'close_session',sessionId:session.id,counted:amount(f,'counted'),reason:f.get('reason')||''})}><p>Expected cash: {pkr(session.currentExpected)}. Saving closes this session and records the variance.</p></ActionForm>}
 {(write||discount)&&<ActionForm title="billIssueInvoice" resource="billing" onSaved={live.refresh} fields={[choice('encounterId','billPatientEncounter',d.encounters.map(e=>({value:e.id,label:e.patient+' / '+e.mrn+' / '+e.clinic+' / '+new Date(e.date).toLocaleDateString()}))),...(discount?[moneyField('discount','billDiscount',true),{...reasonField,label:'billDiscountReason' as const,optional:true}]:[])]} body={(f,requestId)=>({action:'invoice',requestId,encounterId:f.get('encounterId'),lines:lines.map(l=>({...l,expectedPrice:d.services.find(s=>s.id===l.serviceId)?.price??-1})),discount:discount?amount(f,'discount'):0,reason:String(f.get('reason')||'')})}><div className="admin-form"><h3>{t('billInvoiceLines')}</h3>{lines.map((l,index)=><div className="admin-grid" key={index}><label>{t('billService')}<select required value={l.serviceId} onChange={e=>setLines(values=>values.map((v,i)=>i===index?{...v,serviceId:e.target.value}:v))}><option value="">{t('billChooseService')}</option>{d.services.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name} / {pkr(s.price)}</option>)}</select></label><label>{t('billQuantity')}<input type="number" min={1} max={10000} step={1} required value={l.quantity} onChange={e=>setLines(values=>values.map((v,i)=>i===index?{...v,quantity:Number(e.target.value)}:v))}/></label><button type="button" className="text-button" disabled={lines.length===1} onClick={()=>setLines(values=>values.filter((_,i)=>i!==index))}>{t('billRemoveLine')}</button></div>)}<button type="button" className="secondary-button" disabled={lines.length>=30} onClick={()=>setLines(v=>[...v,{serviceId:'',quantity:1}])}>{t('billAddLine')}</button><strong>Subtotal: {pkr(lines.reduce((n,l)=>n+(d.services.find(s=>s.id===l.serviceId)?.price||0)*l.quantity,0))}</strong></div></ActionForm>}
 <section className="panel ops-chart-panel"><h2>{t('billInvoices')}</h2>{!d.invoices.length&&<p>{t('billNoInvoices')}</p>}{d.invoices.map(i=><details key={i.id} className="ops-daily-table"><summary>{i.patient} / {i.mrn} / {pkr(i.total)} / Outstanding {pkr(i.total-i.paid+i.refunded)}</summary><Table heads={['billService','billQuantity','billUnitPrice']}>{i.lines.map((l,n)=><tr key={n}><td>{l.description}</td><td>{l.quantity}</td><td>{pkr(l.price)}</td></tr>)}</Table><p>Discount: {pkr(i.discount)} / Paid: {pkr(i.paid)} / Refunded: {pkr(i.refunded)}</p>{write&&i.total-i.paid+i.refunded>0&&<ActionForm title="billRecordPayment" resource="billing" onSaved={live.refresh} fields={[{...moneyField('amount','billPaymentAmount'),max:(i.total-i.paid+i.refunded)/100,min:.01},choice('method','billPaymentMethod',['cash','card','bank_transfer','welfare'].map(value=>({value,label:t(`payMethod_${value}` as MessageKey)}))),{name:'reference',label:'billPaymentReference' as const,optional:true}]} body={(f,requestId)=>({action:'payment',requestId,invoiceId:i.id,amount:amount(f,'amount'),method:f.get('method'),reference:f.get('reference')||''})}/>}{d.payments.filter(p=>p.invoiceId===i.id).map(p=><div className="ops-record-summary" key={p.id}><p>{pkr(p.amount)} / {p.method} / {new Date(p.at).toLocaleString()}</p><a className="text-button" href={'/receipts/'+p.id} target="_blank" rel="noreferrer">{t('billPrintReceipt')}</a>{write&&<ActionForm title="billRequestRefund" resource="billing" onSaved={live.refresh} fields={[moneyField('amount','billRefundAmount'),reasonField]} body={f=>({action:'refund',paymentId:p.id,amount:amount(f,'amount'),reason:f.get('reason')})}/>}</div>)}</details>)}</section>
 <section className="panel ops-chart-panel"><h2>{t('billRefundApprovals')}</h2>{!d.refunds.length&&<p>{t('billNoRefunds')}</p>}{d.refunds.map(r=><article className="ops-record-summary" key={r.id}><p>{pkr(r.amount)} / {r.reason} / {r.approvedAt?'Approved':'Awaiting a second approver'}</p>{!r.approvedAt&&r.requestedBy!==user.id&&user.permissions.includes('billing:approve_refund')&&<ActionForm title="billApproveRefund" resource="billing" fields={[]} body={()=>({action:'approve_refund',refundId:r.id})} onSaved={live.refresh}/>}</article>)}</section>
 <section className="panel ops-chart-panel"><h2>{t('billReconciliation')}</h2><Table heads={['billCashier','billOpened','billStatus','billExpected','billCounted','billVariance']}>{d.sessions.map(s=><tr key={s.id}><td>{s.cashier}</td><td>{new Date(s.openedAt).toLocaleString()}</td><td>{s.closedAt?'Closed':'Open'}</td><td>{pkr(s.expected??s.currentExpected)}</td><td>{s.counted===null?'?':pkr(s.counted)}</td><td>{s.closedAt?pkr((s.counted??0)-(s.expected??0)):'?'}<small>{s.reason}</small></td></tr>)}</Table></section>
 <section className="panel ops-chart-panel"><h2>{t('billCatalogue')}</h2><Table heads={['billService','billCategory','billPrice','billStatus','billAction']}>{d.services.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.category}</td><td>{pkr(s.price)}</td><td>{s.active?'Active':'Inactive'}</td><td>{settings&&<button className="text-button" onClick={()=>setEditing(s)}>{t('billEditService')}</button>}</td></tr>)}</Table>{settings&&<><button className="text-button" onClick={()=>setEditing(null)}>{t('billNewService')}</button><ActionForm key={editing?.id||'new'} title={editing?'billUpdateService':'billAddService'} resource="billing" fields={serviceFields.map(f=>f.name==='category'?{...f,value:editing?.category}:f.name==='active'?{...f,value:String(editing?.active??true)}:f)} onSaved={live.refresh} body={f=>({action:'service',...(editing?{id:editing.id,version:editing.version}:{}),name:f.get('name'),category:f.get('category'),price:amount(f,'price'),active:f.get('active')==='true'})}/></>}</section></div>;
}

// Read-only invoice breakdown, shared with the printable sample receipt.
// Sample-fixture amounts are plain currency units, so they use money() rather
// than pkr(), which converts from paisa for the live billing tables above.
export function InvoiceLines({invoice}:{invoice:SampleInvoice}){
 const {t}=useLocale();
 return <section className="ops-invoice-lines"><Table heads={['opsLineItem','opsQuantity','opsUnitPrice','opsAmount']}>{invoice.items.map((item,index)=><tr key={index}><td>{item.description}</td><td>{item.quantity}</td><td>{money(item.unitPrice)}</td><td>{money(item.quantity*item.unitPrice)}</td></tr>)}</Table><p className="ops-invoice-total"><span>{t('opsBilled')}</span><strong>{money(invoiceTotal(invoice))}</strong></p></section>;
}
