'use client';

import { useState } from 'react';
import type { AdministrationData, ClinicalOutcomeRecord } from '@/lib/administration';

export function ClinicalOutcomeAdministration({data,busy,canWrite,save}:{data:AdministrationData;busy:boolean;canWrite:boolean;save:(resource:string,body:unknown)=>Promise<void>}){
 const [editing,setEditing]=useState<Partial<ClinicalOutcomeRecord>|null>(null);
 return <section className="panel"><div className="registry-heading"><div><h2>Clinical outcomes</h2><p className="admin-note">Configure the visit dispositions doctors select before signing. Signed Doctor Events keep the original code and label.</p></div>{canWrite&&<button type="button" className="primary-button" onClick={()=>setEditing({version:0,active:true,requiresRecall:false,requiresNotes:false,displayOrder:100})}>Add outcome</button>}</div>
 <div className="patient-table-wrap"><table className="patient-table"><thead><tr><th>Outcome</th><th>Requirements</th><th>Order</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.clinicalOutcomes.map(item=><tr key={item.id}><td><strong>{item.label}</strong><small>{item.code}</small></td><td>{[item.requiresRecall?'Recall date':null,item.requiresNotes?'Management notes':null].filter(Boolean).join(', ')||'No extra fields'}</td><td>{item.displayOrder}</td><td>{item.active?'Active':'Inactive'}</td><td>{canWrite&&<button type="button" className="text-button" onClick={()=>setEditing(item)}>Edit</button>}</td></tr>)}</tbody></table></div>
 {editing&&<form className="admin-form" onSubmit={event=>{event.preventDefault();const values=new FormData(event.currentTarget);void save('outcomes',{...(editing.id?{id:editing.id}:{}),version:editing.version??0,code:values.get('code'),label:values.get('label'),active:values.get('active')==='on',requiresRecall:values.get('requiresRecall')==='on',requiresNotes:values.get('requiresNotes')==='on',displayOrder:Number(values.get('displayOrder'))}).then(()=>setEditing(null));}}><h3>{editing.id?'Edit clinical outcome':'Add clinical outcome'}</h3><div className="admin-grid"><label>Stable code<input name="code" required pattern="[a-z][a-z0-9_]{1,59}" defaultValue={editing.code||''} readOnly={!!editing.id}/></label><label>Display label<input name="label" required minLength={2} maxLength={120} defaultValue={editing.label||''}/></label><label>Display order<input name="displayOrder" type="number" min={0} max={1000} required defaultValue={editing.displayOrder??100}/></label></div><div className="admin-grid"><label className="admin-check"><input name="active" type="checkbox" defaultChecked={editing.active??true}/>Available to doctors</label><label className="admin-check"><input name="requiresRecall" type="checkbox" defaultChecked={editing.requiresRecall??false}/>Require recall date</label><label className="admin-check"><input name="requiresNotes" type="checkbox" defaultChecked={editing.requiresNotes??false}/>Require management notes</label></div><div className="admin-actions"><button className="primary-button" disabled={busy}>Save outcome</button><button type="button" className="secondary-button" onClick={()=>setEditing(null)}>Cancel</button></div></form>}
 </section>;
}
