"use client";
import {useState} from 'react';
import {useSession} from '../session-provider';
import {todayKarachi} from '@/lib/patients';
import type {Stock,stockSummary} from '@/lib/operations';
import {useLocale} from '../locale-provider';
import {SampleBanner,usePreview} from './shared';
import {ActionForm,LiveHeading,Table,useOperations,pkr,choice,quantityField,reasonField,moneyField,number,amount,type Facility} from './live-shared';
type Inventory={facilities:Facility[];drugs:{id:string;name:string;strength:string;active:boolean}[];batches:{id:string;facilityId:string;facility:string;drugId:string;name:string;strength:string;batch:string;expiry:string;unitCost:number;quantity:number;quarantined:boolean}[];thresholds:{facilityId:string;drugId:string;minimum:number}[];prescriptions:{id:string;patient:string;mrn:string;date:string;closed:boolean;items:{id:string;drugId:string|null;name:string;strength:string;eye:string;quantity:number|null;dispensed:number}[]}[]};
export function PharmacyWorkspace(){const {t}=useLocale();const user=useSession(),live=useOperations<Inventory>('inventory'),[query,setQuery]=useState('');if(!live.data)return <LiveHeading {...live}/>;const d=live.data,facilities=d.facilities.map(f=>({value:f.id,label:f.name})),drugs=d.drugs.filter(f=>f.active).map(f=>({value:f.id,label:f.name+' '+f.strength})),batches=d.batches.map(b=>({value:b.id,label:`${b.name} / ${b.batch} / ${b.facility} (${b.quantity})`})),today=todayKarachi(),horizon=new Date(Date.parse(today)+90*86400000).toISOString().slice(0,10),write=user.permissions.includes('inventory:write');const low=d.thresholds.filter(t=>d.batches.filter(b=>b.facilityId===t.facilityId&&b.drugId===t.drugId&&!b.quarantined&&b.expiry>=today).reduce((n,b)=>n+b.quantity,0)<t.minimum);
 return <div className="ops-workspace"><LiveHeading {...live}/><div className="ops-metrics"><article className="panel"><span>{t('pharStockValue')}</span><strong>{pkr(d.batches.reduce((n,b)=>n+b.quantity*b.unitCost,0))}</strong></article><article className="panel"><span>{t('pharLowAlerts')}</span><strong>{low.length}</strong></article><article className="panel"><span>{t('pharExpiring90')}</span><strong>{d.batches.filter(b=>b.quantity>0&&b.expiry>=today&&b.expiry<=horizon).length}</strong></article></div>{low.length>0&&<section className="panel ops-chart-panel"><h2>{t('pharDailyAlerts')}</h2>{low.map(item=><p key={item.facilityId+item.drugId}>{d.drugs.find(x=>x.id===item.drugId)?.name} / {d.facilities.find(f=>f.id===item.facilityId)?.name} / {t('pharBelow')} {item.minimum} {t('pharUnitsSuffix')}</p>)}</section>}
 <section className="panel"><div className="registry-heading"><h2>{t('pharBatchStock')}</h2><input aria-label={t('pharSearchStock')} placeholder={t('pharSearchPlaceholder')} value={query} onChange={e=>setQuery(e.target.value)}/></div><Table heads={['pharMedicine','pharFacilityBatch','pharExpiry','pharAvailableUnits','pharUnitCost','pharStatus']}>{d.batches.filter(b=>(b.name+' '+b.batch).toLowerCase().includes(query.toLowerCase())).map(b=><tr key={b.id}><td>{b.name}<small>{b.strength}</small></td><td>{b.facility}<small>{b.batch}</small></td><td>{b.expiry}</td><td>{b.quantity}</td><td>{pkr(b.unitCost)}</td><td>{t(b.quarantined?'pharQuarantined':b.expiry<today?'pharExpired':b.expiry<=horizon?'pharExpiresSoon':'pharAvailable')}</td></tr>)}</Table>{!d.batches.length&&<p className="intake-empty">{t('pharEmptyStock')}</p>}</section>
 {write&&<><ActionForm title="pharReceiveStock" resource="inventory" onSaved={live.refresh} fields={[choice('facilityId','pharFacility',facilities),choice('drugId','pharMedicineField',drugs),{name:'batch',label:'pharBatchNumber' as const},{name:'expiry',label:'pharExpiryDate' as const,type:'date' as const},quantityField,moneyField('unitCost','pharCostPerUnit'),reasonField]} body={(f,requestId)=>({action:'receipt',requestId,facilityId:f.get('facilityId'),drugId:f.get('drugId'),batch:f.get('batch'),expiry:f.get('expiry'),quantity:number(f,'quantity'),unitCost:amount(f,'unitCost'),reason:f.get('reason')})}/>
 <ActionForm title="pharAdjustStock" resource="inventory" onSaved={live.refresh} fields={[choice('batchId','pharBatch',batches),{name:'quantity',label:'pharAdjustment' as const,type:'number' as const,min:-10000,max:10000,step:1},reasonField]} body={(f,requestId)=>({action:'adjust',requestId,batchId:f.get('batchId'),quantity:number(f,'quantity'),reason:f.get('reason')})}/>
 <ActionForm title="pharTransferStock" resource="inventory" onSaved={live.refresh} fields={[choice('batchId','pharSourceBatch',batches),choice('facilityId','pharDestFacility',facilities),quantityField,reasonField]} body={(f,requestId)=>({action:'transfer',requestId,batchId:f.get('batchId'),facilityId:f.get('facilityId'),quantity:number(f,'quantity'),reason:f.get('reason')})}/>
 <ActionForm title="pharSetQuarantine" resource="inventory" onSaved={live.refresh} fields={[choice('batchId','pharBatch',batches),choice('quarantined','pharStatusField',[{value:'true',label:t('pharQuarantined')},{value:'false',label:t('pharAvailable')}]),reasonField]} body={f=>({action:'quarantine',batchId:f.get('batchId'),quarantined:f.get('quarantined')==='true',reason:f.get('reason')})}/>
 <ActionForm title="pharSetThreshold" resource="inventory" onSaved={live.refresh} fields={[choice('facilityId','pharFacility',facilities),choice('drugId','pharMedicineField',drugs),{name:'minimum',label:'pharMinimumUnits' as const,type:'number' as const,min:0,max:100000,step:1}]} body={f=>({action:'threshold',facilityId:f.get('facilityId'),drugId:f.get('drugId'),minimum:number(f,'minimum')})}/>
 <ActionForm title="pharAddDrug" resource="inventory" onSaved={live.refresh} fields={[{name:'name',label:'pharDrugName' as const},{name:'strength',label:'pharStrength' as const},{name:'therapyGroup',label:'pharTherapyGroup' as const}]} body={f=>({action:'drug',...Object.fromEntries(f)})}/></>}
 {user.permissions.includes('pharmacy:dispense')&&<section className="panel ops-chart-panel"><h2>{t('pharDispensing')}</h2><p>{t('pharDispensingNote')}</p>{d.prescriptions.map(rx=><details key={rx.id} className="ops-daily-table"><summary>{rx.patient} / {rx.mrn} / {t(rx.closed?'pharRxClosed':rx.items.every(i=>i.quantity!==null&&i.dispensed>=i.quantity)?'pharRxFullyDispensed':'pharRxOpen')}</summary>{rx.items.map(i=><div key={i.id}><p><strong>{i.name} {i.strength} / {i.eye}</strong> / {i.dispensed} / {i.quantity??t('pharQuantityUnspecified')}</p>{!rx.closed&&i.quantity&&i.drugId&&i.dispensed<i.quantity&&<ActionForm title="pharDispense" resource="dispensing" onSaved={live.refresh} fields={[choice('facilityId','pharDispensingFacility',facilities),{...quantityField,max:i.quantity-i.dispensed},choice('batchId','pharBatchOverride',d.batches.filter(b=>b.drugId===i.drugId&&b.quantity>0&&!b.quarantined&&b.expiry>=today).map(b=>({value:b.id,label:b.facility+' / '+b.batch+' / '+b.expiry})),true),{...reasonField,label:'pharOverrideReason' as const,optional:true}]} body={(f,requestId)=>({action:'dispense',requestId,itemId:i.id,facilityId:f.get('facilityId'),quantity:number(f,'quantity'),...(f.get('batchId')?{batchId:f.get('batchId')}:{}),reason:f.get('reason')||''})}/>}</div>)}{!rx.closed&&<ActionForm title="pharClosePrescription" resource="dispensing" fields={[reasonField]} onSaved={live.refresh} body={f=>({action:'close',prescriptionId:rx.id,reason:f.get('reason')})}/>}</details>)}</section>}
 </div>;
}

// Read-only companion to the prescription record. Deliberately narrow: it matches
// on exact formulary ID and shows the first-expiry batch, with no substitution and
// no dose or quantity arithmetic. Callers gate this on the preview:inventory
// permission; stock comes from the current facility ledger.
export function PrescriptionBatchSuggestions({drugIds}:{drugIds:(string|null)[]}){
 const {t}=useLocale(),live=useOperations<Inventory>('inventory');const wanted=drugIds.filter((id):id is string=>!!id);if(!live.data||!wanted.length)return null;const today=todayKarachi();const matches=live.data.batches.filter(b=>wanted.includes(b.drugId)&&b.quantity>0&&!b.quarantined&&b.expiry>=today).sort((a,b)=>a.expiry.localeCompare(b.expiry));
 return <section className="ops-rx-batches"><h3>{t('opsRxBatchTitle')}</h3><p>{t('opsRxBatchNote')}</p>{matches.length?<Table heads={['opsDrug','opsSuggested','opsExpiry','opsAvailable']}>{matches.map(b=><tr key={b.id}><td>{b.name}<small>{b.strength}</small></td><td>{b.batch}<small>{b.facility}</small></td><td>{b.expiry}</td><td>{b.quantity}</td></tr>)}</Table>:<p className="intake-empty">{t('opsNoBatch')}</p>}</section>;
}
