"use client";
import {useState} from 'react';
import {useLocale} from '../locale-provider';
import {LiveHeading,Table,useOperations,pkr} from './live-shared';
import type {MessageKey} from '@/lib/messages';
function DailyChart({ values, label, format }: { values: { date: string; value: number }[]; label: string; format: (value: number) => string }) {
  const [hovered, setHovered] = useState<number | null>(null); const selected = values[Math.min(hovered ?? values.length - 1, values.length - 1)], max = Math.max(1, ...values.map(item => item.value));
  return <div className="ops-chart"><div className="ops-chart-reading" aria-live="polite"><span>{selected?.date}</span><strong>{format(selected?.value ?? 0)}</strong></div><div className="ops-bars" role="group" aria-label={label}>{values.map((item, index) => <button type="button" key={item.date} className={selected?.date === item.date ? 'selected' : ''} style={{ height: `${Math.max(2, item.value / max * 100)}%` }} aria-label={`${item.date}: ${format(item.value)}`} title={`${item.date}: ${format(item.value)}`} onFocus={() => setHovered(index)} onMouseEnter={() => setHovered(index)} onClick={() => setHovered(index)}/>)}</div><div className="ops-chart-axis"><span>{values[0]?.date}</span><span>{values.at(-1)?.date}</span></div></div>;
}

type Management={lowStock:number;refunds:number;date:string;asOf:string;bookings:{total:number;attended:number;cancelled:number;missed:number};collections:{date:string;method:string;amount:number}[];outstanding:number;inventory:{value:number;expired:number};surgery:{stage:string;count:number}[];documentation:{visits:number;signed:number};waits:{stage:string;minutes:number}[]};
export function ManagementWorkspace({navigate}:{navigate:(page:'billing'|'surgery'|'overview')=>void}){const {t}=useLocale(),live=useOperations<Management>('management');if(!live.data)return <LiveHeading {...live}/>;const d=live.data,daily=Array.from(new Set(d.collections.map(c=>c.date))).map(date=>({date,value:d.collections.filter(c=>c.date===date).reduce((n,c)=>n+c.amount,0)}));return <div className="ops-workspace"><LiveHeading {...live}/><div className="ops-metrics">{([{label:'dashBookings',value:d.bookings.total},{label:'dashAttended',value:d.bookings.attended},{label:'dashCancelled',value:d.bookings.cancelled},{label:'dashMissed',value:d.bookings.missed},{label:'dashOutstanding',value:pkr(d.outstanding)},{label:'dashStock',value:pkr(d.inventory.value)},{label:'dashLowStock',value:d.lowStock},{label:'dashRefunds',value:pkr(d.refunds)},{label:'dashDocumentation',value:`${d.documentation.signed} / ${d.documentation.visits}`} ] as {label:MessageKey;value:string|number}[]).map(m=><article className="panel" key={m.label}><span>{t(m.label)}</span><strong>{m.value}</strong></article>)}</div><div className="ops-chart-grid"><section className="panel ops-chart-panel"><h2>{t('dashCollections')}</h2>{daily.length?<DailyChart values={daily} label={t('dashCollections')} format={pkr}/>:<p>{t('dashEmpty')}</p>}<Table heads={['dashDate','dashMethod','dashAmount']}>{d.collections.map((c,i)=><tr key={i}><td>{c.date}</td><td>{c.method}</td><td>{pkr(c.amount)}</td></tr>)}</Table></section><section className="panel ops-chart-panel"><h2>{t('dashWait')}</h2><Table heads={['dashStage','dashMinutes']}>{d.waits.map(w=><tr key={w.stage}><td>{w.stage}</td><td>{w.minutes}</td></tr>)}</Table></section></div><section className="panel ops-chart-panel"><h2>{t('dashPipeline')}</h2><Table heads={['dashStage','dashCount']}>{d.surgery.map(s=><tr key={s.stage}><td>{s.stage}</td><td>{s.count}</td></tr>)}</Table></section><div className="admin-actions"><button className="secondary-button" onClick={()=>navigate('billing')}>{t('opsViewBilling')}</button><button className="secondary-button" onClick={()=>navigate('surgery')}>{t('opsViewSurgery')}</button></div></div>;}
