"use client";
import {useState} from 'react';
import {useSession} from '../session-provider';
import {useLocale} from '../locale-provider';
import {ActionForm,LiveHeading,useOperations,pkr,choice,moneyField,amount,type Facility} from './live-shared';
const stages=['estimate','consent','preop','scheduled','operated','discharged','followup'];
type SurgeryCase={id:string;version:number;eye:string;procedure:string;stage:string;estimate:number;scheduled:string|null;patient:string;mrn:string;history:{stage:string;eye:string;notes:string;actor:string;at:string}[];documents:{id:string;filename:string;eye:string;witness:string;at:string}[]};
type Surgery={facilities:Facility[];encounters:{id:string;patient:string;mrn:string}[];cases:SurgeryCase[]};
export function SurgeryWorkspace(){const {t}=useLocale(),user=useSession(),live=useOperations<Surgery>('surgery');if(!live.data)return <LiveHeading {...live}/>;const d=live.data,write=user.permissions.includes('surgery:write'),eyes=[{value:'OD',label:'OD - Right eye'},{value:'OS',label:'OS - Left eye'}];return <div className="ops-workspace"><LiveHeading {...live}/>{write&&<ActionForm title="surgeryCreate" resource="surgery" onSaved={live.refresh} fields={[choice('encounterId','surgeryEncounter',d.encounters.map(e=>({value:e.id,label:e.patient+' / '+e.mrn}))),choice('facilityId','surgeryTheatre',d.facilities.filter(f=>f.type==='theatre').map(f=>({value:f.id,label:f.name}))),choice('eye','surgeryEye',eyes),{name:'procedure',label:'surgeryProcedure'},moneyField('estimate','surgeryEstimate')]} body={f=>({action:'create',encounterId:f.get('encounterId'),facilityId:f.get('facilityId'),eye:f.get('eye'),procedure:f.get('procedure'),estimate:amount(f,'estimate')})}/>}<section className="panel ops-chart-panel"><h2>{t('surgeryCases')}</h2>{!d.cases.length&&<p>{t('surgeryEmpty')}</p>}{d.cases.map(c=><details key={c.id} className="ops-daily-table"><summary>{c.patient} / {c.mrn} / {c.eye} / {c.procedure} / {c.stage}</summary><p>{pkr(c.estimate)}{c.scheduled&&' / '+new Date(c.scheduled).toLocaleString()}</p><h3>{t('surgeryHistory')}</h3><ol className="ops-stage-history">{c.history.map((h,i)=><li key={i}><strong>{h.stage} / {h.eye}</strong><span>{h.notes}<small>{h.actor} / {new Date(h.at).toLocaleString()}</small></span></li>)}</ol><h3>{t('surgeryConsent')}</h3>{c.documents.map(doc=><p key={doc.id}><a href={'/api/operations/consent?id='+doc.id}>{doc.filename}</a> / {doc.eye} / {doc.witness}</p>)}{write&&['estimate','consent','preop'].includes(c.stage)&&<ConsentUpload c={c} onSaved={live.refresh}/>} {write&&!['followup','cancelled'].includes(c.stage)&&<ActionForm key={c.version} title="surgeryAdvance" resource="surgery" onSaved={live.refresh} fields={[choice('stage','surgeryNext',[...(stages[stages.indexOf(c.stage)+1]?[{value:stages[stages.indexOf(c.stage)+1],label:stages[stages.indexOf(c.stage)+1]}]:[]),...(['estimate','consent','preop','scheduled'].includes(c.stage)?[{value:'cancelled',label:t('surgeryCancel')}]:[])]),choice('eye','surgeryEye',eyes),{name:'notes',label:'surgeryNotes',type:'textarea'},...(c.stage==='preop'?[{name:'scheduled',label:'surgeryScheduled' as const,type:'datetime-local' as const,optional:true}]:[])]} body={f=>({action:'advance',id:c.id,version:c.version,stage:f.get('stage'),eye:f.get('eye'),notes:f.get('notes'),...(f.get('scheduled')?{scheduled:new Date(String(f.get('scheduled'))).toISOString()}:{})})}/>}</details>)}</section></div>;}
function ConsentUpload({c,onSaved}:{c:SurgeryCase;onSaved:()=>void}){const {t}=useLocale(),[busy,setBusy]=useState(false),[error,setError]=useState('');return <form className="admin-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);f.set('caseId',c.id);setBusy(true);setError('');try{const result=await fetch('/api/operations/consent',{method:'POST',body:f});if(!result.ok){const body=await result.json();throw new Error(body.error);}form.reset();onSaved();}catch(e){setError(e instanceof Error?e.message:'Upload failed');}finally{setBusy(false);}}}><h4>{t('surgeryUpload')}</h4><label>{t('surgeryEye')}<select name="eye" required defaultValue=""><option value="">Select...</option><option>OD</option><option>OS</option></select></label><label>{t('surgeryWitness')}<input name="witness" required minLength={3} maxLength={160}/></label><label>{t('surgeryFile')}<input type="file" name="file" accept="application/pdf,image/png,image/jpeg" required/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="secondary-button" disabled={busy}>{t('surgeryUpload')}</button></form>;}
