"use client";
import { useEffect, useRef, useState } from "react";
import { CalendarDays, Check, Plus, Search, X } from "lucide-react";
import { api } from "@/lib/api-client";
import { bookingDateAllowed, type Appointment, type Clinic } from "@/lib/intake";
import { patientName, todayKarachi, type PatientList, type PatientSummary } from "@/lib/patients";
import type { MessageKey } from "@/lib/messages";
import { useLocale } from "../locale-provider";
import { useSession } from "../session-provider";
import { AppointmentActions } from "./appointment-actions";
import { ErrorNotice, intakeError, LiveStatus, RiskFlags, useLiveData } from "./shared";

export function AppointmentsWorkspace({ initialPatient, onBooked }: { initialPatient?: PatientSummary | null; onBooked?: () => void }) {
 const { t } = useLocale(), user = useSession(); const [date, setDate] = useState(todayKarachi), [booking, setBooking] = useState(!!initialPatient), [busy, setBusy] = useState<string | null>(null), [error, setError] = useState<MessageKey | null>(null), [success, setSuccess] = useState<MessageKey | null>(null);
 const live = useLiveData<{ appointments: Appointment[] }>(`/api/intake/appointments?date=${date}`);
 async function checkIn(id: string) { setBusy(id); setError(null); setSuccess(null); try { await api('/api/intake/checkin', { appointmentId: id }); setSuccess('checkInSaved'); live.refresh(); } catch (error) { setError(intakeError(error)); live.refresh(); } finally { setBusy(null); } }
 return <div className="intake-workspace"><section className="panel"><div className="registry-heading"><div><CalendarDays size={21}/><h2>{t("scheduleLabel")}</h2><span className="count-badge">{live.data?.appointments.length ?? '—'}</span></div>{user.permissions.includes('appointment:create') && <button type="button" className="primary-button" onClick={() => setBooking(true)}><Plus size={16}/>{t('bookAppointment')}</button>}</div>
 <div className="intake-filters"><label><span>{t('appointmentDate')}</span><input type="date" value={date} onChange={event => { if (event.target.value) setDate(event.target.value); }}/></label><button type="button" className="secondary-button" onClick={() => setDate(todayKarachi())}>{t('todayLabel')}</button><small>{t('localTimeLabel')}</small></div>
 <ErrorNotice error={error}/>{success && <p className="registration-success" role="status"><Check size={16}/>{t(success)}</p>}
 <LiveStatus {...live}/><div className="intake-table-wrap"><table className="patient-table"><thead><tr><th>{t('appointmentTime')}</th><th>{t('patientColumn')}</th><th>{t('clinicLabel')}</th><th>{t('doctorLabel')}</th><th>{t('recordColumn')}</th></tr></thead><tbody>{live.data?.appointments.map(item => <tr key={item.id} data-testid={`appointment-${item.id}`}><td><strong>{item.time}</strong><small>PKT</small></td><td><strong>{item.name}</strong><small>{item.mrn}</small><RiskFlags flags={item.flags}/></td><td>{item.clinic}</td><td>{item.doctor}</td><td>{!['booked','checked_in'].includes(item.status) ? <span>{item.status.replace('_',' ')}</span> : item.status === 'checked_in' ? <span className="intake-status"><Check size={13}/>{t('checkedIn')}</span> : user.permissions.includes('appointment:checkin') ? <button type="button" className="secondary-button" disabled={date !== todayKarachi() || !!busy || !!live.error} onClick={() => checkIn(item.id)}>{busy === item.id ? t('savingWorkup') : t('checkIn')}</button> : t('booked')}{user.permissions.includes('appointment:manage')&&<AppointmentActions item={item} onDone={live.refresh}/>}</td></tr>)}</tbody></table></div>{live.data?.appointments.length === 0 && <p className="intake-empty">{t('emptySchedule')}</p>}</section>
 {booking && <BookingDialog initialPatient={initialPatient} initialDate={date} onClose={() => { setBooking(false); onBooked?.(); }} onSaved={bookedDate => { setBooking(false); setDate(bookedDate); setSuccess('bookingSaved'); live.refresh(); onBooked?.(); }}/>}</div>;
}
function BookingDialog({ initialPatient, initialDate, onClose, onSaved }: { initialPatient?: PatientSummary | null; initialDate: string; onClose: () => void; onSaved: (date: string) => void }) {
 const { t } = useLocale(); const [walkin,setWalkin]=useState(false); const ref = useRef<HTMLDialogElement>(null);
 const [patient, setPatient] = useState<PatientSummary | null>(initialPatient ?? null), [query, setQuery] = useState(''), [patients, setPatients] = useState<PatientSummary[]>([]), [clinics, setClinics] = useState<Clinic[]>([]), [clinicId, setClinicId] = useState(''), [doctorId, setDoctorId] = useState(''), [date, setDate] = useState(bookingDateAllowed(initialDate) ? initialDate : todayKarachi()), [time, setTime] = useState(''), [slots, setSlots] = useState<string[]>([]), [error, setError] = useState<MessageKey | null>(null), [busy, setBusy] = useState(false), [searching, setSearching] = useState(false), [slotLoading, setSlotLoading] = useState(false);
 useEffect(() => { ref.current?.showModal(); const controller = new AbortController(); api<{ clinics: Clinic[] }>('/api/intake/clinics', undefined, { signal: controller.signal }).then(result => { setClinics(result.clinics); setClinicId(result.clinics[0]?.id ?? ''); }).catch(error => { if (!controller.signal.aborted) setError(intakeError(error)); }); return () => controller.abort(); }, []);
 const clinic = clinics.find(value => value.id === clinicId);
 useEffect(() => { setDoctorId(clinic?.doctors[0]?.id ?? ''); }, [clinic]);
 useEffect(() => { setTime(''); setSlots([]); if (!clinicId || !doctorId || !date) return; const controller = new AbortController(); setSlotLoading(true); api<{ slots: string[] }>(`/api/intake/slots?${new URLSearchParams({ facilityId: clinicId, doctorId, date })}`, undefined, { signal: controller.signal }).then(result => { setSlots(result.slots); setError(null); }).catch(error => { if (!controller.signal.aborted) setError(intakeError(error)); }).finally(() => { if (!controller.signal.aborted) setSlotLoading(false); }); return () => controller.abort(); }, [clinicId, doctorId, date]);
 async function search() { setSearching(true); setError(null); try { const result = await api<PatientList>('/api/patients/search', { query, page: 1 }); setPatients(result.patients); } catch(error) { setError(intakeError(error)); } finally { setSearching(false); } }
 async function save(event: React.FormEvent) { event.preventDefault(); if (!patient) return; setBusy(true); setError(null); try { await api(walkin?'/api/intake/walkin':'/api/intake/appointments', walkin?{patientId:patient.id,facilityId:clinicId,doctorId}:{ patientId: patient.id, facilityId: clinicId, doctorId, date, time }); onSaved(walkin?todayKarachi():date); } catch(error) { setError(intakeError(error)); } finally { setBusy(false); } }
 return <dialog ref={ref} className="intake-dialog booking-dialog" aria-labelledby="booking-title" onCancel={event => { event.preventDefault(); if (!busy) onClose(); }}><div className="patient-record-header"><div><p className="eyebrow">{t('appointments')}</p><h2 id="booking-title">{t('bookingTitle')}</h2></div><button type="button" disabled={busy} className="icon-button" aria-label={t('closeBooking')} onClick={onClose}><X size={20}/></button></div><div className="intake-dialog-body"><ErrorNotice error={error}/>
 {!patient ? <section><form className="patient-search" onSubmit={event => { event.preventDefault(); void search(); }}><div><Search size={17}/><input autoFocus aria-label={t('searchPatients')} placeholder={t('patientSearchPlaceholder')} value={query} maxLength={100} onChange={event => setQuery(event.target.value)}/></div><button className="secondary-button" disabled={searching}>{t('search')}</button></form><div className="booking-results">{patients.map(value => <button type="button" key={value.id} onClick={() => setPatient(value)}><strong>{patientName(value)}</strong><small>{value.mrn}</small><RiskFlags flags={value.flags}/></button>)}</div></section> : <div className="booking-patient"><span><small>{t('selectedPatient')}</small><strong>{patientName(patient)}</strong><span>{patient.mrn}</span></span><button type="button" className="text-button" onClick={() => setPatient(null)}>{t('changePatient')}</button><RiskFlags flags={patient.flags}/></div>}
 <form onSubmit={save}><label className="admin-check"><input type="checkbox" checked={walkin} onChange={e=>setWalkin(e.target.checked)}/>Walk-in: check in immediately today</label><div className="intake-form-grid"><label><span>{t('clinicLabel')}</span><select aria-label={t('clinicLabel')} required value={clinicId} onChange={event => setClinicId(event.target.value)}>{clinics.map(value => <option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label><span>{t('doctorLabel')}</span><select aria-label={t('doctorLabel')} required value={doctorId} onChange={event => setDoctorId(event.target.value)}>{clinic?.doctors.map(value => <option key={value.id} value={value.id}>{value.name}</option>)}</select></label><label><span>{t('appointmentDate')}</span><input required={!walkin} disabled={walkin} type="date" min={todayKarachi()} value={date} onChange={event => setDate(event.target.value)}/></label><label><span>{t('appointmentTime')}</span><select required={!walkin} value={time} disabled={slotLoading||walkin} onChange={event => setTime(event.target.value)}><option value="">{slotLoading ? t('intakeLoading') : t('chooseSlot')}</option>{slots.map(slot => <option key={slot}>{slot}</option>)}</select></label></div>
 {!clinics.length && <p>{t('noClinics')}</p>}{clinic && !slotLoading && !slots.length && <p>{t('noSlots')}</p>}<p className="intake-help">{t('clinicHours')}</p><div className="intake-dialog-actions"><button type="button" className="secondary-button" disabled={busy} onClick={onClose}>{t('bookingCancel')}</button><button className="primary-button" disabled={!patient || (!walkin&&(!time||slotLoading)) || busy}>{t(busy ? 'savingWorkup' : 'bookAppointment')}</button></div></form></div></dialog>;
}
