'use client';
import { useEffect,useState } from 'react';
import type { Appointment,Clinic } from '@/lib/intake';
import { api,ClientApiError } from '@/lib/api-client';
import { todayKarachi } from '@/lib/patients';
export function AppointmentActions({item,onDone}:{item:Appointment;onDone:()=>void}){const [action,setAction]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[clinics,setClinics]=useState<Clinic[]>([]),[facilityId,setFacility]=useState(item.facilityId),[doctorId,setDoctor]=useState(item.doctorId),[date,setDate]=useState(item.date>=todayKarachi()?item.date:todayKarachi()),[time,setTime]=useState(''),[slots,setSlots]=useState<string[]>([]);
 useEffect(()=>{if(action==='rescheduled')api<{clinics:Clinic[]}>('/api/intake/clinics').then(r=>setClinics(r.clinics)).catch(()=>setError('Unable to load clinics.'));},[action]);
 useEffect(()=>{if(action!=='rescheduled')return;const controller=new AbortController();setTime('');setSlots([]);api<{slots:string[]}>(`/api/intake/slots?${new URLSearchParams({facilityId,doctorId,date})}`,undefined,{signal:controller.signal}).then(r=>setSlots(r.slots)).catch(()=>{if(!controller.signal.aborted)setError('Unable to load available times.');});return()=>controller.abort();},[action,facilityId,doctorId,date]);
 if(item.status!=='booked')return null;
 return <div><button className="text-button" onClick={()=>setAction(action?'':'cancelled')}>Manage booking</button>{action&&<form className="admin-form" onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');try{await api('/api/intake/appointment-action',{id:item.id,version:item.version,action,reason,...(action==='rescheduled'?{booking:{facilityId,doctorId,date,time}}:{})});setAction('');onDone();}catch(e){setError(e instanceof ClientApiError&&e.status===409?'The appointment or slot changed. Refresh and try again.':'Unable to save this change.');}finally{setBusy(false);}}}><label>Action<select value={action} onChange={e=>setAction(e.target.value)}><option value="cancelled">Cancel appointment</option><option value="rescheduled">Reschedule</option><option value="no_show">Mark no-show</option></select></label>{action==='rescheduled'&&<><label>Clinic<select value={facilityId} onChange={e=>{setFacility(e.target.value);setDoctor(clinics.find(c=>c.id===e.target.value)?.doctors[0]?.id||'');}}>{clinics.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Doctor<select value={doctorId} onChange={e=>setDoctor(e.target.value)}>{clinics.find(c=>c.id===facilityId)?.doctors.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>New date<input type="date" min={todayKarachi()} required value={date} onChange={e=>setDate(e.target.value)}/></label><label>New time<select required value={time} onChange={e=>setTime(e.target.value)}><option value="">Choose a time</option>{slots.map(s=><option key={s}>{s}</option>)}</select></label></>}<label>Reason<input required minLength={8} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button className="primary-button" disabled={busy}>Save booking change</button></form>}</div>;
}
