'use client';

import { useMemo,useState } from 'react';
import { FileUp,FlaskConical,Trash2 } from 'lucide-react';
import { api,ClientApiError } from '@/lib/api-client';
import { INVESTIGATION_CATALOGUE,investigationInputSchema,type InvestigationKind,type InvestigationResult,type InvestigationStage } from '@/lib/investigations';
import type { MessageKey } from '@/lib/messages';
import { formatDate } from '../patients/patients-workspace';
import { ErrorNotice,intakeError } from './shared';

function localTime(){return new Date(Date.now()+5*3600000).toISOString().slice(0,16);}
function kindFor(stage:InvestigationStage){return (Object.entries(INVESTIGATION_CATALOGUE).find(([,value])=>value.stage===stage)?.[0]??'visual_field') as InvestigationKind;}

export function InvestigationPanel({encounterId,stage,results,onChanged}:{encounterId:string;stage:InvestigationStage;results:InvestigationResult[];onChanged:()=>Promise<void>}){
 const [kind,setKind]=useState<InvestigationKind>(()=>kindFor(stage)),[eye,setEye]=useState<'OD'|'OS'|'OU'>('OU'),[performedAt,setPerformedAt]=useState(localTime()),[device,setDevice]=useState(''),[findings,setFindings]=useState(''),[measurements,setMeasurements]=useState<Record<string,string|boolean>>({}),[busy,setBusy]=useState(false),[error,setError]=useState<MessageKey|null>(null);
 const choices=useMemo(()=>Object.entries(INVESTIGATION_CATALOGUE).filter(([,value])=>value.stage===stage) as [InvestigationKind,typeof INVESTIGATION_CATALOGUE[InvestigationKind]][],[stage]);
 const definition=INVESTIGATION_CATALOGUE[kind];
 function changeKind(value:InvestigationKind){setKind(value);setMeasurements({});}
 async function save(event:React.FormEvent){event.preventDefault();setError(null);const values=Object.fromEntries(Object.entries(measurements).filter(([,value])=>value!=='' ).map(([key,value])=>{const field=definition.fields.find(item=>item.key===key);return [key,field?.type==='number'?Number(value):value];}));const parsed=investigationInputSchema.safeParse({encounterId,stage,kind,eye,performedAt:new Date(`${performedAt}:00+05:00`).toISOString(),device,findings,measurements:values});if(!parsed.success){setError('investigationInvalid');return;}setBusy(true);try{await api('/api/intake/investigations',parsed.data);setFindings('');setMeasurements({});await onChanged();}catch(value){setError(intakeError(value));}finally{setBusy(false);}}
 async function remove(id:string){setBusy(true);setError(null);try{const response=await fetch('/api/intake/investigations?id='+id,{method:'DELETE'});const body=await response.json();if(!response.ok)throw new ClientApiError(body.error??'serviceUnavailable',response.status,body);await onChanged();}catch(value){setError(intakeError(value));}finally{setBusy(false);}}
 async function upload(result:InvestigationResult,file:File){setBusy(true);setError(null);try{const form=new FormData();form.set('investigationId',result.id);form.set('file',file);const response=await fetch('/api/intake/investigation-evidence',{method:'POST',body:form});const body=await response.json();if(!response.ok)throw new ClientApiError(body.error??'serviceUnavailable',response.status,body);await onChanged();}catch(value){setError(intakeError(value));}finally{setBusy(false);}}
 return <section className="investigation-panel"><div><h3><FlaskConical size={18}/>Structured investigations</h3><p>Record the eye-specific test or image result. Attach the source image or PDF when it is available.</p></div><ErrorNotice error={error}/>
  <form className="investigation-form" onSubmit={save}><label><span>Investigation</span><select value={kind} onChange={event=>changeKind(event.target.value as InvestigationKind)}>{choices.map(([value,meta])=><option value={value} key={value}>{meta.label}</option>)}</select></label><label><span>Eye</span><select value={eye} onChange={event=>setEye(event.target.value as typeof eye)}><option>OD</option><option>OS</option><option>OU</option></select></label><label><span>Performed at (PKT)</span><input type="datetime-local" required value={performedAt} onChange={event=>setPerformedAt(event.target.value)}/></label><label><span>Device (optional)</span><input maxLength={120} value={device} onChange={event=>setDevice(event.target.value)}/></label>
   {definition.fields.map(field=><label key={field.key}><span>{field.label}{field.unit?' ('+field.unit+')':''}</span>{field.type==='boolean'?<select value={String(measurements[field.key]??'')} onChange={event=>setMeasurements(value=>({...value,[field.key]:event.target.value==='true'}))}><option value="">Not recorded</option><option value="true">Yes</option><option value="false">No</option></select>:<input type={field.type} min={field.min} max={field.max} step={field.type==='number'?'0.01':undefined} value={String(measurements[field.key]??'')} onChange={event=>setMeasurements(value=>({...value,[field.key]:event.target.value}))}/>}</label>)}
   <label className="investigation-findings"><span>Findings</span><textarea required minLength={3} maxLength={2000} value={findings} onChange={event=>setFindings(event.target.value)}/></label><button className="secondary-button" disabled={busy}>Record investigation</button></form>
  <div className="investigation-list">{results.filter(result=>result.stage===stage).map(result=><article key={result.id}><header><div><strong>{INVESTIGATION_CATALOGUE[result.kind].label} · {result.eye}</strong><small>{formatDate(result.performedAt,true)} · {result.author}</small></div><button type="button" className="icon-button" aria-label="Remove investigation" disabled={busy} onClick={()=>remove(result.id)}><Trash2 size={15}/></button></header><p>{result.findings}</p>{Object.keys(result.measurements).length>0&&<dl>{Object.entries(result.measurements).map(([key,value])=><div key={key}><dt>{key.replace(/([A-Z])/g,' $1')}</dt><dd>{String(value)}</dd></div>)}</dl>}<div className="investigation-evidence">{result.evidence.map(file=><a href={'/api/intake/investigation-evidence?id='+file.id} target="_blank" rel="noreferrer" key={file.id}>{file.filename}</a>)}{result.evidence.length<5&&<label className="secondary-button"><FileUp size={14}/>Attach image or PDF<input hidden type="file" accept="image/jpeg,image/png,application/pdf" disabled={busy} onChange={event=>{const file=event.target.files?.[0];if(file)void upload(result,file);event.currentTarget.value='';}}/></label>}</div></article>)}{results.filter(result=>result.stage===stage).length===0&&<p className="intake-empty">No structured investigation has been recorded at this checkpoint.</p>}</div>
 </section>;
}
