"use client";
import { useState } from "react";
import { ArrowRight, Clock3, ListOrdered } from "lucide-react";
import { api } from "@/lib/api-client";
import { STAGES, type Encounter } from "@/lib/intake";
import type { MessageKey } from "@/lib/messages";
import { useLocale } from "../locale-provider";
import { useSession } from "../session-provider";
import { formatDate } from "../patients/patients-workspace";
import { ErrorNotice, intakeError, LiveStatus, RiskFlags, useLiveData } from "./shared";
import { WorkupDialog } from "./workup-dialog";
import { ReasonDialog } from "../reason-dialog";
export function QueueWorkspace({ workupOnly = false }: { workupOnly?: boolean }) {
 const { t } = useLocale(), user = useSession(); const live = useLiveData<{ encounters: Encounter[]; serverNow: string }>('/api/intake/queue');
 const [clinic, setClinic] = useState(''), [selected, setSelected] = useState<string | null>(null), [busy, setBusy] = useState<string | null>(null), [error, setError] = useState<MessageKey | null>(null);
 const [pending, setPending] = useState<{ item: Encounter; action: string } | null>(null);
 const encounters = live.data?.encounters.filter(value => !clinic || value.facilityId === clinic) ?? [];
 async function start(item: Encounter) { setBusy(item.id); setError(null); try { await api('/api/intake/transition', { encounterId: item.id, version: item.version, to: 'workup' }); live.refresh(); if (user.permissions.includes('workup:read')) setSelected(item.id); } catch(error) { setError(intakeError(error)); live.refresh(); } finally { setBusy(null); } }
 async function manage(item:Encounter,action:string,reason:string){setBusy(item.id);try{await api('/api/intake/queue-action',{id:item.id,version:item.version,action,reason});live.refresh();}catch(e){setError(intakeError(e));}finally{setBusy(null);setPending(null);}}
 return <div className="intake-workspace"><div className="queue-toolbar"><div><ListOrdered size={20}/><label><span className="sr-only">{t('clinicLabel')}</span><select value={clinic} onChange={event => setClinic(event.target.value)}><option value="">{t('allClinics')}</option>{Array.from(new Map(live.data?.encounters.map(value => [value.facilityId, value.clinic])).entries()).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label></div><LiveStatus {...live}/></div><ErrorNotice error={error}/>
 <div className={`queue-board ${workupOnly ? 'workup-board' : ''}`}>{STAGES.map(stage => <section className={`queue-column stage-${stage}`} key={stage}><header><span/><h2>{t(`stage_${stage}`)}</h2><strong>{encounters.filter(value => value.stage === stage).length}</strong></header><div>{encounters.filter(value => value.stage === stage).map(item => <article className="queue-card" key={item.id} data-testid={`queue-${item.id}`}><div className="queue-card-patient"><span className="patient-avatar">{item.name[0]}</span><div><h3>{item.name}</h3><small>{item.mrn}</small></div></div><RiskFlags flags={item.flags}/>{item.priority==='urgent'&&<strong className="ops-tag warning">Urgent</strong>}<dl><div><dt>{t('clinicLabel')}</dt><dd>{item.clinic}</dd></div><div><dt>{t('doctorLabel')}</dt><dd>{item.doctor}</dd></div></dl><p className="queue-arrival">{t('arrivalLabel')} {formatDate(item.checkedInAt, true)}</p><p className="queue-clock"><Clock3 size={13}/>{Math.max(0, Math.floor((new Date(live.data!.serverNow).getTime() - new Date(item.stageAt).getTime()) / 60_000))} {t('elapsedLabel')}</p>{stage === 'dilation' && item.dilationReadyAt && <p className="dilation-countdown">{new Date(item.dilationReadyAt) > new Date(live.data!.serverNow) ? `${Math.ceil((new Date(item.dilationReadyAt).getTime() - new Date(live.data!.serverNow).getTime()) / 60000)} ${t('dilationRemaining')}` : t('dilationElapsed')}</p>}<p className="queue-workup-status">{t(item.workupVersion ? 'workupRecorded' : 'workupPending')}{item.workupVersion > 0 && ` · v${item.workupVersion}`}</p>
 <div className="queue-card-actions">{user.permissions.includes("queue:manage")&&<>{stage==='pharmacy_billing'&&<button className="primary-button" disabled={!!busy} onClick={()=>setPending({item,action:'completed'})}>{t('completeVisit')}</button>}<button className="text-button" disabled={!!busy} onClick={()=>setPending({item,action:item.priority==='urgent'?'routine':'urgent'})}>{item.priority==='urgent'?'Set routine':'Mark urgent'}</button>{!['consultation','pharmacy_billing'].includes(stage)&&<button className="text-button" disabled={!!busy} onClick={()=>setPending({item,action:'left_before_seen'})}>Left before consultation</button>}</>}{stage === 'waiting' && user.permissions.includes('queue:workup') && <button type="button" className="primary-button" disabled={!!busy || !!live.error} onClick={() => start(item)}>{t('startWorkup')}<ArrowRight size={13}/></button>}{user.permissions.includes('workup:read') && <button type="button" className="secondary-button" onClick={() => setSelected(item.id)}>{t(user.permissions.includes('workup:write') && stage === 'workup' ? 'openWorkup' : 'viewWorkup')}</button>}</div></article>)}{!encounters.some(value => value.stage === stage) && <p className="queue-empty">{t('emptyQueue')}</p>}</div></section>)}</div><p className="intake-help">{t('intakeBoundary')}</p>
 {pending && <ReasonDialog title="queueChangeReason" busy={busy===pending.item.id} onClose={()=>setPending(null)} onConfirm={reason=>void manage(pending.item,pending.action,reason)}/>}
  {selected && <WorkupDialog id={selected} onClose={() => { setSelected(null); live.refresh(); }} onSaved={live.refresh}/>}</div>;
}
